/**
 * @module 03_configuration
 * @description APIs, user settings, default_site_info (100+ sites)
 * @lines 917-1340
 * 
 * Extracted from auto_feed.user.js
 * DO NOT EDIT - Auto-generated by split_modules.py
 */

const apis = ['https://api.iyuu.cn/App.Movie.Ptgen', 'https://ptgen.tju.pt/infogen'];
var api_chosen = GM_getValue('api_chosen') === undefined ? 3 : GM_getValue('api_chosen');
var tldomain = GM_getValue('tldomain') === undefined ? 0 : GM_getValue('tldomain');
var imdb2db_chosen = GM_getValue('imdb2db_chosen') === undefined ? 0 : GM_getValue('imdb2db_chosen');

//用来转存海报使用的ptpimg的key,打开首页即可获取
var used_ptp_img_key = GM_getValue('used_ptp_img_key') === undefined ? '' : GM_getValue('used_ptp_img_key');

var used_tl_rss_key = GM_getValue('used_tl_rss_key') === undefined ? '' : GM_getValue('used_tl_rss_key');
var douban_poster_rehost = GM_getValue('douban_poster_rehost') === undefined ? 0 : GM_getValue('douban_poster_rehost');

//用来获取TMDB的key，需要使用请自行申请
var used_tmdb_key = GM_getValue('used_tmdb_key') === undefined ? '0f79586eb9d92afa2b7266f7928b055c' : GM_getValue('used_tmdb_key');

//是否匿名，默认开启匿名选项
var if_uplver = GM_getValue('if_uplver') === undefined ? 1 : GM_getValue('if_uplver');

var if_douban_jump = GM_getValue('if_douban_jump') === undefined ? 1 : GM_getValue('if_douban_jump');
var if_imdb_jump = GM_getValue('if_imdb_jump') === undefined ? 1 : GM_getValue('if_imdb_jump');

var remote_server = GM_getValue('remote_server') === undefined ? null : JSON.parse(GM_getValue('remote_server'));

//额外的功能选项
const default_extra_settings = {
  'ptp_show_douban': { 'title': 'PTP中文', 'enable': 1 },
  'ptp_show_group_name': { 'title': 'PTP组名', 'enable': 1 },
  'hdb_show_douban': { 'title': 'HDB中文', 'enable': 1 },
  'hdb_show_discount_color': { 'title': 'HDB折扣', 'enable': 1 },
  'btn_dark_color': { 'title': '妞暗色系', 'enable': 1 },
  'other_douban_info': { 'title': '中文信息', 'enable': 1 },
};
var extra_settings = GM_getValue('extra_settings') === undefined ? default_extra_settings : JSON.parse(GM_getValue('extra_settings'));
if (!extra_settings.hasOwnProperty('btn_dark_color')) {
  extra_settings = default_extra_settings;
}
if (!extra_settings.hasOwnProperty('other_douban_info')) {
  extra_settings.other_douban_info = default_extra_settings.other_douban_info;
}

const all_sites_show_douban = extra_settings.other_douban_info.enable;

var hdb_hide_douban = GM_getValue('hdb_hide_douban') === undefined ? 0 : GM_getValue('hdb_hide_douban');

//0表示前边，1表示后边
var ptp_name_location = GM_getValue('ptp_name_location') === undefined ? 1 : GM_getValue('ptp_name_location');

//支持转发的站点列表，可以自行取消注释
const default_site_info = {
  '13City': { 'url': 'https://13city.org/', 'enable': 1 },
  '1PTBA': { 'url': 'https://1ptba.com/', 'enable': 1 },
  '52PT': { 'url': 'https://52pt.site/', 'enable': 1 },
  'ACM': { 'url': 'https://eiga.moi/', 'enable': 1 },
  'ANT': { 'url': 'https://anthelion.me/', 'enable': 1 },
  'avz': { 'url': 'https://avistaz.to/', 'enable': 1 },
  'Audiences': { 'url': 'https://audiences.me/', 'enable': 1 },
  'BHD': { 'url': 'https://beyond-hd.me/', 'enable': 1 },
  'Aither': { 'url': 'https://aither.cc/', 'enable': 1 },
  'BLU': { 'url': 'https://blutopia.cc/', 'enable': 1 },
  'BTN': { 'url': 'https://broadcasthe.net/', 'enable': 1 },
  'BYR': { 'url': 'https://byr.pt/', 'enable': 1 },
  'BTSchool': { 'url': 'https://pt.btschool.club/', 'enable': 1 },
  'CarPt': { 'url': 'https://carpt.net/', 'enable': 1 },
  'CG': { 'url': 'http://cinemageddon.net/', 'enable': 1 },
  'CMCT': { 'url': "https://springsunday.net/", 'enable': 1 },
  'CNZ': { 'url': 'https://cinemaz.to/', 'enable': 1 },
  'CHDBits': { 'url': "https://ptchdbits.co/", 'enable': 1 },
  'DiscFan': { 'url': 'https://discfan.net/', 'enable': 1 },
  'Dragon': { 'url': 'https://www.dragonhd.xyz/', 'enable': 1 },
  'FreeFarm': { 'url': 'https://pt.0ff.cc/', 'enable': 1 },
  'GPW': { 'url': 'https://greatposterwall.com/', 'enable': 1 },
  'HaiDan': { 'url': 'https://www.haidan.video/', 'enable': 1 },
  'HDArea': { 'url': 'https://hdarea.club/', 'enable': 1 },
  'HDB': { 'url': 'https://hdbits.org/', 'enable': 1 },
  'HDCity': { 'url': 'https://hdcity.city/', 'enable': 1 },
  'HDDolby': { 'url': 'https://www.hddolby.com/', 'enable': 1 },
  'HDF': { 'url': 'https://hdf.world/', 'enable': 1 },
  'HDfans': { 'url': 'http://hdfans.org/', 'enable': 1 },
  'HDHome': { 'url': 'https://hdhome.org/', 'enable': 1 },
  'DarkLand': { 'url': 'https://darkland.top/', 'enable': 1 },
  'HDRoute': { 'url': 'http://hdroute.org/', 'enable': 1 },
  'HDSky': { 'url': 'https://hdsky.me/', 'enable': 1 },
  'HDSpace': { 'url': 'https://hd-space.org/', 'enable': 1 },
  'HDT': { 'url': 'https://hd-torrents.org/', 'enable': 1 },
  'HDTime': { 'url': 'https://hdtime.org/', 'enable': 1 },
  'HDU': { 'url': 'https://pt.upxin.net/', 'enable': 1 },
  'HDVideo': { 'url': 'https://hdvideo.top/', 'enable': 1 },
  'HD-Only': { 'url': 'https://hd-only.org/', 'enable': 1 },
  'HITPT': { 'url': 'https://www.hitpt.com/', 'enable': 1 },
  'HUDBT': { 'url': 'https://hudbt.hust.edu.cn/', 'enable': 1 },
  'iTS': { 'url': 'https://shadowthein.net/', 'enable': 1 },
  'JoyHD': { 'url': 'https://www.joyhd.net/', 'enable': 1 },
  'KG': { 'url': 'https://karagarga.in/', 'enable': 1 },
  'MTeam': { 'url': 'https://kp.m-team.cc/', 'enable': 1 },
  'MTV': { 'url': 'https://www.morethantv.me/', 'enable': 1 },
  'NanYang': { 'url': 'https://nanyangpt.com/', 'enable': 1 },
  'NexusHD': { 'url': 'https://www.nexushd.org/', 'enable': 1 },
  'NBL': { 'url': 'https://nebulance.io/', 'enable': 1 },
  'NPUPT': { 'url': 'https://npupt.com/', 'enable': 1 },
  'OpenCD': { 'url': 'https://open.cd/', 'enable': 1 },
  'OPS': { 'url': 'https://orpheus.network/', 'enable': 1 },
  'Oshen': { 'url': 'http://www.oshen.win/', 'enable': 1 },
  'OurBits': { 'url': 'https://ourbits.club/', 'enable': 1 },
  'PHD': { 'url': 'https://privatehd.to/', 'enable': 1 },
  'PigGo': { 'url': 'https://piggo.me/', 'enable': 1 },
  'PTCafe': { 'url': 'https://ptcafe.club/', 'enable': 1 },
  'PTChina': { 'url': 'https://ptchina.org/', 'enable': 1 },
  'PTer': { 'url': 'https://pterclub.net/', 'enable': 1 },
  'PThome': { 'url': 'https://www.pthome.net/', 'enable': 1 },
  'PTP': { 'url': 'https://passthepopcorn.me/', 'enable': 1 },
  'PTsbao': { 'url': 'https://ptsbao.club/', 'enable': 1 },
  'PTT': { 'url': 'https://www.pttime.org/', 'enable': 1 },
  'PuTao': { 'url': 'https://pt.sjtu.edu.cn/', 'enable': 1 },
  'RED': { 'url': 'https://redacted.sh/', 'enable': 1 },
  'SC': { 'url': 'https://secret-cinema.pw/', 'enable': 1 },
  'SoulVoice': { 'url': 'https://pt.soulvoice.club/', 'enable': 1 },
  'TCCF': { 'url': 'https://et8.org/', 'enable': 1 },
  'Tik': { 'url': 'https://cinematik.net/', 'enable': 1 },
  'TJUPT': { 'url': 'https://www.tjupt.org/', 'enable': 1 },
  'TLFbits': { 'url': 'http://pt.eastgame.org/', 'enable': 1 },
  'TTG': { 'url': 'https://totheglory.im/', 'enable': 1 },
  'TVV': { 'url': 'http://tv-vault.me/', 'enable': 1 },
  'UHD': { 'url': 'https://uhdbits.org/', 'enable': 1 },
  'UltraHD': { 'url': 'https://ultrahd.net/', 'enable': 1 },
  'WT-Sakura': { 'url': 'https://wintersakura.net/', 'enable': 1 },
  'xthor': { 'url': 'https://xthor.tk/', 'enable': 1 },
  'YDY': { 'url': 'https://pt.hdbd.us/', 'enable': 1 },
  'ITZMX': { 'url': 'https://pt.itzmx.com/', 'enable': 1 },
  'Monika': { 'url': 'https://monikadesign.uk/', 'enable': 1 },
  'ZMPT': { 'url': 'https://zmpt.cc/', 'enable': 1 },
  'ICC': { 'url': 'https://www.icc2022.com/', 'enable': 1 },
  'CyanBug': { 'url': 'https://cyanbug.net/', 'enable': 1 },
  'ZHUQUE': { 'url': 'https://zhuque.in/', 'enable': 1 },
  'YemaPT': { 'url': 'https://www.yemapt.org/', 'enable': 1 },
  '海棠': { 'url': 'https://www.htpt.cc/', 'enable': 1 },
  '杏林': { 'url': 'https://xingtan.one/', 'enable': 1 },
  'UBits': { 'url': 'https://ubits.club/', 'enable': 1 },
  'OKPT': { 'url': 'https://www.okpt.net/', 'enable': 1 },
  'GGPT': { 'url': 'https://www.gamegamept.com/', 'enable': 1 },
  'RS': { 'url': 'https://resource.xidian.edu.cn/', 'enable': 1 },
  'Panda': { 'url': 'https://pandapt.net/', 'enable': 1 },
  'KuFei': { 'url': 'https://kufei.org/', 'enable': 1 },
  'RouSi': { 'url': 'https://rousi.pro/', 'enable': 1 },
  'GTK': { 'url': 'https://pt.gtk.pw/', 'enable': 1 },
  '麒麟': { 'url': 'https://www.hdkyl.in/', 'enable': 1 },
  'AGSV': { 'url': 'https://www.agsvpt.com/', 'enable': 1 },
  'ECUST': { 'url': 'https://pt.ecust.pp.ua/', 'enable': 1 },
  'iloli': { 'url': 'https://mua.xloli.cc/', 'enable': 1 },
  'CrabPt': { 'url': 'https://crabpt.vip/', 'enable': 1 },
  'QingWa': { 'url': 'https://qingwapt.com/', 'enable': 1 },
  'FNP': { 'url': 'https://fearnopeer.com/', 'enable': 1 },
  'OnlyEncodes': { 'url': 'https://onlyencodes.cc/', 'enable': 1 },
  'PTFans': { 'url': 'https://ptfans.cc/', 'enable': 1 },
  '影': { 'url': 'https://star-space.net/', 'enable': 1 },
  'PTzone': { 'url': 'https://ptzone.xyz/', 'enable': 1 },
  '雨': { 'url': 'https://raingfh.top/', 'enable': 1 },
  'PTLGS': { 'url': 'https://ptlgs.org/', 'enable': 1 },
  'NJTUPT': { 'url': 'https://njtupt.top/', 'enable': 1 },
  'LemonHD': { 'url': 'https://lemonhd.club/', 'enable': 1 },
  'ReelFliX': { 'url': 'https://reelflix.xyz/', 'enable': 1 },
  'HDClone': { 'url': 'https://pt.hdclone.top/', 'enable': 1 },
  'CDFile': { 'url': 'https://pt.cdfile.org/', 'enable': 1 },
  'HDBAO': { 'url': 'https://hdbao.cc/', 'enable': 1 },
  'AFUN': { 'url': 'https://www.ptlover.cc/', 'enable': 1 },
  'DevTracker': { 'url': 'https://www.devtracker.me/', 'enable': 1 },
  '唐门': { 'url': 'https://tmpt.top/', 'enable': 1 },
  '天枢': { 'url': 'https://dubhe.site/', 'enable': 1 },
  '财神': { 'url': 'https://cspt.top/', 'enable': 1 },
  '星陨阁': { 'url': 'https://pt.xingyungept.org/', 'enable': 1 },
  '樱花': { 'url': 'http://pt.ying.us.kg/', 'enable': 1 },
  '我好闲': { 'url': 'http://whax.net/', 'enable': 1 },
  '下水道': { 'url': 'https://sewerpt.com/', 'enable': 1 },
  '柠檬不甜': { 'url': 'https://lemonhd.net/', 'enable': 1 },
  'RailgunPT': { 'url': 'https://bilibili.download/', 'enable': 1 },
  'MyPT': { 'url': 'https://cc.mypt.cc/', 'enable': 1 },
  'LaJiDui': { 'url': 'https://pt.lajidui.top/', 'enable': 1 },
  'PTSkit': { 'url': 'https://www.ptskit.org/', 'enable': 1 },
  'MARCH': { 'url': 'https://duckboobee.org/', 'enable': 1 },
  'NovaHD': { 'url': 'https://pt.novahd.top/', 'enable': 1 },
  'LuckPT': { 'url': 'https://pt.luckpt.de/', 'enable': 1 },
  'Tokyo': { 'url': 'https://www.tokyopt.xyz/', 'enable': 1 },
  'ALing': { 'url': 'https://pt.aling.de/', 'enable': 1 },
  'LongPT': { 'url': 'https://longpt.org/', 'enable': 1 },
  '藏宝阁': { 'url': 'https://cangbao.ge/', 'enable': 1 },
  '未来幻境': { 'url': 'https://nex.jivon.de/', 'enable': 1 },
  '自然': { 'url': 'http://zrpt.cc/', 'enable': 1 },
  'SBPT': { 'url': 'https://sbpt.link/', 'enable': 1 },
  '慕雪阁': { 'url': 'https://pt.muxuege.org/', 'enable': 1 },
  'YHPP': { 'url': 'https://www.yhpp.cc/', 'enable': 1 },
  '52MOVIE': { 'url': 'https://www.52movie.top/', 'enable': 1 },
  '好学': { 'url': 'https://www.hxpt.org/', 'enable': 1 },
  '躺平': { 'url': 'https://www.tangpt.top/', 'enable': 1 },
  'BaoZi': { 'url': 'https://p.t-baozi.cc/', 'enable': 1 }
};

var chd_use_backup_url = GM_getValue('chd_use_backup_url') === undefined ? 0 : GM_getValue('chd_use_backup_url');
if (chd_use_backup_url) {
  var region_code = GM_getValue('region_code');
  if (region_code) {
    default_site_info.CHDBits.url = `https://${region_code}.chddiy.xyz/`;
  } else {
    fetch('https://ipapi.co/json/') // 发送GET请求到ipapi
      .then(response => response.json()) // 解析响应的JSON数据
      .then(data => {
        region_code = data.region_code.toLowerCase();
        GM_setValue('region_code', region_code);
      })
      .catch(error => {
        console.log("发生错误: " + error);
      }
      );
  }
}

var nhd_use_v6_url = GM_getValue('nhd_use_v6_url') === undefined ? 0 : GM_getValue('nhd_use_v6_url');
if (nhd_use_v6_url) {
  default_site_info.NexusHD.url = `https://v6.nexushd.org/`;
}

//初始化数据site_order/used_site_info等等
var site_order = GM_getValue('site_order') === undefined ? Object.keys(default_site_info).sort() : JSON.parse(GM_getValue('site_order')).split(',');

var used_site_info = GM_getValue('used_site_info');
var if_new_site_added = false;
if (used_site_info === undefined) {
  used_site_info = default_site_info;
  GM_setValue('used_site_info', JSON.stringify(used_site_info));
} else {
  //预防有新加的站点没有加上的。
  used_site_info = JSON.parse(used_site_info);
  for (key in default_site_info) {
    if (!used_site_info.hasOwnProperty(key)) {
      used_site_info[key] = default_site_info[key];
      if_new_site_added = true;
    } else if (default_site_info[key].url != used_site_info[key].url && ['AGSV', 'QingWa', 'MTeam'].indexOf(key) < 0) {
      used_site_info[key].url = default_site_info[key].url
    }
    if (site_order.indexOf(key) < 0) {
      site_order.push(key);
    }
  }
  for (key in used_site_info) {
    if (!default_site_info.hasOwnProperty(key)) {
      delete used_site_info[key];
      if (site_order.indexOf(key) >= 0) {
        site_order = site_order.filter(function (item) {
          return item != key;
        });
      }
      if_new_site_added = true;
    }
  }
  site_order = site_order.filter(function (item) {
    if (!default_site_info.hasOwnProperty(item)) {
      return false;
    } else {
      return true;
    }
  });
}
if (if_new_site_added) {
  GM_setValue('used_site_info', JSON.stringify(used_site_info));
  GM_setValue('site_order', JSON.stringify(site_order.join(',')));
}

// 修正北洋、铂金和皇后有www和不带www两个域名。
if (site_url.match(/^http(s)?:\/\/(www.)?(tjupt.org|open.cd|pthome.net)\//)) {
  var site_domain = site_url.match(/^http(s)?:\/\/(www.)?(tjupt.org|open.cd|pthome.net)\//)[0];
  if (site_domain.match(/tjupt/)) {
    used_site_info.TJUPT.url = site_domain;
  } else if (site_domain.match(/pthome/)) {
    used_site_info.PThome.url = site_domain;
  } else {
    used_site_info.OpenCD.url = site_domain;
  }
}

if (site_url.match(/^https:\/\/hdts.ru\/.*/)) {
  used_site_info.HDT.url = 'https://hdts.ru/';
} else if (site_url.match(/^https:\/\/hd-torrents.org\/.*/)) {
  used_site_info.HDT.url = 'https://hd-torrents.org/';
}

if (site_url.match(/^https:\/\/kp.m-team.cc\/.*/)) {
  used_site_info.MTeam.url = 'https://kp.m-team.cc/';
} else if (site_url.match(/^https:\/\/zp.m-team.io\/.*/)) {
  used_site_info.MTeam.url = 'https://zp.m-team.io/';
} else if (site_url.match(/^https:\/\/next.m-team.cc\/.*/)) {
  used_site_info.MTeam.url = 'https://next.m-team.cc/';
}

if (site_url.match(/^https?:\/\/backup.landof.tv\/.*/)) {
  used_site_info.BTN.url = 'https://backup.landof.tv/';
} else if (site_url.match(/^https?:\/\/broadcasthe.net\/.*/)) {
  used_site_info.BTN.url = 'https://broadcasthe.net/';
}
if (site_url.match(/^https?:\/\/(www.)?qingwapt.org\/.*/)) {
  used_site_info.QingWa.url = 'https://www.qingwapt.org/';
} else if (site_url.match(/^https?:\/\/qingwapt.com\/.*/)) {
  used_site_info.QingWa.url = 'https://qingwapt.com/';
}
if (site_url.match(/^https?:\/\/www.agsvpt.com\/.*/)) {
  used_site_info.AGSV.url = 'https://www.agsvpt.com/';
} else if (site_url.match(/^https?:\/\/abroad.agsvpt.com\/.*/)) {
  used_site_info.AGSV.url = 'https://abroad.agsvpt.com/';
} else if (site_url.match(/^https?:\/\/new.agsvpt.com\/.*/)) {
  used_site_info.AGSV.url = 'https://new.agsvpt.com/';
} else if (site_url.match(/^https?:\/\/pt.agsvpt.cn\/.*/)) {
  used_site_info.AGSV.url = 'https://pt.agsvpt.cn/';
} else if (site_url.match(/^https?:\/\/new.agsvpt.cn\/.*/)) {
  used_site_info.AGSV.url = 'https://new.agsvpt.cn/';
}

GM_setValue('used_site_info', JSON.stringify(used_site_info));

//支持快速搜索的默认站点列表，可自行添加，举例：imdbid表示tt123456, imdbno表示123456，search_name表示the big bang thoery
const default_search_list = [
  `<a href="https://passthepopcorn.me/torrents.php?searchstr={imdbid}" target="_blank">PTP</a>`,
  `<a href="https://broadcasthe.net/torrents.php?action=advanced&imdb={imdbid}" target="_blank">BTN</a>`,
  `<a href="https://hdbits.org/browse.php?search={imdbid}" target="_blank">HDB</a>`,
  `<a href="https://karagarga.in/browse.php?search={imdbid}&search_type=imdb" target="_blank">KG</a>`,
  `<a href="http://cinemageddon.net/browse.php?search={imdbid}&proj=0&descr=1" target="_blank">CG</a>`,
  `<a href="https://filelist.io/browse.php?search={imdbid}" target="_blank">FileList</a>`,
  `<a href="https://beyond-hd.me/torrents?imdb={imdbid}" target="_blank">BHD</a>`,
  `<a href="https://blutopia.cc/torrents?imdbid={imdbno}&perPage=25&imdbId={imdbno}" target="_blank">BLU</a>`,
  `<a href="https://secret-cinema.pw/torrents.php?action=advanced&searchsubmit=1&filter_cat=1&cataloguenumber={imdbid}" target="_blank">SC</a>`,
  `<a href="https://darkland.top/torrents?imdbId={imdbid}#page/1" target="_blank">DarkLand</a>`,
  `<a href="https://totheglory.im/browse.php?search_field=imdb{imdbno}&c=M" target="_blank">TTG</a>`,
  `<a href="https://hd-torrents.org/torrents.php?&search={imdbid}&active=0" target="_blank">HDT</a>`,
  `<a href="https://hd-space.org/index.php?page=torrents&search={imdbno}&active=1&options=2" target="_blank">HDSpace</a>`,
  `<a href="http://hdroute.org/browse.php?action=s&imdb={imdbno}" target="_blank">HDR</a>`,
  `<a href="https://hdf.world/torrents.php?searchstr={search_name}" target="_blank">HDF</a>`,
  `<a href="https://privatehd.to/torrents?in=1&search={search_name}" target="_blank">PHD</a>`,
  `<a href="https://avistaz.to/torrents?in=1&search={search_name}" target="_blank">AVZ</a>`,
  `<a href="https://cinemaz.to/torrents?in=1&search={search_name}" target="_blank">CNZ</a>`,
  `<a href="https://xthor.tk/browse.php?sch={search_name}" target="_blank">xTHOR</a>`,
  `<a href="https://cinematik.net/torrents?imdbId={imdbid}#page/1" target="_blank">Tik</a>`,
  `<a href="https://nzbs.in/search?query=imdb:{imdbid}" target="_blank">IN</a>`,
  `<a href="https://search.douban.com/movie/subject_search?search_text={imdbid}" target="_blank">Douban</a>`,
  `<a href="https://uhdbits.org/torrents.php?searchstr={imdbid}" target="_blank">UHD</a>`,
  `<a href="http://zmk.pw/search?q={search_name}" target="_blank">ZMK</a>`,
  `<a href="https://mediaarea.net/MediaInfoOnline" target="_blank">MediaiInfo</a>`,
  `<a href="https://assrt.net/sub/?searchword={search_name}" target="_blank">SSW</a>`,
  `<a href="https://eiga.moi/torrents?imdb={imdbno}#page/1" target="_blank">ACM</a>`
];

var used_search_list = GM_getValue('used_search_list') === undefined ? default_search_list : JSON.parse(GM_getValue('used_search_list')).split(',');

//常用站点列表，这里只是举例说明，可以替换成自己想要的站点名称即可
const default_common_sites = ['TTG', 'CMCT', 'HUDBT', 'PTer'];
var used_common_sites = GM_getValue('used_common_sites') === undefined ? default_common_sites : JSON.parse(GM_getValue('used_common_sites')).split(',');
//签到站点列表
const default_signin_sites = ['TTG', 'CMCT', 'HUDBT', 'PTer'];
var used_signin_sites = GM_getValue('used_signin_sites') === undefined ? default_common_sites : JSON.parse(GM_getValue('used_signin_sites')).split(',');

//欧美国家列表，可以酌情添加
const us_ue = ['阿尔巴尼亚|安道尔|奥地利|俄罗斯|比利时|波黑|保加利亚|克罗地亚|塞浦路斯|捷克|丹麦|爱沙尼亚|法罗群岛[丹]|冰岛|芬兰|法国|德国|希腊|匈牙利|爱尔兰|意大利|拉脱维亚|列支敦士登|立陶宛|卢森堡|马其顿|马耳他|摩尔多瓦|摩纳哥|荷兰|挪威|波兰|葡萄牙|罗马尼亚|俄罗斯|圣马力诺|塞黑|斯洛伐克|斯洛文尼亚|西班牙|瑞典|瑞士|乌克兰|英国|梵蒂冈|美国|加拿大|澳大利亚|新西兰|西德|苏联|秘鲁|阿根廷|墨西哥'];

const us_ue_english = ['Albania|Andorra|Austria|Russia|Belgium|Bosnia and Herzegovina|Bulgaria|Croatia|Cyprus|Czechia|Denmark|Estonia|Faroe Islands (Denmark)|Iceland|Finland|France|Germany|Greece|Hungary|Ireland|Italy|Latvia|Liechtenstein|Lithuania|Luxembourg|North Macedonia|Malta|Moldova|Monaco|Netherlands|Norway|Poland|Portugal|Romania|Russia|San Marino|Serbia|Slovakia|Slovenia|Spain|Sweden|Switzerland|Ukraine|United Kingdom|Vatican City|United States|Canada|Australia|New Zealand|West Germany|Soviet Union|Peru|Argentina|Mexico'];

//是否在PTP/HDB/HDT/UHD种子列表显示搜索跳转功能，1表示显示，0表示隐藏
const default_show_search_urls = {
  'PTP': 1,
  'HDB': 0,
  'HDT': 0,
  'UHD': 0,
};
var show_search_urls = GM_getValue('show_search_urls') === undefined ? default_show_search_urls : JSON.parse(GM_getValue('show_search_urls'));

function set_host_link() {
  var host_link = prompt(`-------------Auto-feed依托NP架构站进行部分功能布局-------------\n请在输入框输入托管站点的个人设置链接，步骤如下：
    1.进入任意NexusPHP架构PT站点主页;
    2.打开控制面板;
    3.选择个人设定;
    4.复制网页地址输入到下方输入框;
    格式形如：https://(站点域名)/usercp.php?action=personal
    注意：后期可通过>重置托管<按钮进行重置。`, "");
  if (host_link.match(/https?:\/\/.*?\/usercp\.php\?action=personal/)) {
    GM_setValue("host_link", host_link);
    location.reload();
  } else {
    alert('链接格式不对！！');
  }
}

if (GM_getValue("host_link") === undefined && judge_if_the_site_as_source(site_url) !== undefined) {
  set_host_link();
} else {
  host_link = GM_getValue("host_link");
}

if (site_url.match(/^https:\/\/bangumi.tv\/subject/)) {
  var bgm_id = site_url.match(/subject\/(\d+)/)[1];
  $('ul[class="navTabs clearit"]').append(`<li><a href="${host_link}#ptgen?bgmid=${bgm_id}" pcked="1" target="_blank">PtGen</a></li>`);
  return;
}

const default_rehost_img_info = {
  'freeimage': {
    'url': 'https://freeimage.host/page/api',
    'api-url': 'https://freeimage.host/api/1/upload',
    'api-key': ''
  },
  'gifyu': {
    'url': 'https://gifyu.com/',
    'api-url': 'https://gifyu.com/api/1/upload',
    'api-key': ''
  },
  'imgbb': {
    'url': 'https://api.imgbb.com/',
    'api-url': 'https://api.imgbb.com/1/upload',
    'api-key': ''
  }
};

var used_rehost_img_info = GM_getValue('used_rehost_img_info') === undefined ? default_rehost_img_info : JSON.parse(GM_getValue('used_rehost_img_info'));
for (key in default_rehost_img_info) {
  if (!used_rehost_img_info.hasOwnProperty(key)) {
    used_rehost_img_info[key] = default_rehost_img_info[key];
  }
}

/*******************************************************************************************************************
*                                          part 2 常量、变量及函数定义封装层                                          *
********************************************************************************************************************/
