/**
 * @module 04_origin_site_config
 * @description o_site_info dictionary, source site URLs
 * @lines 1341-1550
 * 
 * Extracted from auto_feed.user.js
 * DO NOT EDIT - Auto-generated by split_modules.py
 */

//用于作为源站点但是不是转发站点的字典，大部分都外站，用作判断是否是外站的标准
const o_site_info = {
  'FRDS': 'https://pt.keepfrds.com/',
  'BYR': 'https://byr.pt/',
  'avz': 'https://avistaz.to/',
  'PHD': 'https://privatehd.to/',
  'PTP': 'https://passthepopcorn.me/',
  'HDT': used_site_info.HDT.url,
  'MTV': 'https://www.morethantv.me/',
  'BHD': 'https://beyond-hd.me/',
  'UHD': 'https://uhdbits.org/',
  'BLU': 'https://blutopia.cc/',
  'Aither': 'https://aither.cc/',
  'DarkLand': 'https://darkland.top/',
  'FNP': 'https://fearnopeer.com/',
  'OnlyEncodes': 'https://onlyencodes.cc/',
  'TorrentLeech': 'https://www.torrentleech.org/',
  'xthor': 'https://xthor.tk/',
  'FileList': 'https://filelist.io/',
  'HDF': 'https://hdf.world/',
  'HDB': 'https://hdbits.org/',
  'BTN': used_site_info.BTN.url,
  'RED': 'https://redacted.sh/',
  'OpenCD': 'https://open.cd/',
  'U2': 'https://u2.dmhy.org/',
  'jpop': 'https://jpopsuki.eu/',
  'CG': 'http://cinemageddon.net/',
  'KG': 'https://karagarga.in/',
  'SC': 'https://secret-cinema.pw/',
  'iTS': 'https://shadowthein.net/',
  'HDRoute': 'http://hdroute.org/',
  'HDSpace': 'https://hd-space.org/',
  'ACM': 'https://eiga.moi/',
  'HDOli': 'https://hd-olimpo.club/',
  'Tik': 'https://cinematik.net/',
  'CNZ': 'https://cinemaz.to/',
  'GPW': 'https://greatposterwall.com/',
  'HD-Only': 'https://hd-only.org/',
  'NBL': 'https://nebulance.io/',
  'ANT': 'https://anthelion.me/',
  'IPT': 'https://iptorrents.com/',
  'torrentseeds': 'https://torrentseeds.org/',
  'IN': 'https://nzbs.in/',
  'HOU': 'https://house-of-usenet.com/',
  'OMG': 'https://omgwtfnzbs.org/',
  'digitalcore': 'https://digitalcore.club/',
  'BlueBird': 'https://bluebird-hd.org/',
  'bwtorrents': 'https://bwtorrents.tv/',
  'lztr': 'https://lztr.me/',
  'DICMusic': 'https://dicmusic.com/',
  'OPS': 'https://orpheus.network/',
  'bib': 'https://bibliotik.me/',
  'mam': 'https://www.myanonamouse.net',
  'bit-hdtv': 'https://www.bit-hdtv.com/',
  'TVV': 'http://tv-vault.me/',
  'SugoiMusic': 'https://sugoimusic.me/',
  'Monika': 'https://monikadesign.uk/',
  'DTR': 'https://torrent.desi/',
  'HONE': 'https://hawke.uno/',
  'ZHUQUE': 'https://zhuque.in/',
  'YemaPT': 'https://www.yemapt.org/',
  'SpeedApp': 'https://speedapp.io/',
  'MTeam': used_site_info.MTeam.url,
  'ReelFliX': 'https://reelflix.xyz/',
  'HHClub': 'https://hhanclub.top/',
  'SportsCult': 'https://sportscult.org/'
};

if (tldomain == 0) {
  o_site_info.TorrentLeech = 'https://www.torrentleech.org/';
} else if (tldomain == 1) {
  o_site_info.TorrentLeech = 'https://www.torrentleech.me/';
} else if (tldomain == 2) {
  o_site_info.TorrentLeech = 'https://www.torrentleech.cc/';
} else if (tldomain == 3) {
  o_site_info.TorrentLeech = 'https://www.tlgetin.cc/';
}

if (site_url.match(/^https:\/\/hhan.club\/.*/)) {
  o_site_info.HHClub = 'https://hhan.club/';
  GM_setValue('o_site_info', JSON.stringify(o_site_info));
} else if (site_url.match(/^https:\/\/hhanclub.top\/.*/)) {
  o_site_info.HHClub = 'https://hhanclub.top/';
  GM_setValue('o_site_info', JSON.stringify(o_site_info));
}

//用来拼接发布站点的url和字符串,也可用于识别发布页和源页面
var separator = '#separator#';
//获取源站点简称
const origin_site = find_origin_site(site_url);

const douban_prex = 'https://movie.douban.com/subject/';
const imdb_prex = 'https://www.imdb.com/title/';

//iTS的简介模板，用于获取数据替换后填充
const its_base_content = `
[center]

[img]{poster}[/img]

[url={imdb_url}][img]https://i.ibb.co/KD855ZM/IMDb-Logo-2016.png[/img][/url]  [size=3]{imdb_score}[/size]  [*] [size=3][url={rt_url}][img]https://i.ibb.co/cDSgzxm/rt-logo.png[/img][/url] {rt_score}%[/size]  [*] [url={tmdb_url}][img]https://i.ibb.co/VWMtVnN/0fa9aceda3e5.png[/img][/url] [size=3]{tmdb_score}%[/size]


[color=DarkOrange][size=2]◢ SYNOPSIS ◣[/size][/color]
    {en_descr}


[color=DarkOrange][size=2]◢ TRAILER ◣[/size][/color]
[youtube]{youtube_url}[/youtube]


[color=DarkOrange][size=2]◢ SCREENSHOTS ◣[/size][/color]
{screenshots}

[/center]
`;

const kg_intro_base_content = `[img]{poster}[/img]

Title: {title}
Genres: {genres}
Date Published: {date}
IMDB Rating: {score}
IMDB Link: {imdb_url}
Directors: {director}
Creators: {creator}
Actors: {cast}

Introduction
  {en_descr}

Screenshots here:
{screenshots}

-------------------------------------------------------------------------------------------------------------

Not my rip. Many thanks to the original uploader.

-------------------------------------------------------------------------------------------------------------
`;

const kg_dvd_base_content = `DVD label: {label}
DVD5 / DVD9: {size}
DVD Format: {source}
DVD Audio: Codec {audio}, Channels {channels}
Program(s): Not my rip.
Menus: Untouched
Video: Untouched
Audio: Untouched
DVD extras: Untouched
Extras contain: {extras}
DVD runtime(s): {runtime}
`;

const kg_bluray_base_content = `Blu-Ray label: {label}
BD25 / BD50: {size}
Blu-Ray Audio: Codec {audio}, Channels {channels}
Program(s): Not my rip.
Menus: Untouched
Video: Untouched
Audio: Untouched
DVD extras: Untouched
Extras contain: {extras}
Blu-Ray runtime(s): {runtime}
`;

//tik的简介模板，用于获取数据替换后填充
const tik_base_content = `
[center][img]{poster}[/img]
{screenshots}
[/center]

[b][color=blue]SYNOPSIS:[/color][/b]
{en_descr}

[code]
IMDb...............: [url]http://www.imdb.com/title/{imdbid}/[/url]

Year...............: {year}
Country............: {country}
Runtime............: {runtime} Minutes
Audio..............: {audio}
Subtitles..........: {subtitles}
Video Format.......: {format}
Film Aspect Ratio..: {aspect_ratio}{dvdformat}
Source.............: {source}
Film Distributor...: [url=addlink]To be specified.[/url]
Ripping Program....: Not my rip
Total  Bitrate.....: {bitrate}

Menus......: [x] Untouched
Video......: [x] Untouched
Extras.....: [x] Untouched
Audio......: [x] Untouched
[/code]

[b][color=blue]Extras:[/color][/b]
[*]
[*]
[*]

[b][color=blue]Uploader Comments:[/color][/b]
- All credit goes to the original uploader.
`;

//需要从源网页获取的信息，有些可能没有
var raw_info = {
  //填充类信息
  'name': '', //主标题
  'small_descr': '', //副标题
