/**
 * @module 07_dom_walkers
 * @description walkDOM(), walk_cmct(), walk_ptp(), domToString()
 * @lines 2201-2430
 * 
 * Extracted from auto_feed.user.js
 * DO NOT EDIT - Auto-generated by split_modules.py
 */

  return pic_info;
}

//标签节点连带转换成字符串
function domToString(node) {
  var tmpNode = document.createElement('div');
  tmpNode.appendChild(node);
  var str = tmpNode.innerHTML;
  tmpNode = node = null; // 解除引用，以便于垃圾回收
  return str;
}

//方便进行判断是否是源站点，不然太长了,属于源站点进入逻辑业务层
function judge_if_the_site_as_source() {
  if (site_url.match(/^https:\/\/karagarga.in\/upload\.php.*/)) {
    return 4;
  }
  if (site_url.match(/^https:\/\/(broadcasthe.net|backup.landof.tv)\/upload.php.*/)) {
    return 5;
  }
  if (site_url.match(/^https?:\/\/\d+.\d+.\d+.\d+:5678/)) {
    return 7;
  }
  if (site_url.match(/^https?:\/\/.*\/.*(upload|create|offer|viewoffers).*?(php)?#separator#/i)) {
    return 0;
  }
  if (site_url.match(/^https:\/\/.*open.cd\/plugin_upload.php#separator#/i)) {
    return 0;
  }
  if (site_url.match(/^https:\/\/www.yemapt.org\/#\/torrent\/add\?/i)) {
    return 0;
  }
  if (site_url.match(/^https?:\/\/(avistaz|privatehd|cinemaz).to\/upload\/torrent\/\d+/i)) {
    return 6;
  }
  if (site_url.match(/^https:\/\/hd-space\.org\/index.php\?page=upload/)) {
    return 0;
  }
  if (site_url.match(/^https:\/\/hdcity.city\/upload/)) {
    return 2;
  }
  if (site_url.match(/^https:\/\/(www.)?(darkland.top|eiga.moi|hd-olimpo.club|fearnopeer.com|onlyencodes.cc|blutopia.cc|aither.cc|torrent.desi|monikadesign.uk|hawke.uno|cinematik.net|reelflix.xyz)\/torrents\/\d+$/)) {
    return 1;
  }
  if (site_url.match(/^https:\/\/(www.)?torrentseeds.org\/torrents\/\d+/)) {
    return 1;
  }
  if (site_url.match(/^https:\/\/zhuque.in\/torrent\/(info|list)\/\d+/)) {
    return 1;
  }
  if (site_url.match(/^https:\/\/bibliotik.me\/torrents\/\d+/)) {
    return 1;
  }
  if (site_url.match(/^https:\/\/www.myanonamouse.net\/t\/\d+/)) {
    return 1;
  }
  if (site_url.match(/^https:\/\/speedapp.io\/browse\/\d+\/t/)) {
    return 1;
  }
  if (site_url.match(/^https:\/\/hd-space.org\/index.php\?page=torrent-details/)) {
    return 1;
  }
  if (site_url.match(/^https:\/\/digitalcore.club\/torrent\/\d+/)) {
    return 1;
  }
  if (site_url.match(/^https:\/\/nzbs.in\/releases\/.{36}|^https:\/\/house-of-usenet.*|https:\/\/omgwtfnzbs.org.*/)) {
    return 1;
  }
  if (site_url.match(/^https:\/\/nebulance.io\/torrents.php\?id=\d+/i)) {
    return 1;
  }
  if (site_url.match(/^https:\/\/star-space.net\/p_torrent\/video_detail.php\?tid=\d+/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/.*\/.*details.*php.*/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/sportscult.org\/.*torrent-details/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/.*\/.*detail\/\d+/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/totheglory.im\/t\/.*/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/(passthepopcorn.me|tv-vault.me|broadcasthe.net|backup.landof.tv|greatposterwall.com|sugoimusic.me).*torrentid.*/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/iptorrents.com\/torrent.php\?id=*/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/anthelion.me.*torrentid.*/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/secret-cinema.pw.*torrentid.*/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/www.morethantv.me.*torrentid.*/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/hd-only.org.*torrentid.*/i)) {
    return 1;
  }
  if (site_url.match(/^https:\/\/hdbits\.org\/details\.php\?id=.*/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/(privatehd|cinemaz|avistaz).to\/torrent/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/www.morethan.tv\/torrents.php\?id/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/beyond-hd.me\/torrents/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/uhdbits.org\/torrents.php\?id=\d+&torrentid=\d+/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/hdf.world\/torrents.php\?id=\d+&torrentid=\d+/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/jpopsuki.eu\/torrents.php\?id=\d+&torrentid=\d+/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/(redacted.sh|lztr.me|dicmusic.com|orpheus.network)\/torrents.php\?id=\d+&torrentid=\d+/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/www\.(torrentleech|tlgetin)\..*?\/torrent\/*/i)) {
    return 1;
  }
  if (site_url.match(/^http(s*):\/\/xthor.tk\/details.php/i)) {
    return 1;
  }
}

//判断是否是国内的站点，国内站点架构基本一致且不需要额外获取豆瓣信息
function judge_if_the_site_in_domestic() {
  var domain, reg, key;
  for (key in o_site_info) {
    if (key != 'FRDS' && key != 'BYR' && key != 'U2') {
      domain = o_site_info[key].split('//')[1].replace('/', '');
      reg = new RegExp(domain, 'i');
      if (site_url.split('#separator#')[0].match(reg) || site_url.match(/https:\/\/www.yemapt.org\/#\/torrent\/add\?/)) {
        return 0;
      }
    }
  }
  return 1;
}

//处理标题业务封装进函数
function deal_with_title(title) {
  title = title.replace(/\./g, ' ').replace(/torrent$/g, '').trim() + ' ';
  if (title.match(/[^\d](2 0|5 1|7 1|1 0|6 1|2 1|4 0|5 0)[^\d]/)) {
    title = title.replace(/[^\d](2 0|5 1|7 1|1 0|6 1|2 1|4 0|5 0)[^\d]/g, function (data) {
      return data.slice(0, 2) + '.' + data.slice(3, data.length);
    }).trim();
  }
  title = title.replace(/H ?(26[45])/i, "H.$1").replace(/x265[.-]10bit/i, 'x265 10bit');
  title = title.replace(/\s+\[2?x?(免费|free)\].*$|\(限时.*\)|\(限時.*\)|\(已审|通过|待定\)/ig, '').replace(/\[.*?\]/ig, '').replace(/剩余时间.*/i, '');
  title = title.replace(/\(|\)/ig, '').replace(/ - /g, function (data, index) {
    try {
      let y_index = title.match(/(19|20)\d+/).index;
      if (index > y_index) {
        return '-';
      } else {
        return data;
      }
    } catch (err) {
      return data;
    }
  });
  title = title.replace('_10_', '(_10_)');
  title = title.replace('V2.1080p', 'V2 1080p').replace(/mkv$|mp4$/i, '').trim();
  return title;
}

//处理副标题逻辑业务封装进函数
function deal_with_subtitle(subtitle) {
  subtitle = subtitle.replace(/\[checked by.*?\]/i, '').replace(/autoup/i, '').replace(/ +/, ' ').trim();
  return subtitle;
}

//字典转成字符串传达到跳转页面
function dictToString(my_dict) {
  my_dict = fill_raw_info(my_dict, null);
  var tmp_string = '', link_str = '#linkstr#', key;
  for (key in my_dict) {
    tmp_string += key + link_str + my_dict[key] + link_str;
  }
  tmp_string = tmp_string.slice(0, tmp_string.length - 9);
  return btoa(encodeURIComponent(tmp_string));
}

//字符串转换成字典回来填充发布页面
function stringToDict(my_string) {
  my_string = decodeURIComponent(atob(my_string));
  var link_str = '#linkstr#';
  var tmp_array = my_string.split(link_str);
  var tmp_dict = {};
  for (i = 0; i < tmp_array.length; i++) {
    if (i % 2 == 0) {
      tmp_dict[tmp_array[i]] = tmp_array[i + 1];
    }
  }
  return tmp_dict;
}

//下面两个函数用来为字符串赋予format方法：例如——'thank you {site}'.format({'site':'ttg'}) => 'thank you ttg'
String.prototype.replaceAll = function (exp, newStr) {
  return this.replace(new RegExp(exp, "gm"), newStr);
};

String.prototype.format = function (args) {
  var result = this;
  if (arguments.length < 1) {
    return result;
  }
  var data = arguments;
  if (arguments.length == 1 && typeof (args) == "object") {
    data = args;
  }
  for (var key in data) {
    var value = data[key];
    if (undefined != value) {
      result = result.replaceAll("\\{" + key + "\\}", value);
    }
  }
  return result;
