/**
 * @module 09_data_processing
 * @description fill_raw_info(), get_mediainfo_picture_from_descr()
 * @lines 2701-3600
 * 
 * Extracted from auto_feed.user.js
 * DO NOT EDIT - Auto-generated by split_modules.py
 */

function judge_forward_site_in_domestic(site) {
  if (Object.keys(o_site_info).indexOf(site) < 0 && site != "HDSpace") {
    return true;
  } else {
    return false;
  }
}

//从简介和名称获取副标题
function get_small_descr_from_descr(descr, name) {
  var small_descr = '', videoname = '', sub_str = '', type_str = '';
  if (descr.match(/译.{0,5}名[^\r\n]+/)) {
    videoname = descr.match(/译.*?名([^\r\n]+)/)[1];
    if (!/.*[\u4e00-\u9fa5]+.*/.test(videoname) || videoname.trim() == '') {
      try { videoname = descr.match(/片.*?名([^\r\n]+)/)[1]; } catch (err) { }
    }
    videoname = videoname.trim(); //去除首尾空格
    if (name.match(/S\d{2}E\d{2}/i)) { //电视剧单集
      sub_str = name.match(/S(\d{2})E(\d{2})/i);
      sub_str = ' *第' + numToChinese(parseInt(sub_str[1])) + '季 第' + parseInt(sub_str[2]) + '集*';
    } else if (name.match(/S\d{2}/)) {
      sub_str = name.match(/S(\d{2})/i);
      sub_str = ' *第' + numToChinese(parseInt(sub_str[1])) + '季';
      if (descr.match(/◎集.{1,10}数.*?(\d+)/)) {
        sub_str += ' 全' + parseInt(descr.match(/◎集.{1,10}数.*?(\d+)/)[1]) + '集*'
      } else {
        sub_str += '*';
      }
    }
    small_descr = videoname + sub_str;
  } if (descr.match(/类.{0,5}别[^\r\n]+/)) {
    type_str = descr.match(/类.*别([^\r\n]+)/)[1];
    type_str = type_str.trim(); //去除首尾空格
    type_str = type_str.replace(/\//g, ''); //去除/
    small_descr = small_descr + ' | 类别：' + type_str;
  }
  return small_descr.trim();
}

//根据简介获取来源，也就是地区国家产地之类的——尤其分类是日韩或者港台的，有的站点需要明确一下
function get_source_sel_from_descr(descr) {
  var region = '';
  var reg_region = descr.match(/◎(地.{0,10}?区|国.{0,10}?家|产.{0,10}?地|◎產.{0,5}?地)([^\r\n]+)/);
  if (!reg_region) {
    reg_region = descr.match(/(地.{0,10}?区|国.{0,10}?家|产.{0,10}?地|◎產.{0,5}?地)([^\r\n]+)/);
  }
  if (reg_region) {
    region = reg_region[2].split('/')[0].trim();
    reg_region = RegExp(us_ue, 'i');
    if (region.match(/香港/)) {
      region = '香港';
    } else if (region.match(/台湾|臺灣/)) {
      region = '台湾';
    } else if (region.match(/日本/)) {
      region = '日本';
    } else if (region.match(/韩国/)) {
      region = '韩国';
    } else if (region.match(/印度/) && !region.match(/印度尼西亚/)) {
      region = '印度';
    } else if (region.match(/中国|大陆/)) {
      region = '大陆';
    } else if (region.match(reg_region)) {
      region = '欧美';
    } else {
      region = region;
    }
  } else {
    reg_region = descr.match(/Country: (.*)/);
    if (reg_region) {
      region = reg_region[1].trim();
      reg_region = RegExp(us_ue_english, 'i');
      if (region.match(reg_region)) {
        region = '欧美'
      }
    }
  }
  return region;
}

//为获取豆瓣信息提供链接简化 promise
function create_site_url_for_douban_info(raw_info, is_douban_search_needed) {
  if (imdb2db_chosen == 0) {
    var p = new Promise(function (resolve, reject) {
      if (is_douban_search_needed) {
        url = raw_info.url.match(/tt\d+/)[0];
        req = 'https://movie.douban.com/j/subject_suggest?q={url}'.format({ 'url': url });
        GM_xmlhttpRequest({
          method: 'GET',
          url: req,
          onload: function (res) {
            var response = JSON.parse(res.responseText);
            if (response.length > 0) {
              raw_info.dburl = douban_prex + response[0].id;
              resolve(raw_info);
            } else {
              reject();
            }
          }
        });
      } else {
        resolve(raw_info);
      }
    });
  }
  else {
    var p = new Promise(function (resolve, reject) {
      if (is_douban_search_needed) {
        url = raw_info.url.match(/tt\d+/)[0];
        var search_url = 'https://m.douban.com/search/?query=' + url + '&type=movie';
        getDoc(search_url, null, function (doc) {
          if ($('ul.search_results_subjects', doc).length) {
            var douban_url = 'https://movie.douban.com/subject/' + $('ul.search_results_subjects', doc).find('a').attr('href').match(/subject\/(\d+)/)[1];
            if (douban_url.search('35580200') > -1) {
              reject();
            }
            raw_info.dburl = douban_url;
            resolve(raw_info);
          } else {
            reject();
          }
        });
      } else {
        resolve(raw_info);
      }
    });
  }
  return p;
}

//颜色转换rgb转16进制
function rgb_2_hex(data) {
  if (data.match(/rgb\((.*)\)/)) {
    data = data.match(/rgb\((.*)\)/)[1];
    data = data.split(',');
    color = '#';
    for (iii = 0; iii < data.length; iii++) {
      var color_tmp = parseInt(data[iii]).toString(16);
      if (color_tmp.length < 2) {
        color_tmp = '0' + color_tmp;
      }
      color += color_tmp;
    }
    return color;
  } else {
    return data;
  }
}

//判断是否是原盘
function check_descr(descr) {
  flag = false;
  if (descr.match(/mpls/i)) {
    flag = true;
  }
  return flag;
}

function get_full_size_picture_urls(raw_info, imgs, container, need_img_label, callback, remove_img) {
  var img_urls = null;
  if (raw_info !== null) {
    img_urls = raw_info.descr.match(/(\[url=.*?\])?\[img\].*?\[\/img\](\[\/url\])?/ig);
  } else if (imgs) {
    img_urls = imgs.match(/(\[url=.*?\])?\[img\].*?\[\/img\](\[\/url\])?/ig);
  }
  var img_info = '';
  try {
    try {
      var _index = raw_info.descr.indexOf("◎");
    } catch (err) {
      _index = -1;
    }
    for (i = 0; i < img_urls.length; i++) {
      if (raw_info && raw_info.descr.indexOf(img_urls[i]) < 80 || (_index > 0 && raw_info.descr.indexOf(img_urls[i]) < _index)) {
        img_urls[i] = '';
        continue;
      }
      if (raw_info) {
        raw_info.descr = raw_info.descr.replace(img_urls[i], '');
      }
      var item = img_urls[i].match(/\[img\](.*?)\[\/img\]/)[1];
      if (img_urls[i].match(/\[url=(https:\/\/i.ibb.co\/.*?\.png)\]/)) {
        item = img_urls[i].match(/\[url=(https:\/\/i.ibb.co\/.*?\.png)\]/)[1];
      }
      if (item.match(/imgbox/)) {
        item = item.replace('thumbs2', 'images2').replace('t.png', 'o.png');
      } else if (item.match(/pixhost/)) {
        item = item.replace('//t', '//img').replace('thumbs', 'images');
      } else if (item.match(/shewang.net|pterclub.net|img4k.net|img.hdhome.org|img.hdchina.org/)) {
        item = item.replace(/th.png/, 'png').replace(/md.png/, 'png');
      } else if (item.match(/beyondhd.co\/(images|cache)/)) {
        item = item.replace(/th.png/, 'png').replace(/md.png/, 'png').replace('/t/', '/i/');
      } else if (item.match(/tu.totheglory.im/)) {
        item = item.replace(/_thumb.png/, '.png');
      }
      if (need_img_label) {
        img_info += '\n' + `[img]${item}[/img]`;
      } else {
        img_info += '\n' + item;
      }
    }
    container.val(img_info.trim());
    if (callback) {
      callback(img_info);
    }
    if (remove_img) {
      remove_img(img_urls);
    }
  } catch (err) { }
}

if (site_url.match(/https:\/\/(springsunday.net|www.hddolby.com|ptlgs.org)\/upload.php/)) {
  $('#url_vimages').after(`<a href="" id="get_full_size" style="color: red" title="点击获取原图,目前支持imgbox，pixhost，pter，ttg，瓷器，img4k">获取原图</a>`);
  $('textarea[name="screenshots"]').after(`<br><a href="" id="get_full_size" style="color: red" title="点击获取原图,目前支持imgbox，pixhost，pter，ttg，瓷器，img4k">获取原图</a>`);
  $('#get_full_size').click(function (e) {
    e.preventDefault();
    get_full_size_picture_urls(null, $('#url_vimages').val(), $('#url_vimages'), false);
    get_full_size_picture_urls(null, $('textarea[name="screenshots"]').val(), $('textarea[name="screenshots"]'), false);
  });
}

function get_bluray_name_from_descr(descr, name) {
  var temp_title = "";
  //分辨率
  if (descr.match(/(2160)(P|I)/i)) {
    temp_title = temp_title + "2160p.Blu-ray ";
  } else if (descr.match(/(1080)(P)/i)) {
    temp_title = temp_title + "1080p.Blu-ray.";
  } else if (descr.match(/(1080)(i)/i)) {
    temp_title = temp_title + "1080i.Blu-ray.";
  }

  if (descr.match(/Ultra HD|UHD/i)) {
    temp_title = "UHD ";
  }

  //视频编码
  if (descr.match(/(AVC Video)/i)) {
    temp_title = temp_title + "AVC.";
  } else if (descr.match(/(HEVC)/i)) {
    temp_title = temp_title + "HEVC.";
  } else if (descr.match(/MPEG-2 Video/i)) {
    temp_title = temp_title + "MPEG-2.";
  }

  //音频编码
  if (descr.match(/DTS:X[\s\S]{0,200}?7.1/i)) {
    temp_title = temp_title + "DTS-HD.MA.7.1";
  } else if (descr.match(/TrueHD[\s\S]{0,200}?(7\.1|5\.1|2\.0|1\.0)/i)) {
    temp_title = temp_title + "TrueHD." + descr.match(/TrueHD[\s\S]{0,200}?(7\.1|5\.1|2\.0|1\.0)/i)[1];
  } else if (descr.match(/DTS-HD[\s\S]{0,200}?(7\.1|5\.1|2\.0|1\.0)/i)) {
    temp_title = temp_title + "DTS-HD.MA." + descr.match(/DTS-HD[\s\S]{0,200}?(7\.1|5\.1|2\.0|1\.0)/i)[1];
  } else if (descr.match(/LPCM[\s\S]{0,200}?(7\.1|5\.1|2\.0|1\.0)/i)) {
    temp_title = temp_title + "LPCM." + descr.match(/LPCM[\s\S]{0,200}?(7\.1|5\.1|2\.0|1\.0)/i)[1];
  } else if (descr.match(/Dolby Digital[\s\S]{0,200}?(7\.1|5\.1|2\.0|1\.0)/i)) {
    temp_title = temp_title + "DD." + descr.match(/Dolby Digital[\s\S]{0,200}?(7\.1|5\.1|2\.0|1\.0)/i)[1];
  }

  if (raw_info.name.match(/Blu-ray|DTS-HD|TrueHD|LPCM|HEVC|Bluray/)) {
    name = raw_info.name;
  } else if (name.match(/BLURAY|UHD.BLURAY/)) {
    name = name.replace(/MULTi.|DUAL.|SWEDiSH|DOCU/i, "");
    name = name.replace(/GERMAN/i, "GER");
    name = name.replace(/REMASTERED/i, "Remastered");
    name = name.replace(/UNCUT/i, "Uncut");
    name = name.replace(/COMPLETE[\s\S]{0,20}BLURAY/, temp_title);
  } else {
    name = name + '.' + temp_title + "-NoGroup";
  }
  return name;
}

const skip_img = [
  '[img]https://pic.imgdb.cn/item/6170004c2ab3f51d91c77825.png[/img]',
  '[img]https://pic.imgdb.cn/item/6170004c2ab3f51d91c7782a.png[/img]',
  '[img]https://images2.imgbox.com/04/6b/Ggp5ReQb_o.png[/img]',
  '[img]https://www.z4a.net/images/2019/09/13/info.png[/img]',
  '[img]https://www.z4a.net/images/2019/09/13/screens.png[/img]',
  '[img]https://i.loli.net/2019/03/28/5c9cb8f8216d7.png[/img]',
  '[img]https://hdsky.me/attachments/201410/20141003100205b81803ac0903724ad88de90649c5a36e.jpg[/img]',
  '[img]https://hdsky.me/adv/hds_logo.png[/img]',
  '[img]https://iili.io/XF9HEQ.png[/img]',
  '[img]https://img.pterclub.net/images/2022/03/24/58ef34eb1c04aa6f87442e439d103b29.png[/img]',
  '[img]https://img.pterclub.net/images/2021/07/14/78c58ee6b3e092d0c5a7fa02f3a1905e.png[/img]',
  '[img]https://pterclub.net/pic/CS.png[/img]',
  '[img]https://pterclub.net/pic/GDJT.png[/img]',
  '[img]http://img.pterclub.net/images/CS.png[/img]',
  '[img]https://img.pterclub.net/images/GDJT.png[/img]',
  '[img]https://kp.m-team.cc/logo.png[/img]',
  '[img]http://tpimg.ccache.org/images/2015/03/08/c736743e65f95c4b68a8acd3f3e2d599.png[/img]',
  '[img]https://ourbits.club/pic/Ourbits_info.png[/img]',
  '[img]https://ourbits.club/pic/Ourbits_MoreScreens.png[/img]',
  '[img]https://images2.imgbox.com/ce/e7/KCmGFMOB_o.png[/img]',
  '[img]https://img.m-team.cc/images/2016/12/05/d3be0d6f0cf8738edfa3b8074744c8e8.png[/img]',
  '[img]https://pic.imgdb.cn/item/6170004c2ab3f51d91c77825.png[/img]',
  '[img]https://pic.imgdb.cn/item/6170004c2ab3f51d91c7782a.png[/img]',
  '[img]https://img.pterclub.net/images/CS.png[/img]',
  '[img]https://img.pterclub.net/images/2022/10/19/1.gif[/img]',
  '[img]https://img93.pixhost.to/images/86/435614074_c5134549f13c2c087d67c9fa4089c49e-removebg-preview.png[/img]'
];

//从简介拆分出来mediainfo和截图
function get_mediainfo_picture_from_descr(descr) {
  var info = { 'mediainfo': '', 'pic_info': '', 'multi_mediainfos': '' };
  var img_info = '';
  var mediainfo = '';
  var img_urls = descr.match(/(\[url=.*?\])?\[img\].*?\[\/img\](\[\/url\])?/ig);
  var index_of_info = 0;
  if (descr.match(/◎译.{2,10}名|◎片.{2,10}名|片.{2,10}名/)) {
    index_of_info = descr.match(/◎译.{2,10}名|◎片.{2,10}名|片.{2,10}名/).index;
  }
  try {
    for (i = 0; i < img_urls.length; i++) {
      if (descr.indexOf(img_urls[i]) < 10 || descr.indexOf(img_urls[i]) < index_of_info) {
        info.cover_img = img_urls[i];
      } else {
        descr = descr.replace(img_urls[i], '');
        img_info += img_urls[i].match(/(\[url=.*?\])?\[img\].*?\[\/img\](\[\/url\])?/)[0];
      }
    }
  } catch (err) { img_info = ''; }
  descr = descr + '\n\n' + img_info;

  try {
    //获取mediainfo,这里可以扩展匹配不同情形
    if (descr.match(/DISC INFO:|.MPLS|Video Codec|Disc Label/i) && (raw_info.medium_sel == 'UHD' || raw_info.medium_sel == 'BluRay')) {
      mediainfo = descr.match(/\[quote.*?\][\s\S]*?(DISC INFO|.MPLS|Video Codec|Disc Label)[\s\S]*?\[\/quote\]/i)[0];
    } else if (descr.match(/General|RELEASE.NAME|RELEASE DATE|Unique ID|RESOLUTiON|Bitrate|帧　率|音频码率|视频码率/i)) {
      mediainfo = descr.match(/\[quote.*?\][\s\S]*?(General|RELEASE.NAME|RELEASE DATE|Unique ID|RESOLUTiON|Bitrate|帧　率|音频码率|视频码率)[\s\S]*?\[\/quote\]/ig);
      mediainfo = mediainfo.join('\n\n');
      if (mediainfo.match(/\.VOB|\.IFO/i)) {
        info.multi_mediainfos = mediainfo.replace(/\[\/?quote\]/g, '');
      }
    }
  } catch (err) {
    if (descr.match(/\n.*DISC INFO:[\s\S]*kbps.*/)) {
      mediainfo = descr.match(/\n.*DISC INFO:[\s\S]*kbps.*/)[0].trim();
    }
  }

  mediainfo = mediainfo.replace(/\[quote.*?\]/ig, '[quote]');
  while (mediainfo.match(/\[quote\]/i)) {
    mediainfo = mediainfo.slice(mediainfo.search(/\[quote\]/) + 7);
  }
  mediainfo = mediainfo.replace(/\[\/quote\]/i, '');
  mediainfo = mediainfo.replace(/\[\/?(font|size|quote|color).{0,80}?\]/ig, '');
  //获取图片
  var imgs = descr.split(/\[\/quote\]/).pop();
  imgs = imgs.match(/(\[url=.*?\])?\[img\].*?\[\/img\](\[\/url\])?/g);
  try {
    if (imgs) {
      imgs = imgs.filter((item) => {
        if (skip_img.indexOf(item) < 0 && !item.match(/m.media-amazon.com\/images/)) {
          return item;
        }
      }).join(' ');
    } else {
      imgs = '';
    }
  } catch (err) {
    imgs = '';
  }
  info.mediainfo = mediainfo.trim();
  info.pic_info = imgs.trim();
  return info;
}
function fill_raw_info(raw_info, forward_site) {
  raw_info.descr = raw_info.descr.replace(/%3A/g, ':').replace(/%2F/g, "/");
  raw_info.descr = raw_info.descr.replace('[quote][/quote]', '').replace('[b][/b]', '').replace(/\n\n+/, '\n\n');
  raw_info.descr = raw_info.descr.replace('https://pic.imgdb.cn/item/6170004c2ab3f51d91c77825.png', 'https://img93.pixhost.to/images/86/435614074_c5134549f13c2c087d67c9fa4089c49e-removebg-preview.png');
  raw_info.descr = raw_info.descr.replace(/引用.{0,5}\n/g, '');
  raw_info.descr = raw_info.descr.replace(/.*ARDTU.*/g, '');
  //标题肯定都有，副标题可能没有，从简介获取
  if (raw_info.small_descr == '') {
    raw_info.small_descr = get_small_descr_from_descr(raw_info.descr, raw_info.name);
  }

  if (raw_info.type == '电影') {
    if (raw_info.descr.match(/类[\s\S]{0,5}别[\s\S]{0,30}纪录片/i)) {
      raw_info.type = '纪录';
    }
    if (raw_info.descr.match(/类[\s\S]{0,5}别[\s\S]{0,30}动画/i)) {
      raw_info.type = '动漫';
    }
  }

  if (forward_site == 'LaJiDui') {
    raw_info.descr += `\n\n[quote]转载种子来源：${raw_info.origin_url.replace('***', '/')}[/quote]`;
  }

  //补充豆瓣和imdb链接
  if (raw_info.url == '') {
    var url = raw_info.descr.match(/http(s*):\/\/www.imdb.com\/title\/tt(\d+)/i);
    if (url) {
      raw_info.url = url[0] + '/';
    }
  }
  if (raw_info.dburl == '') {
    var dburl = raw_info.descr.match(/http(s*):\/\/.*?douban.com\/subject\/(\d+)/i);
    if (dburl) {
      raw_info.dburl = dburl[0] + '/';
    }
  }

  raw_info.tracklist = raw_info.tracklist.replace(/\t/g, '');

  raw_info.url = raw_info.url.split('?').pop();
  //没有来源或者指向不明
  if (raw_info.source_sel == '' || raw_info.source_sel.match(/(港台|日韩)/)) {
    var region = get_source_sel_from_descr(raw_info.descr);
    if (raw_info.source_sel.match(/(港台|日韩)/)) {
      if (raw_info.source_sel == '港台') {
        if (region == '台湾') {
          raw_info.source_sel = '台湾';
        } else {
          raw_info.source_sel = '香港';
        }
      } else if (raw_info.source_sel == '日韩') {
        if (region == '日本') {
          raw_info.source_sel = '日本';
        } else {
          raw_info.source_sel = '韩国';
        }
      }
    }
    if (region != '' && raw_info.source_sel == '') {
      raw_info.source_sel = region;
    }
  }

  //如果没有媒介, 从标题获取
  if (raw_info.medium_sel == '') {
    raw_info.medium_sel = raw_info.name.medium_sel();
    if (!raw_info.medium_sel && raw_info.descr.match(/mpls/i)) {
      raw_info.medium_sel = 'Blu-ray';
    }
    if (raw_info.type == '音乐' && raw_info.music_media) {
      raw_info.medium_sel = raw_info.music_media;
    }
  }
  if (raw_info.medium_sel == 'Blu-ray' && (raw_info.name.match(/UHD|2160P/i) || raw_info.descr.match(/2160p/))) {
    raw_info.medium_sel = 'UHD';
  }

  //如果没有编码信息
  if (raw_info.codec_sel == '') {
    raw_info.codec_sel = raw_info.name.codec_sel();
  }

  //没有音频编码, 从标题获取，最后从简介获取
  if (raw_info.audiocodec_sel == '') {
    raw_info.audiocodec_sel = raw_info.name.audiocodec_sel();
    if (raw_info.audiocodec_sel == '') {
      raw_info.audiocodec_sel = raw_info.descr.audiocodec_sel();
    }
  }

  //没有分辨率
  if (raw_info.standard_sel == '') {
    raw_info.standard_sel = raw_info.name.standard_sel();
  }

  if (raw_info.standard_sel == '') {
    try {
      var height = raw_info.descr.match(/Height.*?:(.*?)pixels/i)[1].trim();
      if (height == '480' || height == '576') {
        raw_info.standard_sel = 'SD';
      } else if (height == '720') {
        raw_info.standard_sel = '720p';
      } else if (height == '1 080') {
        raw_info.standard_sel = '1080p';
        if (raw_info.descr.match(/Scan.*?type.*?(Interleaved|Interlaced)/i)) {
          raw_info.standard_sel = '1080i';
        }
      } else if (height == '2 160') {
        raw_info.standard_sel = '4K';
      }
    } catch (err) {
      if (raw_info.descr.match(/(1080|2160)p/)) {
        raw_info.standard_sel = raw_info.descr.match(/(1080|2160)p/)[0].replace('2160p', '4K');
      }
    }
  }

  if (raw_info.standard_sel == '1080p') {
    if (raw_info.name.standard_sel() == '1080i') {
      raw_info.standard_sel = '1080i';
    } else {
      try {
        var mi = get_mediainfo_picture_from_descr(raw_info.descr).mediainfo;
        if (mi.match(/1080i|Scan.*?type.*?(Interleaved|Interlaced)/)) {
          raw_info.standard_sel = '1080i';
        }
      } catch (err) { }
    }
  }

  if (raw_info.name.match(/Remux/i)) {
    raw_info.medium_sel = 'Remux';
  }

  if (raw_info.name.match(/webrip/i)) {
    raw_info.medium_sel = 'WEB-DL';
  }
  if (raw_info.edition_info.medium_sel()) {
    if (raw_info.edition_info.medium_sel() != 'Blu-ray' || raw_info.descr.match(/mpls/i)) {
      raw_info.medium_sel = raw_info.edition_info.medium_sel();
    } else if (raw_info.edition_info.medium_sel() == 'Blu-ray' && raw_info.edition_info.match(/mkv/i)) {
      raw_info.medium_sel = 'Encode';
    }
  }

  if (raw_info.codec_sel == 'H265' && raw_info.name.match(/x265/i)) {
    raw_info.codec_sel = 'X265';
  }

  if (raw_info.audiocodec_sel == 'TrueHD') {
    if (raw_info.descr.match(/Atmos/)) {
      raw_info.audiocodec_sel = 'Atmos';
    }
  }

  raw_info.descr = raw_info.descr.replace(/\n\n+/g, '\n\n').replace('https://dbimg.audiences.me/?', '').replace('https://imgproxy.pterclub.net/douban/?t=', '');
  raw_info.descr = raw_info.descr.replace('https://imgproxy.tju.pt/?url=', '');

  if (raw_info.edition_info.codec_sel()) {
    raw_info.codec_sel = raw_info.edition_info.codec_sel();
  }
  if (!raw_info.codec_sel || forward_site == 'PTer') {
    if (raw_info.descr.match(/Writing library.*(x264|x265)/)) {
      raw_info.codec_sel = raw_info.descr.match(/Writing library.*(x264|x265)/)[1].toUpperCase();
      if (raw_info.name.match(/H.?26[45]/)) {
        raw_info.name = raw_info.name.replace(/H.?26[45]/i, raw_info.codec_sel.toLowerCase())
      }
    } else if (raw_info.descr.match(/Video[\s\S]*?Format.*?HEVC/i)) {
      raw_info.codec_sel = 'H265';
    } else if (raw_info.descr.match(/Video[\s\S]*?Format.*?AVC/i)) {
      raw_info.codec_sel = 'H264';
    } else if (raw_info.descr.match(/XviD/i)) {
      raw_info.codec_sel = 'XVID';
    } else if (raw_info.descr.match(/DivX/i)) {
      raw_info.codec_sel = 'DIVX';
    } else if (raw_info.descr.match(/Video[\s\S]*?Format.*?MPEG Video[\s\S]{1,10}Format Version.*?Version 4/i)) {
      raw_info.codec_sel = 'MPEG-4';
    } else if (raw_info.descr.match(/Video[\s\S]*?Format.*?MPEG Video[\s\S]{1,10}Format Version.*?Version 2/i)) {
      raw_info.codec_sel = 'MPEG-2';
    }
  }
  if (raw_info.descr.match(/Writing library.*(x264|x265)/)) {
    raw_info.codec_sel = raw_info.descr.match(/Writing library.*(x264|x265)/)[1].toUpperCase();
  }

  if (raw_info.name.match(/dvdrip/i)) {
    raw_info.medium_sel = 'DVD';
  }
  if (raw_info.origin_site == 'OurBits') {
    raw_info.descr = raw_info.descr.replace(/\[quote\]\n/g, '[quote]')
  }
  try {
    if (raw_info.descr.match(/\[quote\].*?官组作品.*?\n?\[\/quote\]/g).length >= 2) {
      raw_info.descr = raw_info.descr.split(/\[quote\].*?官组作品.*?\n?\[\/quote\]/g).pop();
      raw_info.descr = add_thanks(raw_info.descr);
    }
  } catch (err) { }
  raw_info.descr = raw_info.descr.trim();
  return raw_info;
}

//PTHome、HDHome、杜比标签勾选
function check_label(nodes, value) {
  for (i = 0; i < nodes.length; i++) {
    if (nodes[i].value == value) {
      nodes[i].checked = true;
      break;
    }
  }
}

function init_buttons_for_transfer(container, site, mode, raw_info) {
  //imdb框
  var input_box = document.createElement('input');
  input_box.type = "text";
  input_box.className = "input";
  input_box.id = "input_box";
  input_box.value = raw_info.url;
  if (!raw_info.url && raw_info.dburl) {
    input_box.value = raw_info.dburl;
  }

  if (site == 'PTP') {
    input_box.style.width = '320px';
  } else if (site == 'PHD' || site == 'avz' || site == 'BHD' || site == 'CNZ') {
    input_box.style.width = '270px';
  } else {
    input_box.style.width = '280px';
  }
  if (site == 'TorrentLeech') {
    input_box.style.border = '1px solid green';
  }
  container.appendChild(input_box);

  var search_button = document.createElement("input");
  search_button.type = "button";
  search_button.style.marginLeft = '12px';
  search_button.style.marginRight = '4px';
  search_button.value = "检索名称";
  search_button.id = 'search_button';
  container.appendChild(search_button);

  var checkBox = document.createElement("input");
  checkBox.setAttribute("type", "checkbox");
  checkBox.setAttribute("id", 'douban_api');
  var douban_text = document.createTextNode('API');
  container.append(checkBox);
  container.append(douban_text);

  var ptgen_button = document.createElement("input");
  ptgen_button.type = "button";
  ptgen_button.style.marginLeft = '12px';
  ptgen_button.value = "ptgen跳转";
  ptgen_button.id = 'ptgen_button';
  container.appendChild(ptgen_button);

  var douban_button = document.createElement("input");
  douban_button.type = "button";
  douban_button.value = "点击获取";
  douban_button.id = 'douban_button';
  douban_button.style.marginLeft = '12px';
  container.appendChild(douban_button);

  if (site == 'ZHUQUE') {
    var brDiv = document.createElement('br');
    container.appendChild(brDiv);
  }

  if (['PHD', 'avz', 'CNZ', 'FileList', 'TTG', 'PTP'].indexOf(site) > -1) {
    var download_button = document.createElement('input');

    var select_img = document.createElement("input");
    select_img.setAttribute("type", "checkbox");
    select_img.setAttribute("id", 'select_img');
    container.append(select_img);
    select_img.style.marginLeft = '8px';
    select_img.style.marginRight = '-1px';
    select_img.checked = true;

    select_img.addEventListener('click', function (e) {
      if (e.target.checked) {
        location.reload();
      } else {
        $('span.imgCheckbox0').map((_, e) => {
          $(e).replaceWith(e.innerHTML)
        });
      }
    }, false);

    download_button.type = "button";
    download_button.id = 'download_pngs';
    download_button.value = '转存截图';
    download_button.style.marginLeft = '0px';
    download_button.style.paddingLeft = '2px';
    download_button.onclick = function () {
      if (textarea.value.match(/ilikeshots/)) {
        raw_info.images = textarea.value.match(/https?:\/\/yes\.ilikeshots\.club\/images\/.*?png/g);
      }
      if (raw_info.images.length > 0) {
        download_button.value = '处理中…';
        if (raw_info.images[0].match(/ilikeshots/) && !raw_info.images[0].match(/.png|.jpg/)) {
          raw_info.images.map((e) => {
            getDoc(e, null, function (doc) {
              textarea.value += $('#image-viewer-container', doc).find('img').attr('src').replace(/\.md/, '') + '\n';
            })
          });
        }
        pix_send_images(raw_info.images)
          .then(function (new_urls) {
            new_urls = new_urls.toString().split(',');
            var urls_append = '';
            if (new_urls.length > 1) {
              for (var i = 0; i <= new_urls.length - 2; i += 2) {
                urls_append += `${new_urls[i]} ${new_urls[i + 1]}\n`
              }
              if (new_urls.length % 2 == 1) {
                urls_append += new_urls[new_urls.length - 1] + '\n';
              }
            } else {
              urls_append = new_urls;
            }
            $('#textarea').val($('#textarea').val() + '\n' + urls_append);
            if (site == 'PTP') {
              raw_info.descr = raw_info.descr.replace(/\[img\].*?(ptpimg|pixhost).*?\[\/img\]/g, '');
            }
            raw_info.descr = raw_info.descr + '\n' + urls_append;
            set_jump_href(raw_info, 1);
            download_button.value = '处理成功';
            download_button.disable = true;
          })
          .catch(function (message) {
            alert(message);
            download_button.disable = true;
            download_button.value = '转存失败';
          });
      }
    };
    container.appendChild(download_button);

    if (site != 'PTP') {
      var hdb_transfer = document.createElement('input');
      hdb_transfer.type = "button";
      hdb_transfer.id = 'transfer_hdb';
      hdb_transfer.value = '转存HDB';
      hdb_transfer.style.marginLeft = '5px';
      hdb_transfer.style.paddingLeft = '2px';
      container.appendChild(hdb_transfer);
      hdb_transfer.onclick = function () {
        if (raw_info.images.length > 0) {
          raw_info.images.push(raw_info.name.replace(/ /g, '.'));
          GM_setValue('HDB_images', raw_info.images.join(', '));
          window.open('https://img.hdbits.org/', '_blank');
        } else {
          alert('请选择要转存的图片！！！')
        }
      }
    }
  }

  if (site == 'HDB') {
    var send_pixhost = document.createElement('input');
    send_pixhost.type = "button";
    send_pixhost.id = 'send_pixhost';
    send_pixhost.value = 'PIXHOST';
    send_pixhost.style.marginLeft = '12px';
    send_pixhost.onclick = function () {
      if (raw_info.images.length > 0) {
        raw_info.images.push(raw_info.name.replace(/ /g, '.'));
        GM_setValue('HDB_images', raw_info.images.join(', '));
        window.open('https://pixhost.to/', '_blank');
      } else {
        alert('请选择要转存的图片！！！')
      }
    };
    container.appendChild(send_pixhost);

    var send_ptpimg = document.createElement('input');
    send_ptpimg.type = "button";
    send_ptpimg.id = 'send_ptpimg';
    send_ptpimg.value = 'PTPIMG';
    send_ptpimg.style.marginLeft = '12px';
    send_ptpimg.onclick = function () {
      if (raw_info.images.length > 0) {
        GM_setValue('HDB_images', raw_info.images.join(', '));
        window.open('https://ptpimg.me/', '_blank');
      } else {
        alert('请选择要转存的图片！！！')
      }
    };
    container.appendChild(send_ptpimg);

    var send_imgbox = document.createElement('input');
    send_imgbox.type = "button";
    send_imgbox.id = 'send_ptpimg';
    send_imgbox.value = 'IMGBOX';
    send_imgbox.style.marginLeft = '12px';
    send_imgbox.onclick = function () {
      if (raw_info.images.length > 0) {
        raw_info.images.push(raw_info.name.replace(/ /g, '.'));
        GM_setValue('HDB_images', raw_info.images.join(', '));
        window.open('https://imgbox.com/', '_blank');
      } else {
        alert('请选择要转存的图片！！！')
      }
    };
    container.appendChild(send_imgbox);
  }

  if (site != 'IN') {
    var textarea = document.createElement('textarea');
    textarea.style.marginTop = '12px';
    textarea.style.height = '120px';
    textarea.style.width = '580px';
    textarea.id = 'textarea';
    container.appendChild(textarea);
    textarea.style.display = 'none';
    checkBox.addEventListener('click', function (e) {
      if (e.target.checked) {
        $('#textarea').slideDown();
      } else {
        $('#textarea').slideUp();
      }
    }, false);
  } else {
    checkBox.disabled = true;
  }

  // 上下结构
  if (mode == 1) {
    container.align = 'center';
    //匹配站点样式，为了美观
    if (site == 'MTV') {
      $('#douban_button,#ptgen_button,#search_button,#download_pngs').css({ "backgroundColor": "#262626" });
    } else if (site != 'BTN') {
      $('#douban_button,#ptgen_button,#search_button,#download_pngs').css({ "border": "1px solid #2F3546", "color": "#FFFFFF", "backgroundColor": "#2F3546" });
      if (site == 'PTP') {
        textarea.style.width = '675px';
      } else if (site == 'GPW') {
        input_box.style.width = '330px';
        textarea.style.width = '650px';
      } else if (site == 'HD-Only') {
        input_box.style.width = '260px';
        textarea.style.width = '540px';
      }
    } else if (site == 'BTN') {
      textarea.style.width = '530px';
    }
  } else {
    if (['BHD', 'BLU', 'Tik', 'ACM', 'HDOli', 'Monika', 'DTR', 'HONE', 'Aither', 'FNP', 'OnlyEncodes', 'DarkLand', 'ReelFliX', 'IN'].indexOf(site) > -1) {
      $('#douban_button,#ptgen_button,#search_button,#download_pngs').css({ "border": "1px solid #0D8ED9", "color": "#FFFFFF", "backgroundColor": "#292929" });
      if (site == 'HONE') {
        $('#douban_button,#ptgen_button,#search_button,#download_pngs').css({ "width": "80px" })
      }
    } else if (site == 'TorrentLeech') {
      $('#douban_button,#ptgen_button,#search_button,#download_pngs').css({ "border": "1px solid green", "color": "#FFFFFF", "backgroundColor": "#292929" });
    }
    if (site == 'BHD') {
      textarea.style.width = '550px';
    } else if (site == 'BLU' || site == 'Tik' || site == 'Aither') {
      textarea.style.width = '585px';
    }
  }

  if (['HDB', 'PHD', 'avz', 'CNZ', 'FileList', 'TTG'].indexOf(site) > -1) {
    var width = textarea.style.width.match(/\d+/)[0];
    if (site == 'PHD' || site == 'avz' || site == 'CNZ') {
      textarea.style.width = `${parseInt(width) + 90}px`;
    } else if (site == 'FileList') {
      textarea.style.width = `${parseInt(width) + 35}px`;
    } else {
      textarea.style.width = `${parseInt(width) + 55}px`;
    }
  }

  //把白框换个颜色
  if (['PTP', 'xthor', 'HDF', 'BHD', 'BLU', 'Tik', 'Aither', 'TorrentLeech', 'DarkLand', 'ACM', 'HDOli', 'Monika', 'DTR', 'HONE', 'FNP', 'OnlyEncodes', 'ReelFliX'].indexOf(site) > -1) {
    textarea.style.backgroundColor = '#4d5656';
    textarea.style.color = 'white';
    input_box.style.backgroundColor = '#4d5656';
    input_box.style.color = 'white';
  }

  if (site == 'TorrentLeech' && $('#off').css('display') == 'none') {
    input_box.style.color = 'black';
    textarea.style.color = 'black';
    douban_button.style.color = 'black';
    ptgen_button.style.color = 'black';
    search_button.style.color = 'black';
  }
}

function transmissionRequest(rpcUrl, username, password, base64, path, tag, skip_checking) {
  let sessionId = "";
  let data = {
    method: "torrent-add",
    arguments: {
      'metainfo': base64,
      'download-dir': path,
      'labels': tag,
      'skip-verify': skip_checking
    }
  };
  return new Promise((resolve, reject) => {
    const headers = {
      "Content-Type": "application/json",
      "X-Transmission-Session-Id": sessionId,
      "Authorization": "Basic " + btoa(username + ":" + password)
    };
    GM_xmlhttpRequest({
      method: "POST",
      url: rpcUrl,
      headers,
      data: JSON.stringify(data),
      onload: function (res) {
        // 先带用户名和密码获取sessionID，409返回sessionID
        console.log(res);
        if (res.status === 409) {
          const newSessionId = res.responseHeaders.match(/X-Transmission-Session-Id:\s*(.+)/i);
          if (newSessionId) { sessionId = newSessionId[1].trim(); }
          // 获取sessionID，添加种子
          GM_xmlhttpRequest({
            method: "POST",
            url: rpcUrl,
            headers: {
              ...headers,
              "X-Transmission-Session-Id": sessionId
            },
            data: JSON.stringify(data),
            onload: function (res2) {
              let result = JSON.parse(res2.responseText);
              if (result.result == 'success') {
                var $alertBox = $('#autoDismissAlert');
                $alertBox.fadeIn(400);
                setTimeout(function () {
