/**
 * @module 16_origin_site_parsing3
 * @description origin_site blocks: exclusivity checks, FRDS, HDB, CMCT...
 * @lines 13001-14313
 * 
 * Extracted from auto_feed.user.js
 * DO NOT EDIT - Auto-generated by split_modules.py
 */

        box_left.setAttribute('class', 'colhead');
      }
    }

    if (origin_site == 'CG') {
      forward_l.setAttribute('class', 'rowhead');
      box_left.setAttribute('class', 'rowhead');
    }

    //循环部署转发节点，根据自己情况进行增加或删减
    var para;
    forward_r.id = 'forward_r';
    var style = document.createElement("style");
    style.type = "text/css";
    var text = document.createTextNode(".round_icon{ width: 12px; height: 12px; border-radius: 90%; margin-right: 2px;} #douban_button {outline:none;}");
    style.appendChild(text);
    var head = document.getElementsByTagName("head")[0];
    head.appendChild(style);

    var img_url, key;
    for (index = 0; index < site_order.length; index++) {
      var key = site_order[index];
      if (used_site_info[key].enable) {
        if (forward_r.innerHTML) {
          forward_r.innerHTML = forward_r.innerHTML + ' | ';
        }
        para = document.createElement("a");
        para.setAttribute('class', 'forward_a');
        forward_r.appendChild(para);
        para.target = "_blank"; para.id = key;

        if (Object.keys(pt_icos).length === 0 || pt_icos[key] === undefined) {
          img_url = used_site_info[key].url + 'favicon.ico';
          if (origin_site != 'mam') {
            img_url_wsrv = 'https://wsrv.nl/?url=' + img_url;
          } else {
            img_url_wsrv = img_url;
          }
          para.innerHTML = '<div style="display:inline-block; margin-bottom: 2px;"><img src="' + img_url_wsrv +
            '"onerror="this.onerror=null; this.src=' + "'" + img_url + "'" +
            '"class="round_icon" style="display:inline-block">' + key + '</div>';
        } else {
          if (pt_icos[key] == 'default') {
            para.innerHTML = '<div style="display:inline-block; margin-bottom: 2px;"><img src="' + pt_icos['default'] +
              '"class="round_icon" style="display:inline-block">' + key + '</div>';
          } else {
            para.innerHTML = '<div style="display:inline-block; margin-bottom: 2px;"><img src="' + pt_icos[key] +
              '"class="round_icon" style="display:inline-block">' + key + '</div>';
          }
        }

      }
    }

    var check = document.createElement("input");
    check.setAttribute("type", "checkbox");
    check.setAttribute("id", 'search_type');
    var check_text = document.createTextNode('查重');
    forward_r.append(check);
    forward_r.append(check_text);
    set_jump_href(raw_info, 1);

    if (origin_site == 'PTer') {
      try { raw_info.url = $('a:contains("http://www.imdb.com")').last().text(); } catch (err) { }
    }

    forward_r.innerHTML = forward_r.innerHTML + ' <br><br><font color="green">Tools →</font> ';

    var wiki = document.createElement('a');
    wiki.innerHTML = '教程';
    wiki.title = 'Github教程。';
    wiki.id = 'wiki';
    wiki.href = 'https://gitee.com/tomorrow505/auto_feed_js/wikis/pages';
    wiki.target = '_blank';
    wiki.style.color = 'red';
    forward_r.appendChild(wiki);
    forward_r.innerHTML = forward_r.innerHTML + ' | ';

    var ptgen = document.createElement('a');
    ptgen.innerHTML = 'PTgen';
    ptgen.id = 'ptgen';
    ptgen.title = '根据页面的豆瓣或imdb的ID获取豆瓣信息。';
    ptgen.href = host_link + '#ptgen?';
    if (raw_info.dburl) {
      ptgen.href = raw_info.dburl;
    } else if (raw_info.url) {
      ptgen.href += raw_info.url.match(/tt\d+/)[0];
    }
    ptgen.target = '_blank';
    forward_r.appendChild(ptgen);

    forward_r.innerHTML = forward_r.innerHTML + ' | ';
    var get_img = document.createElement('a');
    get_img.innerHTML = '提取图片';
    get_img.title = '对页面图片进行转存或者大图等操作，具体见教程。';
    get_img.id = 'get_img';
    get_img.href = host_link + '#dealimg';
    get_img.target = '_blank';
    forward_r.appendChild(get_img);

    //添加常用链接跳转
    if (used_common_sites.length > 0) {
      forward_r.innerHTML = forward_r.innerHTML + ' | ';

      var common_link = document.createElement('a');
      forward_r.appendChild(common_link);
      common_link.id = 'common_link';
      common_link.title = '一键打开设置的所有转发站点，需要开启弹窗设置，具体见教程。';
      common_link.setAttribute('class', 'forward_a');

      common_link.href = '#common_link';
      window.scrollBy(0, -150);
      common_link.innerHTML = '常用站点';
    }

    forward_r.innerHTML = forward_r.innerHTML + ' | ';
    var mediainfo_link = document.createElement('a');
    mediainfo_link.innerHTML = '简化MI';
    mediainfo_link.title = '部分站点(如HDT)需要简化的Mediainfo/BDinfo，可以输入原始Mediainfo/BDinfo进行转换';
    mediainfo_link.href = host_link + "#mediainfo";
    mediainfo_link.target = '_blank';
    forward_r.appendChild(mediainfo_link);

    forward_r.innerHTML = forward_r.innerHTML + ' | ';
    var setting_link = document.createElement('a');
    setting_link.innerHTML = '脚本设置';
    setting_link.title = '对脚本的一些选项进行设置，具体内容见教程。';
    setting_link.href = host_link + '#setting';
    setting_link.target = '_blank';
    forward_r.appendChild(setting_link);

    forward_r.innerHTML = forward_r.innerHTML + ' | ';
    var reset_host = document.createElement('a');
    reset_host.innerHTML = '重置托管';
    reset_host.title = '重置脚本托管页面，避免网站关停情况脚本功能失灵。';
    reset_host.id = "reset_host";
    reset_host.href = host_link + '#setting';
    reset_host.target = '_blank';
    forward_r.appendChild(reset_host);

    forward_r.innerHTML = forward_r.innerHTML + ' | ';
    var rehost_link = document.createElement('a');
    rehost_link.innerHTML = '单图转存';
    rehost_link.title = '过期功能，基本上可以使用提取图片进行覆盖，具体见教程。';
    rehost_link.href = "#";
    rehost_link.target = '_blank';
    forward_r.appendChild(rehost_link);

    if (used_ptp_img_key != '') {
      forward_r.innerHTML = forward_r.innerHTML + ' | ';
      var refresh_icos = document.createElement('a');
      refresh_icos.href = '#';
      refresh_icos.id = 'refresh_icos';
      refresh_icos.innerHTML = '图标刷新';
      forward_r.appendChild(refresh_icos);
    }

    forward_r.innerHTML = forward_r.innerHTML + ' | ';
    var sign_in = document.createElement('a');
    sign_in.innerHTML = '签到';
    sign_in.title = '一键签到的简单实现。'
    sign_in.href = host_link + '#signin';
    sign_in.target = '_blank';
    forward_r.appendChild(sign_in);

    if (used_common_sites.length > 0) {
      if (origin_site != 'CMCT' || cmct_mode == 1) {
        if (origin_site != 'UHD' && origin_site != 'TTG') {
          document.getElementById('common_link').onclick = function () {
            var key;
            for (index in site_order) {
              key = site_order[index];
              if (used_common_sites.indexOf(key) > -1 && origin_site != key) {
                if (['PTP', 'KG', 'BTN', 'GPW', 'SC', 'avz', 'PHD', 'CNZ', 'ANT', 'NBL', 'HDCity'].indexOf(key) < 0) {
                  var site_href = document.getElementById(key).href;
                  window.open(site_href, '_blank');
                } else {
                  $(`#${key}`).click();
                }
              }
            }
          };
        }
      }
    }
    var search_name = get_search_name(raw_info.name);
    try {
      var imdbid = raw_info.url.match(/tt\d+/i)[0];
      var imdbno = imdbid.substring(2);
      var container = $('#forward_r');
      add_search_urls(container, imdbid, imdbno, search_name, 0);
    } catch (err) {
      var imdbid = '';
      var imdbno = '';
      var container = $('#forward_r');
      add_search_urls(container, imdbid, imdbno, search_name, 0);
    }

    if (origin_site == 'CMCT' && cmct_mode == 2) {
      setTimeout(function () {
        raw_info.descr = '';
        raw_info.extra_text = '';
        try { raw_info.extra_text = walkDOM(document.getElementsByClassName('extra-text')[0].cloneNode(true)).trim(); } catch (Err) { }
        //海报和简介
        var img_address = document.getElementById("kposter").getElementsByTagName("img")[0].src;
        try {
          var descr_box = document.getElementsByClassName('info douban-info');
          var descr_node = descr_box[0].getElementsByTagName('artical')[0];
          descr_node = descr_node.cloneNode(true);
          raw_info.descr = walk_cmct(descr_node).trim().replace(/        ◎/, '◎');
          if (raw_info.extra_text) {
            raw_info.descr = raw_info.descr.replace(raw_info.extra_text, '');
          }
        } catch (err) { }
        raw_info.descr = '[img]' + img_address + '[/img]\n\n' + raw_info.descr + '\n\n';
        if (raw_info.extra_text) {
          raw_info.extra_text = raw_info.extra_text.includes('[quote]') ? raw_info.extra_text : '[quote]\n' + raw_info.extra_text + '\n[/quote]\n';
          raw_info.descr = raw_info.extra_text + '\n' + raw_info.descr;
        }
        try {
          var $html = $('td').filter('.douban_info').html();
          if ($html.match(/https:\/\/www.imdb.com\/title\/tt\d+/)) {
            raw_info.url = $html.match(/https:\/\/www.imdb.com\/title\/tt\d+/)[0];
            var imdbid = raw_info.url.match(/tt\d+/i)[0];
            var imdbno = imdbid.substring(2);
            var container = $('#forward_r');
            add_search_urls(container, imdbid, imdbno, search_name, 0);
          }
        } catch (err) { }
        //mediainfo——短
        try {
          var mediainfo = document.getElementsByClassName("codemain")[0];
          mediainfo = domToString(mediainfo.cloneNode(true));
          mediainfo = mediainfo.replace(/(<div class="codemain">|<\/div>)/g, '');
          mediainfo = mediainfo.replace(/<br>/g, '\n');
          // raw_info.descr += '[quote]' + mediainfo + '[/quote]\n\n';
        } catch (err) {
          console.log('获取mediainfo失败：' + err);
        }

        try {
          var mediainfo1 = document.getElementsByClassName("codemain")[1];
          mediainfo1 = domToString(mediainfo1.cloneNode(true));
          mediainfo1 = mediainfo1.replace(/(<div class="codemain">|<\/div>)/g, '');
          mediainfo1 = mediainfo1.replace(/<br>/g, '\n');
          raw_info.full_mediainfo = mediainfo1;
          raw_info.descr += '[quote]' + mediainfo1 + '[/quote]\n\n';
        } catch (err) { }

        //截图
        var screenshot = document.getElementsByClassName("screenshots-container");
        for (i = 0; i < screenshot.length; i++) {
          var img = screenshot[i].getElementsByTagName("img");
          for (j = 0; j < img.length; j++) {
            if (img[j] && img[j].src.search(/detail/i) < 0) {
              raw_info.descr = raw_info.descr + '[img]' + img[j].src + '[/img]\n';
            }
          }
        }
        raw_info.descr = add_thanks(raw_info.descr);
      }, 1000);
    }

    if (origin_site == 'MTV') {
      $('img.round_icon').hide();
    }

    $('.hdb-task').click((e) => {
      GM_setValue('task_info', JSON.stringify(raw_info));
    });

    //判断是否禁转
    var if_exclusive = false;
    if (origin_site == 'PigGo' && $('span:contains("禁转")').length) {
      if_exclusive = true;
    } else if (origin_site == 'HHClub' && $('span:contains("禁转")').is(':visible')) {
      if_exclusive = true;
    } else if (origin_site == 'TJUPT' && ($('#tag').find('.tag-exclusive').length)) {
      if_exclusive = true;
    } else if (origin_site == 'PTer' && $('#kdescr').parent().parent().parent().find('a[href*="tag_exclusive=yes"]').length) {
      if_exclusive = true;
    } else if (origin_site == 'OpenCD' && opencd_mode == 0 && document.querySelector("#outer > center > table:nth-child(4) > tbody > tr:nth-child(6) > td:nth-child(2) > table > tbody > tr:nth-child(13)").textContent == "禁止轉載") {
      if_exclusive = true;
    } else if (origin_site == 'CHDBits') {
      if (raw_info.name.match(/CHD|SGNB|STBOX|ONEHD|BLUCOOK|HQC|GBT|KAN|PLP/i)) {
        if (raw_info.url) {
          $('#top').append(`<br><b><span id="checking"><font color="red">[禁转判断中……]</font></span></b>`);
          var check_url = default_site_info[origin_site].url + 'torrents.php?incldead=0&spstate=0&inclbookmarked=0&search={imdbid}&search_area=4&search_mode=0';
          var imdbid = raw_info.url.match(/tt\d+/)[0];
          check_url = check_url.format({ 'imdbid': imdbid });
          getDoc(check_url, null, function (doc) {
            var $table = $('.torrents', doc);
            var torrentid = site_url.match(/id=\d+/)[0];
            var torrent = $table.find(`a[href*="${torrentid}"]`);
            if (torrent) {
              if (torrent.parent().html().match(/tag-dz/)) {
                $('#checking').html('<font color="red">[独占资源]</font>');
                if_exclusive = true;
              } else if (torrent.parent().html().match(/tag-limited/)) {
                $('#checking').html('<font color="red">[限转资源]</font>');
                if_exclusive = true;
              } else {
                $('#checking').html('<font color="red">[一般资源]</font>');
              }
            } else {
              $('#checking').html('<font color="red">[查找失败, 自己检查]</font>');
            }
          });
        } else {
          $('#top').append(`<br><b><span id="checking"><font color="red">[缺少IMDB请自查]</font></span></b>`);
        }
      } else {
        $('#top').append(`<br><b><span id="checking"><font color="red">[一般资源]</font></span></b>`);
      }
    } else if (origin_site == 'FRDS') {
      if (raw_info.url) {
        $('#top').append(`<br><b><span id="checking"><font color="red">[禁转判断中……]</font></span></b>`);
        var check_url = 'https://pt.keepfrds.com/torrents.php?incldead=1&spstate=0&inclbookmarked=0&search={imdbid}&search_area=4&search_mode=0';
        var imdbid = raw_info.url.match(/tt\d+/)[0];
        check_url = check_url.format({ 'imdbid': imdbid });
        getDoc(check_url, null, function (doc) {
          var $table = $('.torrents', doc);
          var torrentid = site_url.match(/id=\d+/)[0];
          var torrent = $table.find(`a[href*="${torrentid}"]`);
          if (torrent) {
            if (torrent.parent().html().match(/限时禁转/)) {
              $('#checking').html('<font color="red">[限转资源]</font>');
              if_exclusive = true;
            } else if (torrent.parent().html().match(/禁转/)) {
              $('#checking').html('<font color="red">[禁转资源]</font>');
              if_exclusive = true;
            } else {
              $('#checking').html('<font color="red">[一般资源]</font>');
            }
          } else {
            $('#checking').html('<font color="red">[查找失败, 自己检查]</font>');
          }
        });
      } else {
        $('#top').append(`<br><b><span id="checking"><font color="red">[缺少IMDB请自查]</font></span></b>`);
      }
    } else if (['HDDolby', 'HDHome', 'PThome', 'Audiences'].indexOf(origin_site) > -1) {
      if ($('tr:contains("标签"):last').find('span.txz').length || $('tr:contains("标签"):last').find('span.tjz').length) {
        if_exclusive = true;
      }
    } else if (origin_site == 'BHD') {
      if ($('strong:contains("THIS IS A BEYONDHD EXCLUSIVE.")').length) {
        if_exclusive = true;
      }
    } else if (origin_site == 'HDB' && $('div.torrent-title>span.exclusive').length) {
      if_exclusive = true;
    } else if (origin_site == 'CMCT' && $('span:contains("禁转")').length) {
      if_exclusive = true;
    }

    if ((raw_info.name + raw_info.descr + raw_info.small_descr).replace(/\[.*?\]/g, '').match(/(拒绝转发|不允许转发|严禁转发|谢绝.*?转载|禁转|禁止转载|禁转|謝絕.*?轉載|exclusive|严禁转载)/i)) {
      if_exclusive = true;
    }

    if (raw_info.name.match(/Audies$|-ADE$|-ADWeb$|UBits$|HHWEB$|-beAst$|-beAstTV$/i)) {
      $('#PTT').attr('disabled', true).css("pointer-events", "none").css("color", "grey").text(' 禁转至PTT');
      if (raw_info.name.match(/UBits$/i)) {
        $('#HDSky').attr('disabled', true).css("pointer-events", "none").css("color", "grey").text(' 禁转至HDSky');
        $('#CMCT').attr('disabled', true).css("pointer-events", "none").css("color", "grey").text(' 禁转至CMCT');
      }
    }
    if (raw_info.name.match(/Dream$|DBTV$|QHstudIo$|CornerMV$/i)) {
      $('#HDVideo').attr('disabled', true).css("pointer-events", "none").css("color", "grey").text(' 禁转至HDVideo');
      $('#OpenCD').attr('disabled', true).css("pointer-events", "none").css("color", "grey").text(' 禁转至OpenCD');
    }
    if (raw_info.name.match(/HDVWEB$|HDVMV$/i)) {
      $('#HDDolby').attr('disabled', true).css("pointer-events", "none").css("color", "grey").text(' 禁转至HDDolby');
    }
    if (raw_info.name.match(/HDH(ome|TV|PAD|WEB)$|-HDH$/i)) {
      $('#PThome').attr('disabled', true).css("pointer-events", "none").css("color", "grey").text(' 禁转至PThome');
    }

    function check_exist_tid(site) {
      if (site == 'PTP') {
        if (search_mode == 0 || if_exclusive) {
          return;
        }
        if (raw_info.type != '电影' || (raw_info.name + raw_info.small_descr).match(/DIY|@/)) {
          if (!confirm('该资源可能不是电影或者属于DIY资源，确定发布？')) {
            e.preventDefault();
            return;
          }
        }
        if (raw_info.name.match(/BMDru/)) {
          if (!confirm('该小组作品被PTP认定为劣质资源，确定发布？')) {
            e.preventDefault();
            return;
          }
        }
        if (raw_info.url) {
          var url = 'https://passthepopcorn.me/torrents.php?searchstr=' + raw_info.url.match(/tt\d+/)[0];
          GM_xmlhttpRequest({
            method: 'GET',
            url: url,
            onload: function (res) {
              var upload_url = 'https://passthepopcorn.me/upload.php';
              if (res.finalUrl.match(/id=\d+/)) {
                upload_url += '?group' + res.finalUrl.match(/id=\d+/)[0];
              }
              jump_str = dictToString(raw_info);
              site_href = upload_url + separator + encodeURI(jump_str);
              window.open(site_href, '_blank');
              return;
            }
          });
        } else {
          var url = 'https://passthepopcorn.me/torrents.php?searchstr=' + search_name;
          GM_xmlhttpRequest({
            method: 'GET',
            url: url,
            onload: function (res) {
              var upload_url = 'https://passthepopcorn.me/upload.php';
              if (res.finalUrl.match(/id=\d+/)) {
                upload_url += '?group' + res.finalUrl.match(/id=\d+/)[0];
              }
              jump_str = dictToString(raw_info);
              site_href = upload_url + separator + encodeURI(jump_str);
              window.open(site_href, '_blank');
              return;
            }
          });
        }
      }
      else if (site == 'SC') {
        if (search_mode == 0 || if_exclusive) {
          return;
        }
        if (raw_info.type != '电影' || (raw_info.name + raw_info.small_descr).match(/DIY|@/)) {
          if (!confirm('该资源可能不是电影或者属于DIY资源，确定发布？')) {
            e.preventDefault();
            return;
          }
        }
        if (raw_info.url) {
          var url = 'https://secret-cinema.pw/torrents.php?action=advanced&searchsubmit=1&filter_cat=1&cataloguenumber=' + raw_info.url.match(/tt\d+/)[0];
          GM_xmlhttpRequest({
            method: 'GET',
            url: url,
            onload: function (res) {
              doc = res.responseText;
              var upload_url = 'https://secret-cinema.pw/upload.php';
              if ($('div.torrent_card_container', doc).length) {
                upload_url += '?group' + $('div.torrent_card_container', doc).find('a').attr('href').match(/id=\d+/)[0];
              }
              jump_str = dictToString(raw_info);
              site_href = upload_url + separator + encodeURI(jump_str);
              window.open(site_href, '_blank');
              return;
            }
          });
        } else {
          var url = 'https://secret-cinema.pw/torrents.php?searchstr=' + search_name;
          GM_xmlhttpRequest({
            method: 'GET',
            url: url,
            onload: function (res) {
              doc = res.responseText;
              var upload_url = 'https://secret-cinema.pw/upload.php';
              if ($('div.torrent_card_container', doc).length) {
                upload_url += '?group' + $('div.torrent_card_container', doc).find('a').attr('href').match(/id=\d+/)[0];
              }
              jump_str = dictToString(raw_info);
              site_href = upload_url + separator + encodeURI(jump_str);
              window.open(site_href, '_blank');
              return;
            }
          });
        }
      }
      else if (site == 'TVV') {
        if (search_mode == 0 || if_exclusive) {
          return;
        }
        if (raw_info.url) {
          var url = 'http://tv-vault.me/torrents.php?action=advanced&searchstr=&searchtags=&tags_type=1&groupdesc=&imdbid=' + raw_info.url.match(/tt\d+/)[0];
          GM_xmlhttpRequest({
            method: 'GET',
            url: url,
            onload: function (res) {
              doc = res.responseText;
              console.log(doc)
              var upload_url = 'http://tv-vault.me/upload.php';
              if ($('#torrent_table', doc).length) {
                upload_url += '?group' + $('#torrent_table', doc).find('tr.group').find('a[href*=torrents]').attr('href').match(/id=\d+/)[0];
              }
              jump_str = dictToString(raw_info);
              site_href = upload_url + separator + encodeURI(jump_str);
              window.open(site_href, '_blank');
              return;
            }
          });
        } else {
          var url = 'http://tv-vault.me/torrents.php?action=advanced&searchstr=' + search_name;
          GM_xmlhttpRequest({
            method: 'GET',
            url: url,
            onload: function (res) {
              doc = res.responseText;
              var upload_url = 'http://tv-vault.me/upload.php';
              if ($('#torrent_table', doc).length) {
                upload_url += '?group' + $('#torrent_table', doc).find('tr.group').find('a[href*=torrents]').attr('href').match(/id=\d+/)[0];
              }
              jump_str = dictToString(raw_info);
              site_href = upload_url + separator + encodeURI(jump_str);
              window.open(site_href, '_blank');
              return;
            }
          });
        }
      }
      else if (site == 'avz' || site == 'PHD' || site == 'CNZ') {
        if (search_mode == 0 || if_exclusive) {
          return;
        }
        GM_setValue('avz_info', JSON.stringify(raw_info));
        var domain = {
          'avz': 'avistaz.to', 'PHD': 'privatehd.to', 'CNZ': 'cinemaz.to'
        }
        if (raw_info.url) {
          var url = `https://${domain[site]}/movies?search=&imdb=` + raw_info.url.match(/tt\d+/)[0];
          var upload_url = `https://${domain[site]}/upload/movie`;
          if (raw_info.type != '电影' && raw_info.type != '纪录') {
            url = `https://${domain[site]}/tv-shows?search=&imdb=` + raw_info.url.match(/tt\d+/)[0];
            upload_url = `https://${domain[site]}/upload/tv`;
          }
          GM_xmlhttpRequest({
            method: 'GET',
            url: url,
            onload: function (res) {
              doc = res.responseText;
              if ($('div.overlay-container', doc).length) {
                upload_url += '?movie_id=' + $('div.overlay-container', doc).find('a').attr('href').match(/\d+/)[0];
              }
              jump_str = dictToString(raw_info);
              site_href = upload_url + separator + encodeURI(jump_str);
              window.open(site_href, '_blank');
              return;
            }
          });
        } else {
          var upload_url = `https://${domain[site]}/upload/movie`;
          if (raw_info.type != '电影') {
            upload_url = `https://${domain[site]}/upload/tv`;
          }
          jump_str = dictToString(raw_info);
          site_href = upload_url + separator + encodeURI(jump_str);
          window.open(site_href, '_blank');
          return;
        }
      }
      else if (site == 'ANT') {
        if (search_mode == 0 || if_exclusive) {
          return;
        }
        var search_name = get_search_name(raw_info.name).replace(/ /g, '+');
        var url = 'https://anthelion.me/torrents.php?searchstr=' + search_name;
        if (raw_info.url) {
          var imdbid = raw_info.url.match(/tt\d+/)[0];
        } else {
          imdbid = 0;
        }
        GM_xmlhttpRequest({
          method: 'GET',
          url: url,
          onload: function (res) {
            doc = res.responseText;
            var upload_url = 'https://anthelion.me/upload.php';
            if ($('#torrent_table', doc).length) {
              var table = $('#torrent_table', doc);
              ids = table.find('tr.group').map((index, e) => {
                var imdburl = $(e).find('a:contains(IMDb:)').attr('href');
                console.log(imdburl)
                if (imdbid && imdburl.match(imdbid)) {
                  return $(e).find('a.torrent_title').attr('href').match(/id=\d+/)[0];
                }
              });
              if (ids.length) {
                upload_url += '?group' + ids[0];
              }
            }
            jump_str = dictToString(raw_info);
            site_href = upload_url + separator + encodeURI(jump_str);
            window.open(site_href, '_blank');
            return;
          }
        });
      }
      else if (site == 'GPW') {
        if (search_mode == 0 || if_exclusive) {
          return;
        }
        if (raw_info.url) {
          var url = 'https://greatposterwall.com/torrents.php?searchstr=' + raw_info.url.match(/tt\d+/)[0];
          GM_xmlhttpRequest({
            method: 'GET',
            url: url,
            onload: function (res) {
              var upload_url = 'https://greatposterwall.com/upload.php';
              if (res.responseText.match(/upload.php\?groupid=\d+/)) {
                upload_url += '?group' + res.responseText.match(/upload.php\?group(id=\d+)/)[1];
              }
              jump_str = dictToString(raw_info);
              site_href = upload_url + separator + encodeURI(jump_str);
              window.open(site_href, '_blank');
              return;
            }
          });
        } else {
          var url = 'https://greatposterwall.com/torrents.php?searchstr=' + search_name;
          GM_xmlhttpRequest({
            method: 'GET',
            url: url,
            onload: function (res) {
              var upload_url = 'https://greatposterwall.com/upload.php';
              if (res.responseText.match(/group_movie_title_a.*id=\d+/)) {
                upload_url += '?group' + res.responseText.match(/group_movie_title_a.*(id=\d+)/)[1];
              }
              jump_str = dictToString(raw_info);
              site_href = upload_url + separator + encodeURI(jump_str);
              window.open(site_href, '_blank');
              return;
            }
          });
        }
      }
      else if (site == 'KG') {
        if (search_mode == 0 || if_exclusive) {
          return;
        }
        GM_setValue('kg_info', JSON.stringify(raw_info));
        var href = 'https://karagarga.in/upload.php';
        window.open(href, target = "_blank");
      }
      else if (site == 'HDCity') {
        if (search_mode == 0 || if_exclusive) {
          return;
        }
        GM_setValue('hdcity_info', JSON.stringify(raw_info));
        var href = 'https://hdcity.city/upload';
        window.open(href, target = "_blank");
      }
      else if (site == 'BTN') {
        if (search_mode == 0 || if_exclusive) {
          return;
        }
        GM_setValue('btn_info', JSON.stringify(raw_info));
        var href = `${used_site_info.BTN.url}upload.php`;
        window.open(href, target = "_blank");
      }
    }

    function if_ying_allowed() {
      var info = [];
      if (raw_info.name.match(/remux/i) || (raw_info.name + raw_info.descr).get_label().diy || raw_info.medium_sel == 'Remux') {
        info.push("禁止发布 DIY 和 Remux 资源。");
      } else if (raw_info.medium_sel == 'Encode' && !raw_info.name.match(/WEB/)) {
        if (!raw_info.name.match(/-CMCT/i) && !raw_info.name.match(/-WiKi/i)) {
          info.push('压制资源仅接受这些小组的作品：WiKi / CMCT。这些小组的作品可以共存，不会视为重复。接受的小组，将来会逐步增加。');
        }
      }
      if (raw_info.standard_sel == '720p') {
        info.push("禁止发布分辨率 720p 的资源！");
      } else if (raw_info.standard_sel == '1080p' || raw_info.standard_sel == '1080i') {
        if (raw_info.medium_sel == 'Encode') {
          if (['DTS-HD HR', 'DTS-HD MA', 'LPCM', 'TrueHD', 'Atmos'].indexOf(raw_info.audiocodec_sel) >= 0) {
            info.push("1080p压制：禁止发布带有次世代音轨(DTS-HD HR / DTS-HD MA / LPCM / TrueHD / TrueHD Atmos)的资源");
          }
        }
      } else if (raw_info.standard_sel == '4K') {
        if (raw_info.medium_sel == 'Encode') {
          if (['DTS-HD HR', 'DTS-HD MA', 'LPCM', 'TrueHD', 'Atmos'].indexOf(raw_info.audiocodec_sel) < 0) {
            info.push('2016p压制：必须带有主语言的次世代音轨，除非压制来源的原盘没有。');
          }
        }
      }
      if (!(raw_info.name + raw_info.descr + raw_info.small_descr).get_label().zz) {
        info.push('压制资源必须带有中文字幕，视频内嵌和外挂都可以。外挂的字幕，必须在3天内上传，否则种子会被删除。');
      }
      if (raw_info.name.match(/E\d+/)) {
        info.push('禁止普通会员发布分集资源，只有驻站组和官方组才能发布组内分集资源。');
      }
      if (['游戏', '软件'].indexOf(raw_info.type) >= 0) {
        info.push('禁止发布电子书/软件等非视频资源。');
      }
      if (!raw_info.dburl && !raw_info.url) {
        info.push('发布的资源，必须有豆瓣链接或者IMDB链接。此规则以后会调整，目前严格执行。');
      }
      return info;
    }

    $('.forward_a').click(function (e) {

      if (search_mode) {
        if (origin_site == 'FRDS' || raw_info.name.match(/frds/i)) {
          if (['CMCT', 'OurBits', 'HDSky'].indexOf(e.target.id) > -1) {
            e.preventDefault();
            alert('不支持该站资源转发！');
            return;
          }
        } else if (raw_info.name.match(/Audies$|-ADE$|-ADWeb$/i)) {
          if (['PTT'].indexOf(this.id) > -1) {
            alert('该资源触发了禁转规则(观众资源禁转到PTT)！！！');
            e.preventDefault();
            return;
          }
        } else if (this.id == 'OurBits' && (raw_info.medium_sel == 'Remux' || raw_info.name.medium_sel() == 'Remux')) {
          e.preventDefault();
          alert('该站禁止Remux资源转发！');
          return;
        }
        if (this.id == "影" && ['CMCT', 'TTG', 'UHD', 'FileList', 'RED', 'TJUPT', 'HDB', 'PTsbao', 'HD-Only'].indexOf(origin_site) < 0) {
          info = if_ying_allowed();
          if (info.length) {
            if (!confirm(`转发该资源可能违反站点以下规则:\n${info.join('\n')}\n具体细节请查看站点规则页面。\n是否仍继续发布？`)) {
              e.preventDefault();
              return;
            }
          }
        }
        //判断是否禁止转载，如果确认之后也可以转载
        if (if_exclusive) {
          if (!confirm('该资源可能禁止转载，请检查后确定是否仍旧发布？')) {
            e.preventDefault();
            return;
          } else {
            if_exclusive = false;
          }
        }

        if (['PTP', 'SC', 'TVV', 'avz', 'PHD', 'CNZ', 'HDCity', 'BTN', 'ANT', 'GPW', 'KG'].indexOf(this.id) > -1) {
          e.preventDefault();
          check_exist_tid(this.id);
        }
      }
    });

    function re_forward(_id, _href, raw_info) {
      jump_str = dictToString(raw_info);
      if (_id != 'common_link') {
        _href = decodeURI(_href).split(separator)[0] + separator + encodeURI(jump_str);
        if (['KG', 'PTP', 'HDCity', 'BTN', 'GPW', 'SC', 'avz', 'PHD', 'CNZ', 'TVV'].indexOf(_id) < 0) {
          if (_id == "影") {
            info = if_ying_allowed();
            if (info.length) {
              if (!confirm(`转发该资源可能违反站点以下规则:\n${info.join('\n')}\n具体细节请查看站点规则页面。\n是否仍继续发布？`)) {
                e.preventDefault();
                return;
              }
            } else {
              window.open(_href, '_blank');
            }
          } else {
            window.open(_href, '_blank');
          }
        }
      } else {
        var key;
        for (key in used_common_sites) {
          if (origin_site != used_common_sites[key] && typeof (used_common_sites[key]) == "string") {
            var site_href = document.getElementById(used_common_sites[key]).href;
            site_href = decodeURI(site_href).split(separator)[0] + separator + encodeURI(jump_str);
            if (used_common_sites[key] == "影") {
              info = if_ying_allowed();
              if (info.length) {
                if (confirm(`转发该资源可能违反站点以下规则:\n${info.join('\n')}\n具体细节请查看站点规则页面。\n是否仍继续发布？`)) {
                  window.open(site_href, '_blank');
                }
              } else {
                window.open(_href, '_blank');
              }
            } else {
              window.open(site_href, '_blank');
            }
          }
        }
      }
    }

    if (['UHD', 'FileList', 'RED', 'TJUPT', 'HDB', 'PTsbao', 'HD-Only'].indexOf(origin_site) > -1) {
      $('.forward_a').click(function (e) {
        if (['KG', 'PTP', 'HDCity', 'BTN', 'GPW', 'common_link', 'SC', 'avz', 'PHD', 'CNZ', 'TVV', 'ANT', 'NBL', 'CarPt'].indexOf(this.id) > -1) {
          return;
        }
        e.preventDefault();
        if (if_exclusive && search_mode) {
          return;
        }
        if (search_mode == 0) {
          window.open(this.href, '_blank');
          return;
        }
        if (origin_site == 'UHD' && uhd_lack_descr) {
          var tmp_name = raw_info.descr.match(/movie name.*?:(.*)/i);
          if (tmp_name && !raw_info.name) {
            raw_info.name = tmp_name[1].trim();
            if (check_descr(raw_info.descr)) {
              tmp_name = document.getElementsByClassName('imovie_title')[0].textContent.replace(/\(|\)/g, '').trim();
              raw_info.name = get_bluray_name_from_descr(raw_info.descr, tmp_name);
            }
          }
          raw_info.name = deal_with_title(raw_info.name);
          if (raw_info.name.match(/S\d{2,3}/i)) {
            raw_info.type = '剧集';
          } else {
            raw_info.type = '电影';
          }
          uhd_lack_descr = false;
        }
        if (origin_site == 'TJUPT' || origin_site == 'PTsbao') {
          if (raw_info.type == '动漫') {
            raw_info.animate_info = document.getElementById('top').textContent;
          }
          descr = document.getElementById("kdescr");
          descr = descr.cloneNode(true);
          try {
            var codetop = descr.getElementsByClassName('codetop');
            Array.from(codetop).map((e, index) => {
              try { descr.removeChild(e); } catch (err) { e.parentNode.removeChild(e) }
            });
          } catch (err) {
            console.log(err);
          }
          raw_info.descr = '';
          raw_info.descr = walkDOM(descr);
          raw_info.descr = raw_info.descr.replace(/站外链接 :: /ig, '');
          if (raw_info.descr.match(/Infinity-1.2s-64px.svg/)) {
            if (!confirm('图片可能加载不完全，是否仍继续转载？')) {
              e.preventDefault();
              return;
            }
          }
        }

        var _id = this.id;
        var _href = this.href;
        re_forward(_id, _href, raw_info);
      });
    } else if (origin_site == 'CMCT' && cmct_mode == 2) {
      $('.forward_a').click(function (e) {
        e.preventDefault();
        if (if_exclusive && search_mode) {
          return;
        }
        if (search_mode == 0) {
          window.open(this.href, '_blank');
          return;
        }
        var _id = this.id;
        var _href = this.href;
        re_forward(_id, _href, raw_info);
      });
    } else if (origin_site == 'TTG') {
      $('.forward_a').click(function (e) {
        e.preventDefault();
        if (if_exclusive && search_mode) {
          return;
        }
        if (search_mode == 0) {
          window.open(this.href, '_blank');
          return;
        }
        raw_info.descr = '';
        descr = document.getElementById('kt_d');
        descr_box = descr.cloneNode(true);
        raw_info.descr = walkDOM(descr_box);
        raw_info.descr = add_thanks(raw_info.descr);

        var reg_img = raw_info.descr.match(/\[img\]http(s*):\/\/totheglory.im\/pic\/ico_(free|half|30).gif\[\/img\].*/i);
        if (reg_img) {
          raw_info.descr = raw_info.descr.replace(reg_img[0], '');
        }
        //替换官种简介顺序
        var reg_source = raw_info.descr.match(/\[color=.*?\]\.Comparisons[\s\S]*(thumb\.png|ajax-loader\.gif)\[\/img\]\[\/url\][\s\S]*?\[\/quote\]/im);
        if (reg_source) {
          reg_source = reg_source[0];
          raw_info.descr = raw_info.descr.replace(reg_source, '');
          if (reg_source.match(/\[size=3\].*\[\/size\]/)) {
            var tmp_name = reg_source.match(/\[size=3\].*\[\/size\]/)[0];
            reg_source = reg_source.split(tmp_name);
            reg_source[0] = reg_source[0].replace(/http/g, 'https').replace(/httpss/g, 'https');
            reg_source = tmp_name + reg_source[1] + '\n\n' + reg_source[0];
          }
          raw_info.descr = raw_info.descr + reg_source;
          raw_info.descr = raw_info.descr.replace(/\n{3,5}/ig, '\n\n');
        }

        if (raw_info.images.length > 0) {
          raw_info.descr += $('#textarea').val();
        }

        var _id = this.id;
        var _href = this.href;
        re_forward(_id, _href, raw_info);
      });
    }

    $('#reset_host').click((e) => {
      e.preventDefault();
      set_host_link();
    });

    //----------------------------------界面部署层逻辑：获取豆瓣链接button绑定点击事件-------------------------------------------------

    if ((!judge_if_the_site_in_domestic() && no_need_douban_button_sites.indexOf(origin_site) < 0) || douban_button_needed) {

      douban_button.addEventListener('click', function () {

        douban_button.value = '获取中……';

        var is_douban_needed = false;

        if (raw_info.name.match(/S\d{2}E\d{2}/ig) || raw_info.type == '剧集') {
          if (raw_info.name.match(/S\d{2}/ig)) {
            if (!raw_info.name.match(/S01/ig)) {
              is_douban_needed = true;
            }
          }
        }

        if (raw_info.url && !judge_if_the_site_in_domestic() && !raw_info.dburl) {
          is_douban_needed = true;
        }
        if (douban_button_needed && raw_info.dburl == '') {
          is_douban_needed = true;
        }
        var tmp_url = document.getElementById('input_box').value;
        if (tmp_url.match(/douban.com/)) {
          raw_info.dburl = tmp_url;
          is_douban_needed = false;
        }
        var textarea = document.getElementById('textarea');
        if (textarea && textarea.selectionStart != undefined && textarea.selectionEnd != undefined) {
          var chosen_value = textarea.value.substring(textarea.selectionStart, textarea.selectionEnd);
          var dburl = chosen_value.match(/http(s*):\/\/.*?douban.com\/subject\/(\d+)/i);
          if (dburl) {
            raw_info.dburl = dburl[0] + '/';
            is_douban_needed = false;
          }
        }

        create_site_url_for_douban_info(raw_info, is_douban_needed)
          .then(function (data) {
            console.log(data)
            if (api_chosen == 0 || api_chosen == 2) {
              if (raw_info.dburl) {
                url_to_search = '?url=' + raw_info.dburl;
              } else if (raw_info.url) {
                url_to_search = '?url=' + raw_info.url;
              }
            } else {
              if (raw_info.dburl) {
                url_to_search = '?url=' + raw_info.dburl;
              } else if (raw_info.url) {
                url_to_search = '?site=douban&sid=' + raw_info.url.match(/tt\d+/)[0];
              }
            }
            if (api_chosen < 3) {
              getJson(apis[api_chosen] + url_to_search, null, function (res) {
                if (api_chosen == 0) {
                  var douban_info = !res.msg ? res.data.format : "";
                } else {
                  douban_info = !res.error ? res.format : "";
                }
                douban_info = douban_info.replace("[/img][/center]", "[/img]");
                douban_info = douban_info.replace("hongleyou.cn", "doubanio.com");
                if (douban_info != '') {
                  raw_info.descr = douban_info + '\n\n' + raw_info.descr;
                  var thanks = raw_info.descr.match(/\[quote\].*?感谢原制作者发布。.*?\[\/quote\]/);
                  if (thanks) {
                    raw_info.descr = thanks[0] + '\n' + raw_info.descr.replace(thanks[0], '');
                  }

                  if (is_douban_needed && raw_info.descr.match(/http(s*):\/\/www.imdb.com\/title\/tt(\d+)/i)) {
                    raw_info.url = raw_info.descr.match(/http(s*):\/\/www.imdb.com\/title\/tt(\d+)/i)[0] + '/';
                  }
                  if (raw_info.descr.match(/类[\s\S]{0,5}别[\s\S]{0,30}纪录片/i)) {
                    raw_info.type = '纪录';
                  } else if (raw_info.descr.match(/类[\s\S]{0,5}别[\s\S]{0,30}动画/i)) {
                    raw_info.type = '动漫';
                  }
                  set_jump_href(raw_info, 1);
                  jump_str = dictToString(raw_info);
                  douban_button.value = '获取成功';
                  try { $('#textarea').val(douban_info); } catch (err) { }
                  GM_setClipboard(douban_info);
                  rebuild_href(raw_info);
                } else {
                  douban_button.value = '获取失败';
                }
              });
            } else {
              get_douban_info(raw_info);
            }
          })
          .catch(function (err) {
            douban_button.value = '获取失败';
            if (raw_info.dburl) {
              window.open(raw_info.dburl, target = "_blank");
            } else if (raw_info.url) {
              window.open(`https://search.douban.com/movie/subject_search?search_text=${raw_info.url.match(/tt\d+/)[0]}&cat=1002`, target = "_blank");
            }
            console.log(err);
          });

      }, false);

      search_button.addEventListener('click', function () {
        var search_name = get_search_name(raw_info.name);
        if (raw_info.type == '剧集') {
          if (raw_info.name.match(/S\d+/i)) {
            var number = parseInt(raw_info.name.match(/S(\d+)/i)[1]);
            if (number != 1) {
              search_name = search_name + ' Season ' + number;
            }
          }
        }
        if (raw_info.zh_name) {
          search_name = raw_info.zh_name;
        }
        if ($('#douban_api').prop('checked')) {
          const url_prex = 'https://movie.douban.com/j/subject_suggest?q=';
          var search_url = url_prex + search_name;
          var textarea = document.getElementById('textarea');
          getJson(search_url, null, function (data) {
            if (data.length > 0) {
              textarea.value = `搜索的影视名称为：${raw_info.name}\n`;
              for (i = 0; i < data.length; i++) {
                textarea.value += `${data[i].sub_title}---${data[i].title}: ${douban_prex}${data[i].id}/\n`;
              }
            } else {
              textarea.value += "暂时没有搜索结果！！";
            }
          });

        } else {
          var search_url = 'https://search.douban.com/movie/subject_search?search_text=' + search_name;
          if (raw_info.type == '电影' && raw_info.url) {
            search_url = 'https://search.douban.com/movie/subject_search?search_text=' + raw_info.url.match(/tt\d+/)[0];
          }
          window.open(search_url, target = '_blank');
        }

      }, false);

      ptgen_button.addEventListener('click', function () {
        var tmp_url = document.getElementById('input_box').value;
        create_site_url_for_douban_info(raw_info, true).then(function (data) {
          if (raw_info.dburl) {
            tmp_url = raw_info.dburl.match(/subject\/(\d+)/i)[1];
          } else {
            tmp_url = tmp_url.match(/tt\d+/)[0];
          }
          url = host_link + '#ptgen?' + tmp_url;
          window.open(url, '_blank');
        }, function () {
          url = host_link + '#ptgen?' + tmp_url.match(/tt\d+/)[0];
          window.open(url, '_blank');
        });
      }, false);
    }
    add_picture_transfer();

    $('#get_img').click((e) => {
      if (origin_site == 'TTG') {
        descr = document.getElementById('kt_d');
        descr_box = descr.cloneNode(true);
        raw_info.descr = walkDOM(descr_box);
      } else if (origin_site == 'TJUPT' || origin_site == 'PTsbao') {
        descr = document.getElementById("kdescr");
        descr = descr.cloneNode(true);
        raw_info.descr = '';
        raw_info.descr = walkDOM(descr);
      }
      GM_setValue("descr", raw_info.descr);
    });

    $('#search_type').on('change', function () {
      if (this.checked) {
        search_mode = 0;
        set_jump_href(raw_info, 0);
      } else {
        search_mode = 1;
        set_jump_href(raw_info, 1);
      }
    })

    if ($('#refresh_icos').length) {
      $('#refresh_icos')[0].addEventListener('click', function (e) {
        try {
          getJson('https://gitee.com/tomorrow505/auto-feed-helper/raw/master/sorted_pt_sites_icos.json', null, function (data) {
            GM_setValue('pt_icos', data.data);
            location.reload();
          });
        } catch (err) {
          GM_setValue('pt_icos', '{}');
          location.reload();
        }
      }, false);
    }

    if (origin_site == 'DICMusic') {
      var html = $('#forward_r').html();
      html = html.replace(`<font color="green">Tools →</font>`, '<blockquote style="margin-right:200px"><font color="green">Tools →</font>');
      html = html.replace(`签到</a><br>`, '签到</a></blockquote>');
      html = html.replace(`查重 `, '查重 <div></div>')
      $('#forward_r').html(html);
    }
  }

  /*****************************************************************************************************************
  *                                       part 5 发布页数据逻辑处理                                                  *
  ******************************************************************************************************************/
  else if (judge_if_the_site_as_source() == 0) {
    var upload_site = site_url.split(separator)[0]; //转发的站点
    var forward_site = find_origin_site(upload_site);
    if (upload_site.match(/offers?.php/)) {
      transfer_mode = 1;
    }
    GM_addStyle(`
            #navbarContainer {
                position: fixed; /* 固定定位 */
                top: 48%; /* 垂直居中 */
                right: 10px; /* 距离右侧 10px */
                transform: translateY(-50%); /* 垂直居中 */
                z-index: 1000; /* 确保在其他元素之上 */
                background-color: rgba(0, 0, 0, 0.7); /* 半透明黑色背景 */
                padding: 8px 6px; /* 增加内边距 */
                border-radius: 5px; /* 圆角 */
                display: flex;
                flex-direction: column; /* 垂直排列 */
                align-items: center; /* 水平居中 */
                gap: 8px; /* 链接之间的间距 */
            }

            /* 标题样式 */
            #navbarContainer .title {
                color: white; /* 白色文字 */
                font-size: 10px; /* 稍微增大字体 */
                font-weight: bold; /* 加粗 */
                margin-bottom: 5px; /* 标题下方间距 */
            }

            /* 导航链接样式 */
            #navbarContainer a {
                color: white; /* 白色文字 */
                text-decoration: none; /* 移除下划线 */
                padding: 6px 12px; /* 稍微调整内边距 */
                border-radius: 4px; /* 圆角 */
                transition: background-color 0.3s ease; /* 过渡效果 */
                display: block; /* 垂直排列 */
                width: 30px; /* 固定宽度 */
                font-size: 10px;
                text-align: center; /* 文本居中 */
            }

            /* 鼠标悬停时的样式 */
            #navbarContainer a:hover {
                background-color: rgba(255, 255, 255, 0.2); /* 鼠标悬停时背景颜色变浅 */
            }
        `);

    async function getIMDbPoster(imdbId) {
      url = `https://www.imdb.com/title/${imdbId}/`;
      var doc = await getimdbpage(raw_info.url);
      const imdb_json = JSON.parse($('script[type="application/ld+json"]', doc).text());
      var poster = imdb_json.image;
      GM_setClipboard(poster);
      alert('IMDB海报链接已经复制至粘贴板！！');
    }

    function getTMDBPoster(imdbId, apiKey) {
      GM_xmlhttpRequest({
        method: "GET",
        url: `https://api.themoviedb.org/3/find/${imdbId}?api_key=${apiKey}&external_source=imdb_id`,
        onload: function (response) {
          if (response.status === 200) {
            let data = JSON.parse(response.responseText);
            let results = (data.movie_results && data.movie_results.length > 0) ? data.movie_results : data.tv_results;
            if (results && results.length > 0) {
              let posterPath = results[0].poster_path;
              if (posterPath) {
                let posterURL = `https://image.tmdb.org/t/p/original${posterPath}`;
                GM_setClipboard(posterURL);
                alert(`TMDB海报链接已经复制至粘贴板！！`);
              } else {
                alert("TMDB 结果中缺少海报链接！");
              }
            } else {
              alert("未找到 TMDB 海报");
            }
          } else {
            alert("获取 TMDB 信息失败");
          }
        }
      });
    }

    function getPTPPoster(imdbId) {
      GM_xmlhttpRequest({
        method: "GET",
        url: `https://passthepopcorn.me/torrents.php?searchstr=${imdbId}&action=basic`,
        onload: function (response) {
          if (response.status === 200) {
            let parser = new DOMParser();
            let doc = parser.parseFromString(response.responseText, "text/html");
            let poster = doc.querySelector('.sidebar-cover-image')?.src;
            if (poster) {
              GM_setClipboard(poster);
              alert('PTP海报链接已经复制至粘贴板！！');
            } else {
              alert("未找到 PTP 海报");
            }
          } else {
            alert("获取 PTP 信息失败，请检查 Cookie 是否正确");
          }
        }
      });
    }

    function getLetterboxdPoster(imdbId) {
      var url = `https://letterboxd.com/imdb/${imdbId}/`;
      GM_xmlhttpRequest({
        method: "GET",
        url: url,
        onload: function (response) {
          const finalurl = response.finalUrl;
          if (finalurl == url) {
            alert("未在Letterboxd找到相关资源");
            return;
          }
          GM_xmlhttpRequest({
            method: "GET",
            url: finalurl,
            onload: function (response2) {
              if (response2.status === 200) {
                let parser = new DOMParser();
                let doc = parser.parseFromString(response2.responseText, "text/html");
                var info = $('script[type="application/ld+json"]', doc).text();
                info = info.replace(/\/\*.*\*\//g, '');
                info = JSON.parse(info);
                console.log(info)
                let poster = info.image.split('?')[0];
                if (poster) {
                  GM_setClipboard(poster.replace('230-0-345', '460-0-690'));
                  alert('BOXD海报链接已经复制至粘贴板！！');
                } else {
                  alert("未找到 Letterboxd 海报");
                }
              } else {
                alert("获取 Letterboxd 页面失败");
              }
            }
          });
        }
      });
    }

    function getMAZEPoster(imdbId) {
      GM_xmlhttpRequest({
        method: "GET",
        url: `https://api.tvmaze.com/lookup/shows?imdb=${imdbId}`,
        onload: function (response) {
          if (response.status === 200) {
            let data = JSON.parse(response.responseText);
            let posterPath = data.image.original;
            console.log(data)
            GM_setClipboard(posterPath);
            alert(`MAZE海报链接已经复制至粘贴板！！`);
          } else {
            alert("没有找到对应的电视剧！！");
          }
        }
      });
    }

    raw_info = stringToDict(site_url.split(separator)[1]); //将弄回来的字符串转成字典
    if (raw_info.url) {
      var imdbid = raw_info.url.match(/tt\d+/)[0];
      $('body').append(`<div id="navbarContainer" title="由于豆瓣链接经常失效，此处根据IMDB编号提供几个海报替换查询按钮。">
                <div class="title">其他海报</div>
                <a href="#" id="link1">IMDb</a>
                <a href="#" id="link2"  title="需要填写TMDB的APIKEY。">TMDB</a>
                <a href="#" id="link3">BOXD</a>
                <a href="#" id="link4" title="需要有皮的账号。">PTP</a>
                <a href="#" id="link5" title="主要是海外电视剧。">MAZE</a>
            </div>`);
      $("#link1").click(function (event) {
        event.preventDefault();
        getIMDbPoster(imdbid);
      });
      $("#link2").click(function (event) {
        event.preventDefault();
        getTMDBPoster(imdbid, used_tmdb_key);
      });
      $("#link3").click(function (event) {
        event.preventDefault();
        getLetterboxdPoster(imdbid, used_tmdb_key);
      });
      $("#link4").click(function (event) {
        event.preventDefault();
        getPTPPoster(imdbid);
      });
      $("#link5").click(function (event) {
        event.preventDefault();
        getMAZEPoster(imdbid);
      });
    }
    if ($('td:contains(你没有发布种子的权限)').length || $('p:contains("对不起你暂没有发布种子的权限")').length || $('td:contains(请提交候选)').length || $('a[href="?add_offer=1"]').length || $('h1:contains("候选区")').length) {
