/**
 * @module 17_forward_site_filling1
 * @description forward_site blocks: CMCT, PTer, HDSky, OpenCD, OPS...
 * @lines 14314-16000
 * 
 * Extracted from auto_feed.user.js
 * DO NOT EDIT - Auto-generated by split_modules.py
 */

      if (forward_site == "CMCT") {
        upload_site = upload_site.replace('upload.php', 'upload.php?offer=1');
      } else if (forward_site == 'HUDBT') {
        upload_site = upload_site.replace('offers.php', 'offers.php?add_offer=1');
      } else if (forward_site == "TTG") {
        upload_site = upload_site.replace('viewoffers.php', 'offer.php');
      } else {
        upload_site = upload_site.replace('upload.php', 'offers.php?add_offer=1');
      }
      location.href = upload_site + separator + encodeURI(dictToString(raw_info));
      return;
    }
    console.log(raw_info);
    raw_info.descr = raw_info.descr.replace(/ /g, ' ');
    raw_info.full_mediainfo = raw_info.full_mediainfo.replace(/ /g, ' ');
    if (raw_info.origin_site == 'OurBits') {
      raw_info.descr = raw_info.descr.replace(/ /g, ' ');
    }
    raw_info.descr = raw_info.descr.replace(/\[b\]\[\/b\]/g, '')
    var search_name = get_search_name(raw_info.name);

    raw_info = fill_raw_info(raw_info, forward_site);

    if (raw_info.origin_site == 'MTeam') {
      raw_info.descr = raw_info.descr.replace(/░/g, '');
    }
    if (raw_info.name.match(/Audies$|-ADE$|-ADWeb$/i) && forward_site == 'PTT') {
      return;
    }
    if (raw_info.descr.match(/img1.doubanio.com/)) {
      raw_info.descr = raw_info.descr.replace(/img1.doubanio.com/, 'img9.doubanio.com');
    }

    if (raw_info.codec_sel == 'H264' && raw_info.name.match(/x264/)) {
      raw_info.codec_sel = 'X264';
    }

    if (raw_info.medium_sel == 'Encode' && raw_info.name.match(/web/i)) {
      raw_info.medium_sel = 'WEB-DL';
    }

    //副标题加上原盘版本信息
    if (check_descr(raw_info.descr) && !raw_info.name.match(/(diy|@|remux)/i) && judge_forward_site_in_domestic(forward_site)) {
      if (blurayVersion(raw_info.name) && raw_info.small_descr.indexOf(blurayVersion(raw_info.name).replace(/【|】/g, '')) < 0) {
        raw_info.small_descr = raw_info.small_descr + '    ' + blurayVersion(raw_info.name);
      }
    }
    if (raw_info.golden_torrent == "true") {
      raw_info.small_descr = raw_info.small_descr + ' | ' + 'PTP Golden Popcorn';
    }

    //对类别做出简单修正
    if (raw_info.descr.match(/类[\s\S]{0,5}别[\s\S]{0,30}纪录片/i)) {
      raw_info.type = '纪录';
    } else if (raw_info.descr.match(/类[\s\S]{0,5}别[\s\S]{0,30}动画/i)) {
      if (forward_site == 'PTer') {
        raw_info.type = '动漫';
      } else if (raw_info.type == '电影' && ['HUDBT', 'MTeam', 'TLFbits', 'PuTao', 'TJUPT', 'NanYang', 'BYR', 'TTG'].indexOf(forward_site) < 0) {
        raw_info.type = '动漫';
      }
    }

    if (forward_site == "HDSky") {
      var tmp_small_descr = raw_info.small_descr.split('| 类别：');
      if (tmp_small_descr.length == 1) {
        tmp_small_descr = tmp_small_descr[0];
      } else {
        var plus_info = tmp_small_descr[1].replace('【', '[').replace('】', ']');
        plus_info = plus_info.match(/\[.*\]/) ? plus_info.match(/\[.*\]/)[0] : '';
        tmp_small_descr = tmp_small_descr[0] + plus_info;
      }
      raw_info.small_descr = tmp_small_descr.replace(/([\s]\/)/ig, '/');
      raw_info.small_descr = raw_info.small_descr.replace(/(\/[\s])/ig, '/');
    }

    if (forward_site == 'HDSky' && ['纪录', '动漫'].indexOf(raw_info.type) > -1) {
      raw_info.small_descr = (raw_info.type == "纪录" ? `[${raw_info.type}]` : '[动画]') + ' ' + raw_info.small_descr;
    }

    if (forward_site == 'HDSky' && ['剧集'].indexOf(raw_info.type) > -1) {
      if (raw_info.name.match(/s(\d+)/i)) {
        if (raw_info.name.match(/s?(\d+)-s?(\d+)/i)) {
          [s1, s2] = raw_info.name.match(/ep?(\d+)-ep?(\d+)/i).slice(1, 3);
          raw_info.small_descr = raw_info.small_descr + ` [第${parseInt(s1)}-${parseInt(s2)}季]`;
        } else {
          var season = raw_info.name.match(/s(\d+)/i)[1];
          raw_info.small_descr = raw_info.small_descr + ` [第${parseInt(season)}季]`;
          if (!raw_info.name.match(/e(p)?(\d+)/i) && raw_info.descr.match(/◎集.*数.*?(\d+)/)) {
            var number = raw_info.descr.match(/◎集.*数.*?(\d+)/)[1];
            raw_info.small_descr = raw_info.small_descr + `[${parseInt(number)}集全]`;
          }
        }
      }
      if (raw_info.name.match(/e(p)?(\d+)/i)) {
        if (raw_info.name.match(/ep?(\d+)-ep?(\d+)/i)) {
          [ep1, ep2] = raw_info.name.match(/ep?(\d+)-ep?(\d+)/i).slice(1, 3);
          raw_info.small_descr = raw_info.small_descr + ` [第${parseInt(ep1)}-${parseInt(ep2)}集]`;
        } else {
          var episode = raw_info.name.match(/e(p)?(\d+)/i).pop();
          raw_info.small_descr = raw_info.small_descr + ` [第${parseInt(episode)}集]`;
        }
      }
    }

    if (['RED', 'jpop', 'lztr', 'DICMusic', 'OPS', 'SugoiMusic'].indexOf(raw_info.origin_site) > -1) {
      raw_info.name = raw_info.name.replace(/\*/g, '');
      if (raw_info.tracklist) {
        raw_info.tracklist = '[quote=Tracklist]' + raw_info.tracklist + '[/quote]';
      } else {
        raw_info.tracklist = '';
      }
      if (raw_info.log_info) {
        raw_info.log_info = '\n\n[hide]' + raw_info.log_info + '[/hide]\n\n';
      } else {
        raw_info.log_info = '';
      }
      raw_info.descr = raw_info.descr + raw_info.log_info + raw_info.tracklist;
    }

    raw_info.descr = raw_info.descr.replace(/\%2F/g, '/');
    raw_info.descr = raw_info.descr.replace(/\%3A/g, ':');

    //-------------------------------------数据填充到指定位置--------------------------------------
    if (forward_site == 'OpenCD') {

      var info = {
        "大陆": "1", "欧美": "2", "港台": "3", "日韩": "4", "其它地区": "5", "流行(Pop)": "6",
        "发烧(HiFi)": "7", "汽车(garage)": "8", "古典(Classical)": "9", "民族(National)": "10",
        "摇滚(rock)": "11", "原声(OST)": "12", "民间(Folk)": "13", "乡村(Country)": "14",
        "天籁(Soul)": "15", "新世纪(NewAge)": "16", "蓝调(Blues)": "17", "爵士(Jazz)": "18",
        "金属(Metal)": "19", "朋克(Punk)": "20", "电子(Electronic)": "21", "儿童(Children's)": "22",
        "宗教(Religion)": "23", "雷鬼(Reggae)": "24", "贝斯(Drum Bass)": "25", "说唱(Rap)": "26", "音乐剧(musical)": "27"
      };
      var type_dict = {
        "electronic": "电子(Electronic)",
        "blues": "蓝调(Blues)",
        "blues": "蓝调(Blues)", "rhythm.and.blues": "蓝调(Blues)",
        "classical": "古典(Classical)",
        "country": "乡村(Country)",
        "folk": "民间(Folk)",
        "drum.and.bass": "贝斯(Drum Bass)",
        "jazz": "爵士(Jazz)",
        "new.age": "新世纪(NewAge)",
        "soul": "天籁(Soul)",
        "modern.classical": "古典(Classical)",
        "garage.house": "汽车(garage)", "garage.rock": "汽车(garage)",
        "reggae": "雷鬼(Reggae)",
        "hip.hop": "嘻哈(Hip Hop)",
        "instrumental": "器乐(Instrumental)",
        "indie": "独立(Indie)",
        "japanese": "日韩", "korean": "日韩",
        "chinese": "大陆", "thai": "其他地区",
        "dance": "舞曲(Dance)", "english": "欧美",
        "soundtrack": "原声(OST)",
        'score.ost': "原声(OST)",
        "america": "欧美",
        "OST": "原声(OST)",
      }
      console.log(raw_info)
      raw_info.name = raw_info.name.trim();
      if (raw_info.origin_site == 'OPS') {
        raw_info.name = raw_info.name.replace(/–/g, '-');
      }
      var info_text = raw_info.name.split('*');
      var author_name = info_text[0];
      var music_name = '待填';
      if (author_name.split('-').length > 1) {
        music_name = author_name.split('-').pop().trim();
      }

      var year = '';
      if (raw_info.name.match(/(19|20)\d+/)) {
        year = raw_info.name.match(/(19|20)\d+/)[0];
        music_name = music_name.split(year)[0].trim();
      }
      var author = raw_info.name.split(music_name)[0].replace(/-( *)?$/, '').trim();

      if (raw_info.json !== undefined) {
        raw_info.json = JSON.parse(raw_info.json);
        console.log(raw_info.json);
        var group = raw_info.json['response']['group'];
        var torrent = raw_info.json['response']['torrent'];
        if (group.artists) {
          raw_info.music_author = Array.from(group.artists.map((e) => {
            return e.name;
          })).join(' & ');
        }
        raw_info.music_name = group.name.replace(/&quot;/g, '');
        music_name = group.name.replace(/&quot;/g, '');
        if (group.tags) {
          raw_info.music_type = group.tags.join(',');
        }
        raw_info.small_descr = torrent['format'] + ' / ' + torrent['encoding'] + ' / ' + torrent['media'];
        if (torrent.logScore !== undefined && torrent.logScore > 0) {
          raw_info.small_descr += ` / Log (${torrent.logScore}%)`
        }
        if (torrent.hasCue !== undefined && torrent.hasCue) {
          raw_info.small_descr += ` / Cue`
        }
      }
      $('#yadg_input').wait(function () {
        $('#yadg_input').val(music_name);
        $('#yadg_input').parentsUntil('table').last().css({ "margin-left": "0.5%", "width": "99%" });
        $('#yadg_input').parentsUntil('table').find('tr').map((index, e) => {
          $(e).find('td:first').css({ "border-left": "none" });
          $(e).find('td:last').css({ "border-right": "none" });
        });
      });
      if (['RED', 'jpop', 'lztr', 'DICMusic', 'OPS', 'SugoiMusic'].indexOf(raw_info.origin_site) > -1) {
        if (raw_info.origin_site == 'RED') {
          try {
            raw_info.music_type = raw_info.descr.match(/标签： (.*)/)[1].split(' | ');
            raw_info.descr = raw_info.descr.replace(/标签： (.*)/, '');
          } catch (err) { }
        } else {
          raw_info.music_type = raw_info.music_type.split(',');
        }
        try {
          var music_type = [];
          raw_info.music_type.map((item) => {
            if (item.match(/pop/) && music_type.indexOf("流行(Pop)") < 0) {
              music_type.push("流行(Pop)");
            }
            if (item.match(/rock/) && music_type.indexOf("摇滚(rock)") < 0) {
              music_type.push("摇滚(rock)");
            }
            if (item.match(/punk/) && music_type.indexOf("朋克(Punk)") < 0) {
              music_type.push("朋克(Punk)");
            }
            if (item.match(/Metal/i) && music_type.indexOf("金属(Metal)") < 0) {
              music_type.push("金属(Metal)");
            }
            if (type_dict.hasOwnProperty(item) && music_type.indexOf(type_dict[item]) < 0) {
              music_type.push(type_dict[item]);
            }
            if (item.match(/alternative/) && music_type.indexOf("另类(Alternative)") < 0) {
              music_type.push("另类(Alternative)");
            }
            if (item.match(/world.music/) && music_type.indexOf("世界音乐(World)") < 0) {
              music_type.push("世界音乐(World)");
            }
          });
          raw_info.music_type = music_type;
        } catch (err) { }

        var name_dict = {
          "RED": 'Redacted', 'OPS': 'Orpheus', 'jpop': 'Jpopsuki', 'DICMusic': 'DICMusic', 'lztr': 'LzTr', 'SugoiMusic': 'SugoiMusic'
        }
        $('#frname').val(name_dict[raw_info.origin_site]);
      }
      if (raw_info.origin_site == 'jpop') {
        raw_info.name = raw_info.name.replace(/\d{4} \d{2} \d{2}/, function (data) { return data.split(' ')[0]; });
      }

      if (forward_site == 'OpenCD') {
        raw_info.music_media += raw_info.small_descr + (raw_info.file_list ? raw_info.file_list : '');
        raw_info.descr = raw_info.descr.split(/\[b\]\[color=green\]\[size=3\]本站提供的所有影视/)[0].trim();
        raw_info.descr = raw_info.descr.replace(/ \n \n/g, ' \n');
        raw_info.descr = raw_info.descr.replace(raw_info.tracklist, '');
        raw_info.name = raw_info.name.replace(/(Album|Single)$/, '');
        $('#artist').val(raw_info.music_author || author); $('#year').val(year); $('#browsecat').val(408); $('#resource_name').val(raw_info.music_name || music_name); $('#share_rule').val(3);
        $(`#name`).parent().parent().after(`<tr>
                    <td class="rowhead nowrap rowtitle">豆瓣搜索:</td>
                    <td><input id="douban"/></td>
                    <td><input id="douban_button" type="button" value="搜索"></td>
                    </tr>`);
        $('#douban').val(music_name);
        $('#douban_button').click(() => {
          window.open(`https://search.douban.com/music/subject_search?search_text=${$('#douban').val()}&cat=1003`, '_blank');
        })
        try {
          var poster = raw_info.descr.match(/\[img\](.*?)\[\/img\]/)[1].trim();
          $('#cover').after(`<img style="max-width:200px; margin-top:5px;" src=${poster} />`);
          setTimeout(function () {
            addPoster(poster, forward_site);
          }, 2000);
        } catch (err) {
          console.log(err)
        }
        raw_info.descr = raw_info.descr.replace(/^\[img\].*?\[\/img\]([\n\s]*)/, '');

        function add_log(name, log_txt, index) {
          log_txt = log_txt.replace(/^\n{0,5}\[hide\]/, '').replace(/\[\/hide\]/, '').replace(/^Score.*?\(max 100\)/, '').trim();
          var fileData = new Blob([log_txt], { type: "text/plain" });
          var fileName = `${name}-${index + 1}.log`;
          console.log(log_txt)
          var fileInput = $('input[name*=nfo1]:last')[0];
          let container = new DataTransfer();
          const files = new window.File([fileData], fileName, { type: 'text/plain' });
          container.items.add(files);
          fileInput.files = container.files;
        }

        if (raw_info.log_info !== '' && raw_info.log_info) {
          raw_info.log_info = raw_info.log_info.split('==logs==');
          add_log(raw_info.name, raw_info.log_info[0], 0);
          if (raw_info.log_info.length > 1) {
            for (var index = 1; index < raw_info.log_info.length; index++) {
              $('#nfoadd').click();
              add_log(raw_info.name, raw_info.log_info[index], index);
            }
          }
        }

        if (raw_info.music_media) {
          raw_info.music_media += raw_info.edition_info ? raw_info.edition_info : '';
          var media_selected = false;
          var standard_selected = false;
          $('#standard>option').map((index, e) => {
            if (!standard_selected && (raw_info.music_media + raw_info.small_descr).toUpperCase().match(e.innerText)) {
              $(`#standard>option:eq(${index})`).attr('selected', true);
              standard_selected = true;
            }
          });

          $('#medium>option').map((index, e) => {
            if (!media_selected && (raw_info.music_media + raw_info.small_descr).toUpperCase().match(e.innerText.toUpperCase())) {
              $(`#medium>option:eq(${index})`).attr('selected', true);
              media_selected = true;
            }
          });
          if (raw_info.music_media.match(/整轨/)) {
            $('#audio_mode').val('single');
          } else if (raw_info.music_media.match(/分轨/) || $('#standard').val() == 4) {
            $('#audio_mode').val('multi');
          } else {
            $('#audio_mode').val('none');
          }

          if ($('#medium').val() == "1") {
            var dict_cd = { "LPCD": "4", "HDCD": "5", "SACD": "6", "SRCD": "7", "K2CD": "8", "HQCD": "16", "XRCD": "17", "SHM-CD": "18" };
            for (key in dict_cd) {
              var reg = new RegExp(key, 'i');
              if (raw_info.music_media.match(reg)) {
                $('#medium').val(dict_cd[key]);
              }
            }
          }
        }
        $('#team').val('5');
        var source_selected = false;
        if (['RED', 'jpop', 'lztr', 'DICMusic', 'OPS', 'SugoiMusic'].indexOf(raw_info.origin_site) > -1) {
          $('a.tag:contains("大陆")').wait(function () {
            raw_info.music_type.map(item => {
              var source = $(`a.tag:contains(${item})`);
              if (item == "贝斯(Drum Bass)") { source = $(`a.tag[value="25"]`); }
              if (source.length) {
                addTag(source);
              }
              if (!source_selected) {
                if (item == '摇滚(rock)') {
                  item = '摇滚(Rock)';
                }
                if ($(`#source>option:contains(${item})`).length) {
                  $(`#source>option:contains(${item})`).attr('selected', true);
                  source_selected = true;
                }
              }
            })
          });
        }
        try {
          if (raw_info.tracklist) {
            raw_info.tracklist = raw_info.tracklist.replace(/\[.*?\]/g, function (data) {
              if (data.match(/url/)) {
                return data;
              } else {
                return '';
              }
            }).trim();
            $('textarea[name="track_list"]').val(raw_info.tracklist.replace(/\.(flac|wav)/g, ''));
            $('#descr').wait(function () {
              $('#descr').val(raw_info.tracklist);
              $('#descr').parent().append(`<a style="text-decoration:none;" href="#" id="file2descr"><font color="red">从简介导入</font></a>`);
              $('#file2descr').click((e) => {
                e.preventDefault();
                $('#descr').val(raw_info.descr);
              });
            });
          } else {
            var track_list = raw_info.descr.match(/0?1(\.|\))[\s\S]*\d+.*(\n|$)/)[0];
            $('textarea[name="track_list"]').val(track_list);
          }
        } catch (err) { }
        try {
          if (raw_info.musicspectrum !== null) {
            $('#spectrogram').val(raw_info.musicspectrum);
          }
        } catch (err) { }
        try {
          if (raw_info.file_list) {
            $('textarea[name=track_list]').parent().append(`<a style="text-decoration:none;" href="#" id="file2tracklist"><font color="red">从文件列表导入</font></a>`);
            $('#file2tracklist').click((e) => {
              e.preventDefault();
              $('textarea[name=track_list]').val(`[b]Tracklist[/b]\n` + raw_info.file_list.replace(/\.flac|\.wav/g, ''));
            });
          }
        } catch (err) { }
        document.getElementById('audio_mode').dispatchEvent(evt);
      } else {
        raw_info.descr = raw_info.descr.replace(/^\[img\].*?\[\/img\]([\n\s]*)/, '');
        $('input[name="artists[]"]').val(author);
        $('input[name="title"]').val(music_name);
        $('input[name="year"]').val(year);
        $('input[name=title]').after(`<input type="button" value="搜索" id="search"/>`);
        $('#search').click(() => {
          var discogs_url = `https://www.discogs.com/search?q=${music_name}&type=all`;
          window.open(discogs_url, "_blank");
        });
        if (raw_info.edition_info) {
          $('input[name=year]').parent().parent().after(`<tr><td class="nowrap noboder right"><strong>辅助信息</strong></td><td class="nowrap noboder"><input value="${raw_info.edition_info.trim()}" size="60"/></td></tr>`);
          $('input[name=remaster_year]').val(raw_info.edition_info.match(/\d{4}/)[0]);
        }
        if (raw_info.tracklist.match(/https:\/\/www.discogs.com\/release\/.*/)) {
          $('input[name=discogs_url]').val(raw_info.tracklist.match(/https:\/\/www.discogs.com\/release\/.*/)[0]);
        }
      }
    } else if (raw_info.origin_site == 'OpenCD') {
      raw_info.descr += '\n\n' + '[quote]' + raw_info.tracklist + '[/quote]'
    }

    if (forward_site == 'OPS') {
      var announce = $('a:contains(已隐藏你的个人)').attr('href');
      if (forward_site == 'OPS') {
        announce = $('input[value*="announce"]').val();
        if (raw_info.releasetype !== undefined) {
          switch (raw_info.releasetype) {
            case 'Single': $('#releasetype').val(9); break;
            case 'Album': $('#releasetype').val(1); break;
            case 'PV': $('#releasetype').val(11); break;
            case 'DVD': $('#releasetype').val(21); break;
            case 'TV-Music': $('#releasetype').val(21); break;
            case 'TV-Variety': $('#releasetype').val(21); break;
            case 'TV-Drama': $('#releasetype').val(21); break;
            case 'Fansubs': $('#releasetype').val(21); break;
            case 'Pictures': $('#releasetype').val(21); break;
          }
        }
        try { if (!$('#tags').val()) { $('#tags').val(raw_info.music_type.replace(/,/g, ', ')) } } catch (err) { }
      }
      addTorrent(raw_info.torrent_url, raw_info.torrent_name, forward_site, announce);
      function add_extra_info() {
        $('#artist_tr').before(`<tr class="section_tr"><td class="label">辅助信息:</td><td>${raw_info.name}<br>${raw_info.edition_info}<br>${raw_info.small_descr}</td></tr>`)
        raw_info.name = raw_info.name.trim();
        if (raw_info.origin_site == 'OPS') {
          raw_info.name = raw_info.name.replace(/–/g, '-');
        }
        var info_text = raw_info.name.split('*');
        var author_name = info_text[0];
        var music_name = '待填';
        if (author_name.split('-').length > 1) {
          music_name = author_name.split('-').pop().trim();
        }

        try {
          raw_info.music_author.split(' & ').forEach((item, index) => {
            if (index == $('input[name="artists[]"]').length) {
              AddArtistField();
            }
            if (item) {
              $(`#artist_${index}`).val(item);
            }
          });
        } catch (Err) { }
        raw_info.descr = raw_info.descr.replace(/\[quote=Tracklist\]/, 'Tracklist\n').replace(/\[\/quote\]/, '');

        var year = '';
        if (raw_info.name.match(/(19|20)\d+/)) {
          year = raw_info.name.match(/(19|20)\d+/)[0];
          music_name = music_name.split(year)[0].trim();
        }
        var author = raw_info.name.split(music_name)[0].replace(/-( *)?$/, '').trim();
        $('#yadg_input').wait(function () {
          $('#yadg_input').val(music_name);
        });
        if (!$('#artist').val()) { $('#artist').val(raw_info.music_author || author); }
        if (!$('#year').val()) { $('#year').val(year); }
        if (!$('#title').val()) { $('#title').val(raw_info.music_name || music_name); }
        if (raw_info.edition_info && raw_info.edition_info.match(/(19|20)\d{2}/)) {
          if (!$('#remaster_year').val()) { $('#remaster_year').val(raw_info.edition_info.match(/(19|20)\d{2}/)[0]); }
        }
        var media_selected = false;
        var standard_selected = false;
        if ($('#format').val() == '---' || !$('#format').val()) {
          $('#format>option').map((index, e) => {
            if (!standard_selected && (raw_info.music_media + raw_info.small_descr + raw_info.edition_info).toUpperCase().match(e.innerText)) {
              $(`#format>option:eq(${index})`).attr('selected', true);
              standard_selected = true;
            }
          });
        }
        if ($('#media').val() == '---' || !$('#media').val()) {
          $('#media>option').map((index, e) => {
            if (!media_selected && (raw_info.music_media + raw_info.small_descr + raw_info.edition_info).toUpperCase().match(e.innerText.toUpperCase())) {
              $(`#media>option:eq(${index})`).attr('selected', true);
              media_selected = true;
            }
          });
        }

        if ($('#bitrate').val() == '---' || !$('#bitrate').val()) {
          if ((raw_info.small_descr).match(/24bit Lossless/)) {
            $('#bitrate').val('24bit Lossless');
          } else if ((raw_info.small_descr).match(/Lossless/)) {
            $('#bitrate').val('Lossless');
          } else if (raw_info.small_descr.match(/320|256|192|160|128|96|64/)) {
            $('#bitrate').val(raw_info.small_descr.match(/320|256|192|160|128|96|64/)[0]);
          }
        }
        var poster = raw_info.descr.match(/\[img\](.*?)\[\/img\]/)[1].trim();
        if (!$('#image').val()) { $('#image').val(poster); }
      }

      if (raw_info.json !== undefined) {
        var data = JSON.parse(raw_info.json);
        console.log(data)
        var group = data['response']['group'];
        var torrent = data['response']['torrent'];

        var categories_mapping = {
          'Music': 0,
          'Applications': 1,
          'E-Books': 2,
          'Audiobooks': 3,
          'E-Learning Videos': 4,
          'Comedy': 5,
          'Comics': 6
        };
        var index = 0;
        if (categories_mapping.hasOwnProperty(group['categoryName'])) {
          index = categories_mapping[group['categoryName']];
        }
        if (torrent.format) {
          raw_info.small_descr += torrent.format;
        }
        var categories = $('#categories');
        if (!group['categoryName']) {
          group['categoryName'] = 'Music';
        }
        categories.val(index).triggerHandler('change');
        WaitForCategory(function () {
          fillMusicForm(group, torrent);
          add_extra_info();
          setTimeout(function () {
            if (group.wikiBody.match(/\<(br|span).*?\>/)) {
              var tmp_descr = raw_info.descr;
              raw_info.descr = '';
              var wikiBody = $(`<div>${group.wikiBody}</div>`);
              wikiBody = walkDOM(wikiBody[0]);
              $('#album_desc').val(wikiBody);
              raw_info.descr = tmp_descr;
            }
            $('#release_desc').val(torrent.description.replace(/&emsp;/g, ' '));
            if (torrent.encoding == "24bit Lossless") {
              $('#bitrate').val('24bit Lossless');
            }
            if (group['tags']) {
              $('#tags').val(Object.values(group['tags']).filter(f => f != "").join(', '));
            }
          }, 2000);
        });
      } else {
        add_extra_info();
      }
    }

    if (forward_site == 'RED') {
      var announce = $('input[value*="announce"]').val();
      addTorrent(raw_info.torrent_url, raw_info.torrent_name, forward_site, announce);
      var JSONReleaseTypes = {
        '1': 'Album',
        '3': 'Soundtrack',
        '5': 'EP',
        '6': 'Anthology',
        '7': 'Compilation',
        '9': 'Single',
        '11': 'Live album',
        '13': 'Remix',
        '14': 'Bootleg',
        '15': 'Interview',
        '16': 'Mixtape',
        '17': 'Sampler',
        '21': 'Unknown',
        '22': 'Demo',
        '23': 'DJ Mix',
        '24': 'Concert Recording'
      };
      function fillForm(releaseJSON) {
        var categories = ['Music', 'Applications', 'E-Books', 'Audiobooks', 'E-Learning Videos', 'Comedy', 'Comics'];
        var category = document.getElementById('categories');
        var categoryJSON = parseInt(releaseJSON.response.group.categoryId);
        var categoryNameJSON = releaseJSON.response.group.categoryName;
        var categoryIndex = categories.indexOf(categoryNameJSON);

        if (categoryIndex > -1) {
          if (categoryIndex != 0) {
            alert('Currently only Music category torrents are supported. Aborting...');
            return;
          } else {
            category.selectedIndex = categories.indexOf(categoryNameJSON);
          }
        } else {
          alert('The category name indicated in the JSON (' + categoryNameJSON + ') is not one of the available category types! Aborting...');
          return;
        }

        switch (categoryIndex) {
          case 0:
            var artists = [];
            var artistRoles = [
              { 'name': 'artists', 'index': 0 },
              { 'name': 'with', 'index': 1 },
              { 'name': 'composers', 'index': 2 },
              { 'name': 'conductor', 'index': 3 },
              { 'name': 'dj', 'index': 4 },
              { 'name': 'remixedBy', 'index': 5 },
              { 'name': 'producer', 'index': 6 },
            ];
            var artistsJSON = releaseJSON.response.group.musicInfo;

            for (var i = 0, len = artistRoles.length; i < len; i++) {
              if (artistsJSON[artistRoles[i].name].length == 0) continue;
              for (var j = 0, lenj = artistsJSON[artistRoles[i].name].length; j < lenj; j++) {
                artists.push({ 'name': artistsJSON[artistRoles[i].name][j].name, 'index': artistRoles[i].index });
              }
            }

            if (artists.length > 0) {
              var artistInputs = [];
              artistInputs.length = artists.length;
              for (i = 0, len = artists.length; i < len; i++) {
                if (i > 0) window.eval('AddArtistField();');
                artistInputs[i] = document.getElementById('artist' + (i > 0 ? '_' + i : ''));
                artistInputs[i].value = artists[i].name;
                var roles = document.querySelectorAll('td#artistfields > #importance');
                roles[i].selectedIndex = artists[i].index;
              }
            } else {
              alert('No artists are included in the JSON!');
            }

            var albumTitle = document.getElementById('title');
            var albumTitleJSON = releaseJSON.response.group.name;

            if (albumTitleJSON != '') {
              albumTitle.value = albumTitleJSON;
            } else {
              alert('No album title is included in the JSON!');
            }

            var initialYear = document.getElementById('year');
            var initialYearJSON = releaseJSON.response.group.year;

            if (initialYearJSON != '') {
              initialYear.value = initialYearJSON;
            } else {
              alert('No initial year is included in the JSON!');
            }

            var releaseType = document.getElementById('releasetype');
            var releaseTypes = [];
            for (i = 0, len = releaseType.options.length; i < len; i++) {
              releaseTypes.push(releaseType.options[i].textContent.toLowerCase());
            }

            try {
              var releaseTypeIndexJSON = parseInt(releaseJSON.response.group.releaseType);
              var releaseTypeNameJSON = JSONReleaseTypes[releaseTypeIndexJSON];
              var releaseTypeIndex = releaseTypes.indexOf(releaseTypeNameJSON.toLowerCase());

              if (releaseTypeIndex > -1) {
                releaseType.selectedIndex = releaseTypeIndex;
              } else {
                alert('The release type indicated in the JSON (' + releaseTypeNameJSON + ' [' + releaseTypeIndexJSON + ']) ' +
                  'is not one of the available release types!\n\nManually select the appropriate release type.');
              }
            } catch (err) { }

            var editionYear = document.getElementById('remaster_year');
            var editionTitle = document.getElementById('remaster_title');
            var editionLabel = document.getElementById('remaster_record_label');
            var editionCatNo = document.getElementById('remaster_catalogue_number');
            var edition = releaseJSON.response.torrent.remastered;

            if (edition) {
              var editionYearJSON = releaseJSON.response.torrent.remasterYear;
              var editionTitleJSON = releaseJSON.response.torrent.remasterTitle;
              var editionLabelJSON = releaseJSON.response.torrent.remasterRecordLabel;
              var editionCatNoJSON = releaseJSON.response.torrent.remasterCatalogueNumber;
            } else {
              editionYearJSON = initialYearJSON
              editionTitleJSON = '';
              editionLabelJSON = releaseJSON.response.group.recordLabel;
              editionCatNoJSON = releaseJSON.response.group.catalogueNumber;
            }

            if (editionYearJSON == '') {
              alert('No edition year is included in the JSON!');
            }

            editionYear.value = editionYearJSON;
            editionTitle.value = editionTitleJSON;
            editionLabel.value = editionLabelJSON;
            editionCatNo.value = editionCatNoJSON;

            var scene = document.getElementById('scene');
            var sceneJSON = releaseJSON.response.torrent.scene;
            if (sceneJSON) scene.checked = true;

            var format = document.getElementById('format');
            var formats = [];
            for (i = 0, len = format.options.length; i < len; i++) {
              formats.push(format.options[i].textContent.toLowerCase());
            }

            var formatJSON = releaseJSON.response.torrent.format;
            var formatIndex = formats.indexOf(formatJSON.toLowerCase());

            if (formatIndex > -1) {
              format.selectedIndex = formatIndex;
            } else {
              alert('The format indicated in the JSON (' + formatJSON + ') ' +
                'is not one of the available formats!\n\nManually select the appropriate formats.');
            }

            var bitrate = document.getElementById('bitrate');
            var bitrates = [];
            for (i = 0, len = bitrate.options.length; i < len; i++) {
              bitrates.push(bitrate.options[i].textContent.toLowerCase());
            }
            var otherBitrate = document.getElementById('other_bitrate');
            var otherBitrateVBR = document.getElementById('vbr');

            var bitrateJSON = releaseJSON.response.torrent.encoding;
            var bitrateIndex = bitrates.indexOf(bitrateJSON.toLowerCase());

            if (bitrateIndex > -1) {
              bitrate.selectedIndex = bitrateIndex;
            } else {
              bitrate.selectedIndex = bitrates.indexOf('other');
              document.getElementById('other_bitrate_span').classList.remove('hidden');
              otherBitrate.value = bitrateJSON.replace(/ \(VBR\)$/i, '');
              otherBitrateVBR.checked = /.+ \(VBR\)$/i.test(bitrateJSON);
            }

            var media = document.getElementById('media');
            var medias = [];
            for (i = 0, len = media.options.length; i < len; i++) {
              medias.push(media.options[i].textContent.toLowerCase());
            }

            var mediaJSON = releaseJSON.response.torrent.media;
            var mediaIndex = medias.indexOf(mediaJSON.toLowerCase());

            if (mediaIndex > -1) {
              media.selectedIndex = mediaIndex;
            } else {
              alert('The media indicated in the JSON (' + mediaJSON + ') ' +
                'is not one of the available media!\n\nManually select the appropriate media.');
            }

            if (formats[formatIndex] == 'flac' && bitrates[bitrateIndex] == 'lossless' && medias[mediaIndex] == 'cd') {
              var hasLogJSON = releaseJSON.response.torrent.hasLog;
              var logs = document.getElementById('upload_logs');
              if (hasLogJSON) logs.classList.remove('hidden');
            }

            var tags = document.getElementById('tags');
            var tagsJSON = releaseJSON.response.group.tags;
            var tagList = '';

            if (tagsJSON.length > 0) {
              for (i = 0, len = tagsJSON.length; i < len; i++) {
                tagList += (i > 0 ? ', ' : '') + tagsJSON[i];
              }
            }

            tags.value = tagList;

            var image = document.getElementById('image');
            var imageJSON = releaseJSON.response.group.wikiImage;
            image.value = imageJSON;

            var albumDesc = document.getElementById('album_desc');
            var albumDescJSON = releaseJSON.response.group.wikiBody;

            if (albumDescJSON != '') {
              albumDescJSON = albumDescJSON.replace(/<br \/>/g, '');
              albumDescJSON = albumDescJSON.replace(/&amp;/g, '&');
              albumDescJSON = albumDescJSON.replace(/&lt;/g, '<');
              albumDescJSON = albumDescJSON.replace(/&gt;/g, '>');
              albumDescJSON = albumDescJSON.replace(/&quot;/g, '"');
              albumDescJSON = albumDescJSON.replace(/&apos;/g, '\'');
              albumDescJSON = albumDescJSON.replace(/&#39;/g, '\'');
              albumDescJSON = albumDescJSON.replace(/<a href="artist\.php\?artistname=.+?">(.+?)<\/a>/g, '[artist]$1[/artist]');
              albumDescJSON = albumDescJSON.replace(/<a href="user\.php\?action=search&amp;search=.+?">(.+?)<\/a>/g, '[user]$1[/user]');
              albumDescJSON = albumDescJSON.replace(/<a .+?>(https?:\/\/.+?)<\/a>/g, '$1');
              albumDescJSON = albumDescJSON.replace(/<a .*?href="(https?:\/\/.+?)".*?>(.+?)<\/a>/g, '[url=$1]$2[/url]');
              albumDescJSON = albumDescJSON.replace(/<span class="size(\d+)">(.+?)<\/span>/g, '[size=$1]$2[/size]');
              albumDescJSON = albumDescJSON.replace(/<span style="font-style: italic;">(.+?)<\/span>/g, '[i]$1[/i]');
              albumDescJSON = albumDescJSON.replace(/<ol class="postlist">([\s\S]+?)<\/ol>/g, function (data) {
                var data = data.replace(/<ol class="postlist">([\s\S]+?)<\/ol>/g, '$1');
                data = data.replace(/<li>(.+?)<\/li>/g, '[#]$1\n');
                return data;
              });
              albumDescJSON = albumDescJSON.replace(/<span style="text-decoration: underline;">(.+?)<\/span>/g, '[u]$1[/u]');
              albumDescJSON = albumDescJSON.replace(/<span style="text-decoration: line-through;">(.+?)<\/span>/g, '[s]$1[/s]');
              albumDescJSON = albumDescJSON.replace(/<span style="color: (.+?);">(.+?)<\/span>/g, '[color=$1]$2[/color]');
              albumDescJSON = albumDescJSON.replace(/<div style="text-align: (.+?);">(.+?)<\/div>/g, '[align=$1]$2[/align]');
              albumDescJSON = albumDescJSON.replace(
                /<img class="scale_image" onclick="lightbox.init\(this, \$\(this\)\.width\(\)\);" alt="(.+?)" src=".+?">/g,
                '[img]$1[/img]');
              albumDescJSON = albumDescJSON.replace(
                /<a href="#" onclick="QuoteJump\(event, '(\d+)'\); return false;"><strong class="quoteheader">(.+?)<\/strong> wrote: <\/a><blockquote>(.+?)<\/blockquote>/g,
                '[quote=$2|$1]$3[/quote]');
              albumDescJSON = albumDescJSON.replace(/<strong class="quoteheader">(.+?)<\/strong> wrote: <blockquote>(.+?)<\/blockquote>/g,
                '[quote=$1]$2[/quote]');
              albumDescJSON = albumDescJSON.replace(/<blockquote>([\s\S]+?)<\/blockquote>/g, function (data) {
                return `[quote]${data.replace(/<blockquote>([\s\S]+?)<\/blockquote>/, '$1').trim()}[/quote]`;
              });
              albumDescJSON = albumDescJSON.replace(/<strong>(.+?)<\/strong>: <a href="javascript:void\(0\);" onclick="BBCode\.spoiler\(this\);">Show<\/a><blockquote class="hidden spoiler">(.+?)<\/blockquote>/g,
                '[hide=$1]$2[/hide]');
              albumDescJSON = albumDescJSON.replace(/<strong>Hidden text<\/strong>: <a href="javascript:void\(0\);" onclick="BBCode\.spoiler\(this\);">Show<\/a><blockquote class="hidden spoiler">(.+?)<\/blockquote>/g,
                '[hide]$1[/hide]');
              albumDescJSON = albumDescJSON.replace(/<strong class="important_text">(.+?)<\/strong>/g, '[important]$1[/important]');
              albumDescJSON = albumDescJSON.replace(/<(pre|code)>(.+?)<\/\1>/g, '[$1]$2[/$1]');
              albumDescJSON = albumDescJSON.replace(/<(\/)?strong>/g, '[$1b]');

              // 没有匹配上的标签给它去掉
              albumDescJSON = albumDescJSON.replace(/<(\/)?span.*?>/g, '');

              albumDesc.value = albumDescJSON;
              albumDesc.style.height = '400px';
              document.querySelector('input.button_preview_0').click();
            } else {
              alert('No album description is included in the JSON!');
            }

            var relDesc = document.getElementById('release_desc');
            var relDescJSON = releaseJSON.response.torrent.description;
            var groupIDJSON = releaseJSON.response.group.id;
            var torrentIDJSON = releaseJSON.response.torrent.id;
            sourceWebsiteDomains = ['notwhat.cd', 'orpheus.network'];
            relDesc.value = relDescJSON;
            document.querySelector('input.button_preview_1').click();
            break;
        }
      }
      if (raw_info.json !== undefined) {
        var data = JSON.parse(raw_info.json);
        fillForm(data);
      }
    }

    var allinput = document.getElementsByTagName("input");
    if (forward_site == 'BLU' || forward_site == 'Audiences' || forward_site == 'Tik' || forward_site == 'Aither') {
      if (raw_info.descr.match(/Atmos/) && !raw_info.name.match(/atmos/i)) {
        raw_info.name = raw_info.name.replace(/(DDP|DD|AAC|HDMA|TrueHD|DTS.HD|DTS|PCM|FLAC)[ \.](.*?)(\d.\d)/i, '$1 $2 $3 Atmos').replace(/ +/g, ' ');
      }
    }
    if (forward_site == 'PTer' || forward_site == 'Dragon' || forward_site == 'QingWa' || forward_site == 'MTeam') {
      function re_build_name(channels, name) {
        var label = ''; label_str = '';
        if (channels == '1') {
          label = /1\.0/; label_str = '1.0';
        } else if (channels == '2') {
          label = /2\.0/; label_str = '2.0';
        } else if (channels == '6') {
          label = /5\.1/; label_str = '5.1';
        } else if (channels == '8') {
          label = /7\.1/; label_str = '7.1';
        }
        if (!name.match(label)) {
          name = name.replace(/(DDP|DD\+|AAC|FLAC|LPCM|TrueHD|DTS-HD.MA|DTS:X|DTS-HD.?HR|DTS|AC3)/i, `$1 ${label_str}`);
        }
        return name;
      }
      try {
        var channels = (raw_info.descr + raw_info.full_mediainfo).match(/Channel.*?(\d) channel/)[1];
        raw_info.name = re_build_name(channels, raw_info.name);
      } catch (err) {
        if (raw_info.descr.match(/(AUDIO.*CODEC.*?|音频.*?)(2\.0|1\.0|5\.1|7\.1)/i)) {
          channels = raw_info.descr.match(/(AUDIO.*CODEC.*?|音频.*?)(2\.0|1\.0|5\.1|7\.1)/i)[2];
          if (!raw_info.name.includes(channels)) {
            raw_info.name = raw_info.name.replace(/(DDP|AAC|FLAC|LPCM|TrueHD|DTS-HD.MA|DTS:X|DTS-HD.?HR|DTS|AC3|DD)/i, `$1 ${channels}`);
          }
        } else if (raw_info.descr.match(/\d channels/i)) {
          channels = raw_info.descr.match(/(\d) channels/i)[1];
          raw_info.name = re_build_name(channels, raw_info.name);
        }
      }
      if (raw_info.name.match(/WEB-DL/i)) {
        raw_info.name = raw_info.name.replace(/HEVC/, 'H.265').replace(/AVC/, 'H.264');
      }
      if (forward_site == 'MTeam') {
        raw_info.name = raw_info.name.replace(/AC3/, 'DD');
        raw_info.name = raw_info.name.replace(/DD\+/, 'DDP');
        try {
          var audio_number = 1;
          if (raw_info.descr.match(/DISC INFO:/)) {
            if (raw_info.descr.match(/Audio:[\s\S]{0,20}Codec/i)) {
              var audio_info = raw_info.descr.match(/Audio:[\s\S]{0,300}-----------([\s\S]*)/i)[1].split(/subtitles/i)[0].trim();
              audio_number = audio_info.split('\n').length;
            }
          } else {
            if (raw_info.descr.match(/Audio:(.*)/i)) {
              audio_number = raw_info.descr.match(/Audio:(.*)/ig).length;
            } else if (raw_info.descr.match(/Audio #\d/)) {
              audio_number = raw_info.descr.match(/Audio #\d/ig).length;
            }
          }
          if (audio_number > 1) {
            var audio_str = `${audio_number}Audio`;
            if (!raw_info.name.includes(audio_str)) {
              raw_info.name = raw_info.name.replace(/(DDP|AAC|FLAC|LPCM|TrueHD|DTS-HD.?MA|DTS:X|DTS-HD.?HR|DTS|DD) ?(\d\.\d)?/i, `$1 $2 ${audio_str}`);
            }
          }
        } catch (err) { }

      }
    }

    if (raw_info.origin_site == 'BHD' && raw_info.name.match(/-FraMeSToR/)) {
      raw_info.name = raw_info.name.replace(/(BluRay)(.*?)(AVC|VC-1|HEVC)(.*?)(REMUX)/i, '$1 $5 $3 $2').replace(/ +/g, ' ').replace(' -', '-');
    }
    for (i = 0; i < allinput.length; i++) {
      if (allinput[i].name == 'name' && forward_site != 'GPW' && forward_site != 'OpenCD') { //填充标题
        if (['NanYang', 'CMCT', 'iTS', 'NPUPT', 'xthor'].indexOf(forward_site) > -1) {
          allinput[i].value = raw_info.name.replace(/\s/g, ".");
        } else if (forward_site == 'TTG') {
          raw_info.name = raw_info.name.replace(/(5\.1|2\.0|7\.1|1\.0)/, function (data) {
            return data.replace('.', '{@}');
          });
          raw_info.name = raw_info.name.replace(/h\.(26(5|4))/i, 'H{@}$1');
          $('input[name=subtitle]').val(raw_info.small_descr.trim());
          allinput[i].value = raw_info.name;
        } else if (forward_site == 'PuTao') {
          raw_info.name = '[{chinese}] {english}'.format({
            'english': raw_info.name,
            'chinese': get_small_descr_from_descr(raw_info.descr, raw_info.name).split('/')[0].split(/\| 类别/)[0].split('*')[0].trim()
          });
          allinput[i].value = raw_info.name;
        } else if (forward_site == 'Panda') {
          raw_info.name = raw_info.name.replace(/TrueHD(\d\.\d)/, 'TrueHD $1');
          raw_info.name = raw_info.name.replace(/DTS-HD.?MA.?(\d\.\d)/, 'DTS-HD MA $1');
          raw_info.name = raw_info.name.replace(/DTS-HD.?(HRA?).?(\d\.\d)/, 'DTS-HD $1 $2');
          allinput[i].value = raw_info.name;
        } else {
          if (forward_site == 'BLU') {
            raw_info.name = raw_info.name.replace(/Remux/i, 'REMUX');
            raw_info.name = raw_info.name.replace(/(Atmos)(.*?)(TrueHD)(.*?)(7.1)/, '$2$3 $5 $1').replace(/ +/g, ' ');
            if (raw_info.name.match(/DV HDR/i)) {
              raw_info.name = raw_info.name.replace(/(1080|2160)[pi]/i, function (data) {
                return 'Hybrid ' + data;
              });
            }
            raw_info.name = raw_info.name.replace(/DDP/i, 'DD+');
            raw_info.name = raw_info.name.replace(/(DD\+|DD|AAC|TrueHD|DTS.HD.?MA|DTS.HD.?HR|DTS.HD|DTS|L?PCM|FLAC)(.*?)(5\.1|2\.0|7\.1|1\.0)/i, '$1 $3');
            raw_info.name = raw_info.name.replace(/(WEB-DL)(.*?)(AVC|x264|H264)/i, '$1$2H.264');
            raw_info.name = raw_info.name.replace(/(WEB-DL)(.*?)(HEVC|x265|H265)/i, '$1$2H.265');
          }
          if (['ACM'].indexOf(forward_site) > -1) {
            raw_info.name = raw_info.name.replace(/DDP/i, 'DD+');
            raw_info.name = raw_info.name.replace(/(DD\+|DD|AAC|TrueHD|DTS.HD.?MA|DTS.HD.?HR|DTS.HD|DTS|L?PCM|FLAC)[ \.](.*?)(5\.1|2\.0|7\.1|1\.0)/i, '$1$3');
            raw_info.name = raw_info.name.replace(/(WEB-DL|HDTV|SDTV)(.*?)(AVC|x264|H264)/i, '$1$2H.264');
            raw_info.name = raw_info.name.replace(/(WEB-DL|HDTV|SDTV)(.*?)(x265|H265|H.265)/i, '$1$2HEVC');
          }
          if (['BHD'].indexOf(forward_site) > -1) {
            raw_info.name = raw_info.name.replace(/DD\+/i, 'DDP');
            raw_info.name = raw_info.name.replace(/(DDP|DD|AAC|TrueHD|DTS.HD.?MA|DTS.HD.?HR|DTS.HD|DTS|L?PCM|FLAC)(.*?)(5\.1|2\.0|7\.1|1\.0)/i, '$1 $3');
          }
          allinput[i].value = raw_info.name;
        }
      }

      if (allinput[i].name == 'small_descr' || allinput[i].name == 'small_desc' || allinput[i].name == 'subhead' || (allinput[i].name == 'keywords' && forward_site == 'DarkLand')) { //填充副标题
        allinput[i].value = raw_info.small_descr;
        if (forward_site == 'OpenCD') {
          allinput[i].value = raw_info.small_descr.replace('- {自抓}', '');
        }
        if (forward_site == 'CMCT') {
          allinput[i].value = raw_info.small_descr.replace('【', '[').replace('】', ']');
        }
      }

      if (allinput[i].name == 'pt_gen') {
        allinput[i].value = raw_info.dburl ? raw_info.dburl : raw_info.url;
        if (forward_site == 'UBits') {
          allinput[i].value = raw_info.dburl ? raw_info.dburl : "";
        }
      }

      if (allinput[i].name == 'custom_fields[4][1]' && forward_site == 'KuFei') {
        allinput[i].value = raw_info.dburl ? raw_info.dburl : '';
      }

      if (allinput[i].name == 'picture' && !site_url.split('#separator#')[0].match(/offer/)) {
        if (raw_info.descr.match(/\[img\](\S*?)\[\/img\]/i)) {
          allinput[i].value = raw_info.descr.match(/\[img\](\S*?)\[\/img\]/i)[1].split('=').pop();
        }
      }

      if (['url', 'pt_gen[imdb][link]', 'imdb', 'imdb_url', 'imdb_id'].indexOf(allinput[i].name) > -1 && (allinput[i].type == 'text' || allinput[i].type == 'url')) { //填充imdb信息
        if (forward_site == 'OurBits' && raw_info.url == '') {
          if (raw_info.dburl) {
            raw_info.url = raw_info.dburl;
          }
        }
        if (forward_site == 'CMCT') {
          if (raw_info.dburl) {
            allinput[i].value = raw_info.dburl;
          } else {
            allinput[i].value = raw_info.url;
          }
        } else {
          allinput[i].value = raw_info.url;
        }
      }

      if (['url_douban', 'douban', 'dburl', 'douban_url', 'douban_id', 'durl', 'pt_gen[douban][link]'].indexOf(allinput[i].name) > -1) { //豆瓣信息
        if (forward_site == 'TTG' && raw_info.dburl) {
          allinput[i].value = raw_info.dburl.match(/\d+/)[0];
        } else {
          allinput[i].value = raw_info.dburl;
        }
      }

      if (['HDDolby'].indexOf(forward_site) > -1 && allinput[i].name == 'douban_id' && raw_info.dburl) {
        allinput[i].value = raw_info.dburl.match(/\d+/i)[0];
      }

      if (forward_site == 'BTSchool' && allinput[i].name == 'imdbid' && raw_info.url) {
        allinput[i].value = raw_info.url.match(/tt\d+/i)[0];
      }
      if (forward_site == 'BTSchool' && allinput[i].name == 'doubanid' && raw_info.dburl) {
        allinput[i].value = raw_info.dburl.match(/\d+/i)[0];
      }

      if (['TJUPT'].indexOf(forward_site) > -1 && allinput[i].name == 'external_url') {
        allinput[i].value = raw_info.url ? raw_info.url : raw_info.dburl;
      }

      if (forward_site == 'HDT' && allinput[i].name == 'filename') {
        if (raw_info.name.match(/remux/i)) {
          raw_info.name = raw_info.name.replace(/bluray/i, 'Blu-ray');
        }
        allinput[i].value = raw_info.name.replace(/DDP/i, 'DD+').replace(/Remux/i, 'Remux');
      }
      if (forward_site == 'HDT' && allinput[i].name == 'infosite') {
        allinput[i].value = raw_info.url.replace('http:', 'https:').replace(/(tt\d+[^/]$)/, '$1/');
      }
    }

    //填写简介，一般都是textarea，特殊情况后续处理--CMCT改版兼容
    var descr_box = document.getElementsByTagName('textarea');
    if (forward_site == 'AGSV') {
      raw_info.descr = raw_info.descr.replace(/\[color=.*?\].*?\[\/color\]/i, '').trim();
    }
    if (['CMCT', 'PTsbao', 'HDCity', 'BLU', 'UHD', 'HDSpace', 'HDB', 'iTS', 'PTP', 'BYR', 'GPW', 'HDTime', 'HD-Only', 'HDfans',
      'SC', 'MTV', 'NBL', 'avz', 'PHD', 'CNZ', 'ANT', 'TVV', 'xthor', 'HDF', 'OpenCD', 'PigGo', 'RED', 'Tik', 'Aither', 'SugoiMusic', 'CG',
      'ZHUQUE', 'MTeam', 'FNP', 'OnlyEncodes', 'YemaPT', 'DarkLand', '影', 'PTLGS', 'ReelFliX', 'RouSi'].indexOf(forward_site) < 0) {
      if (forward_site == 'HDT') {
        descr_box[0].style.height = '600px';
        var mediainfo_hdt = get_mediainfo_picture_from_descr(raw_info.descr);
        descr_box[0].value = '[quote]' + simplifyMI(mediainfo_hdt.mediainfo, 'HDT') + '[/quote]\n' + mediainfo_hdt.pic_info.replace(/\n/g, '');
      } else if (forward_site != 'HaiDan') {
        if (forward_site != 'OpenCD') {
          descr_box[0].style.height = '800px';
          if ($('textarea[name="technical_info"]').length) {
            descr_box[0].style.height = '460px';
          }
        }
        if (forward_site == 'OPS' && raw_info.origin_site == 'jpop') {
          descr_box[0].style.height = '400px';
          raw_info.descr = raw_info.descr.replace(/^\[.*?\/img\]/, '').trim();
        }
        if (forward_site == 'PTer') {
          if (raw_info.full_mediainfo) {
            if (raw_info.full_mediainfo.match(/mpls/i)) {
              try {
                raw_info.full_mediainfo = raw_info.full_mediainfo.match(/QUICK SUMMARY:([\s\S]*)/)[1].trim();
              } catch (err) { }
            }
            try {
              var info = get_mediainfo_picture_from_descr(raw_info.descr);
              raw_info.descr = raw_info.descr.replace(info.mediainfo, raw_info.full_mediainfo);
            } catch (err) { }
          }
          try {
            raw_info.descr.match(/\[quote\][\s\S]*?\[\/quote\]/g).map((e) => {
              if (e.match(/General.{0,2}\n?(Unique|Complete name)/)) {
                var ee = e.replace('[quote]', '[hide=mediainfo]').replace('[/quote]', '[/hide]');
                raw_info.descr = raw_info.descr.replace(e, ee);
              } else if (e.match(/Disc Title|Disc Info|Disc Label/)) {
                var ee = e.replace('[quote]', '[hide=bdinfo]').replace('[/quote]', '[/hide]');
                raw_info.descr = raw_info.descr.replace(e, ee);
              }
            });
          } catch (err) { }
        } else if (forward_site == 'Audiences' || forward_site == 'TJUPT' || forward_site == 'NexusHD') {
          try {
            raw_info.descr.match(/\[quote\][\s\S]*?\[\/quote\]/g).map((e) => {
              if (e.match(/General|Disc Title|Disc Info|Disc Label|RELEASE.NAME|RELEASE DATE|Unique ID|RESOLUTiON|Bitrate|帧　率|音频码率|视频码率/i)) {
                var ee = e.replace('[quote]', '[Mediainfo]').replace('[/quote]', '[/Mediainfo]');
                if (raw_info.full_mediainfo) {
                  ee = `[Mediainfo]${raw_info.full_mediainfo}[/Mediainfo]`;
                }
                if (forward_site == 'TJUPT') {
                  ee = ee.replace('[Mediainfo]', '[mediainfo]').replace('[/Mediainfo]', '[/mediainfo]');
                }
                raw_info.descr = raw_info.descr.replace(e, ee);
              }
            });
          } catch (err) { }
        }
        descr_box[0].value = raw_info.descr;
        if (forward_site == 'BHD') {
          document.getElementById('mediainfo').dispatchEvent(evt);
        }
        if (forward_site == 'TCCF') {
          $('span:contains("[bbcode]")').click();
          descr_box[0].value = raw_info.descr;
          $('span:contains("[bbcode]")').click();
        }
      } else {
        descr_box[2].value = raw_info.descr;
      }
    }

    if ($('textarea[name="technical_info"]').length || forward_site == '影' || forward_site == 'LemonHD' || forward_site == 'HDDolby' || forward_site == 'MTeam' || forward_site == 'RouSi') {
      var mediainfo_mteam = '';
      function fill_container_or_mteam_mediainfo(v, container) {
        if (forward_site == 'MTeam' || forward_site == 'RouSi') {
          mediainfo_mteam = v.trim();
        } else {
          container.val(v.trim());
        }
      }
      for (i = 0; i < skip_img.length; i++) {
        raw_info.descr = raw_info.descr.replace(skip_img[i], '');
      }
      raw_info.descr = raw_info.descr.replace(/\n\n+/, '\n\n');
      var container = $('textarea[name="technical_info"]');
      if (forward_site == 'LemonHD') {
        container = $('textarea[name="mediainfo"]');
      } else if (forward_site == 'HDDolby') {
        container = $('textarea[name="media_info"]');
      } else if (forward_site == '影' || forward_site == 'PTLGS') {
        var poster = raw_info.descr.match(/\[img\](\S*?)\[\/img\]/i);
        var _index = raw_info.descr.indexOf("◎");
        if (raw_info.descr.indexOf(poster[0]) < 200 || (_index > 0 && raw_info.descr.indexOf(poster[0]) < _index)) {
          $('input[name="tr_cover_url"],input[name="cover"]').val(poster[1]);
          $('input[name="tr_cover_url"],input[name="cover"]').css("width", "93%");
          $('input[name="tr_cover_url"],input[name="cover"]').after(`<button style="margin-left:5px" id="preview">预览</button><img class="my_poster" src="${poster[1]}" style="max-width: 150px; display:none; margin-top:2px;">`);
          $('#preview').click((e) => {
            e.preventDefault();
            if ($('.my_poster').is(":visible")) {
              $('.my_poster').hide();
              $('#preview').text("预览");
            } else {
              $('.my_poster').attr('src', $('input[name="tr_cover_url"]').val());
              $('.my_poster').show();
              $('#preview').text("隐藏");
            }
          })
        }
        if (forward_site == '影') {
          container = $('textarea[name="tr_nfo"]');
        }
      }
      try {
        var infos = get_mediainfo_picture_from_descr(raw_info.descr);
        if (raw_info.multi_mediainfo) {
          mediainfo = raw_info.multi_mediainfo.match(/\[quote.*?\][\s\S]*?General[\s\S]*?\[\/quote\]/ig);
          mediainfo = mediainfo.join('\n\n').replace(/\[\/?quote\]/g, '');
          fill_container_or_mteam_mediainfo(mediainfo, container);
        } else if (infos.multi_mediainfos) {
          fill_container_or_mteam_mediainfo(infos.multi_mediainfos, container);
        } else if (raw_info.full_mediainfo) {
          fill_container_or_mteam_mediainfo(raw_info.full_mediainfo, container);
        } else {
          fill_container_or_mteam_mediainfo(infos.mediainfo.replace(/\[\/?(size|font|color).*?\]/g, ''), container);
        }
        if ($('input[name="screenshot"]').length) {
          get_full_size_picture_urls(null, infos.pic_info, $('#not'), false, function (img_info) {
            $('input[name="screenshot"]').val(img_info.trim().split('\n').join(','));
          });
        }
        if ($('textarea[name="screenshots"]').length || forward_site == '财神' || forward_site == 'LuckPT' || forward_site == 'MTeam') {
          if (forward_site == 'HDDolby' || forward_site == 'PTLGS') {
            get_full_size_picture_urls(null, infos.pic_info, $('#not'), false, function (img_info) {
              $('textarea[name="screenshots"]').val(img_info.trim());
            }, function (data) {
              for (i = 0; i < data.length; i++) {
                if (data[i]) {
                  raw_info.descr = raw_info.descr.replace(data[i], '');
                }
              }
            });
          } else if (forward_site == '财神' || forward_site == 'LuckPT' || forward_site == 'MTeam') {
            get_full_size_picture_urls(null, infos.pic_info, $('#not'), true, function (img_info) {
              raw_info.descr += img_info.trim();
            }, function (data) {
              for (i = 0; i < data.length; i++) {
                if (data[i]) {
                  raw_info.descr = raw_info.descr.replace(data[i], '');
                }
              }
            });
          }
        }
        if ($('textarea[name="screen"]').length) {
          get_full_size_picture_urls(null, infos.pic_info, $('#not'), false, function (img_info) {
            $('textarea[name="screen"]').val(img_info.trim());
          });
        }
        container.css({ 'height': '600px' });
        var tmp_descr = raw_info.descr.replace(infos.mediainfo, '');
        if (forward_site == '影') {
          tmp_descr = tmp_descr.replace(/(\[url=.*\])?\[img\].*?\[\/img\](\[\/url\])?/g, '');
          $('textarea[name="descr"]').css({ 'height': '400px' });
        }
        tmp_descr = tmp_descr.replace(/\[quote\].*?官组作品.*?\[\/quote\]/g, '').replace(/\[quote\][\s\S]*?\[\/quote\]/g, function (data) {
          if (!data.replace(/\[.*?\]/g, '').trim()) {
            return '';
          } else {
            return data;
          }
        });
        tmp_descr = tmp_descr.replace(/ +\n/g, '\n');
        if (raw_info.full_mediainfo) {
          tmp_descr = tmp_descr.replace(/\[quote\][\s\S]{0,80}(General|Disc)[\s\S]{50,30000}?\[\/quote\]/g, '');
        }
        if (raw_info.origin_site == 'Audiences' || raw_info.origin_site == 'HDHome') {
          tmp_descr = tmp_descr.replace(/\[\/?font.*?\]/g, '');
        }
        raw_info.descr = tmp_descr;
        raw_info.descr = add_thanks(raw_info.descr);
        if (forward_site == 'NJTUPT') {
          $('textarea[name="body"]').val(raw_info.descr.trim().replace(/\n\n+/g, '\n\n').replace(/\]\n\n\[/g, '\]\n\['));
        }
        if (forward_site != 'PTLGS') {
          $('textarea[name="descr"]').val(raw_info.descr.trim().replace(/\n\n+/g, '\n\n').replace(/\]\n\n\[/g, '\]\n\['));
        } else {
          try {
            var extra_info = raw_info.descr.match(/^\[quote\]\[b\]\[color=blue\].*?官组作品，感谢原制作者发布。\[\/color\]\[\/b\]\[\/quote\]/)[0];
            $('textarea[name="descr"]').val(extra_info);
          } catch (err) { }
        }
      } catch (Err) {
        if (raw_info.full_mediainfo) {
          fill_container_or_mteam_mediainfo(raw_info.full_mediainfo, container);
        } else {
          fill_container_or_mteam_mediainfo(raw_info.descr, container);
        }
        container.css({ 'height': '600px' });
      }
      raw_info.descr = raw_info.descr.replace(/\n\n+/g, '\n');
    }

    if (forward_site == 'TTG') {
      setTimeout(function () {
        descr_box[0].value = descr_box[0].value.replace(/http:\/\/anonym\.to\/\?/ig, '');
      }, 2000);
    }

    //-------------------------------------------勾选国语粤语中字等标签--------------------------------------------------------
    var label_str = raw_info.small_descr + raw_info.name + '#separator#' + raw_info.descr;
    if ($('textarea[name="technical_info"]').length) {
      label_str += $('textarea[name="technical_info"]').val();
    } else if ($('textarea[name="mediainfo"]').length) {
      label_str += $('textarea[name="mediainfo"]').val();
    }
    if ($('textarea[name="tr_nfo"]').length) {
      label_str += $('textarea[name="tr_nfo"]').val();
    }
    var labels = label_str.get_label();
    if (raw_info.labels % 2) {
      labels.gy = true;
    }
    if (9 < raw_info.labels && raw_info.labels < 100) {
      labels.yy = true;
    }
    if (raw_info.labels > 99) {
      labels.zz = true;
    }
    if (raw_info.descr.match(/◎语.*?言　汉语普通话/) && !label_str.match(/mpls/i)) {
      labels.gy = true;
    }
    if (raw_info.descr.match(/◎语.*?言　粤语/) && !label_str.match(/mpls/i)) {
      labels.yy = true;
    }
    if (raw_info.name.match(/(x|H)(264|265)/i)) {
      labels.diy = false;
    }
    if ((raw_info.name.match(/[\. ]S\d+/) && !raw_info.name.match(/S\d+.?E\d+/)) || ((raw_info.name.match(/Complete/i) || raw_info.small_descr.match(/全\d+集/)) && raw_info.type == '剧集')) {
      labels.complete = true;
    } else if (raw_info.type == '剧集' && raw_info.medium_sel == 'Blu-ray') {
      labels.complete = true;
    } else {
      labels.complete = false;
    }
    if (raw_info.descr.match(/Presentation Graphics.*Chinese/)) {
      labels.zz = true;
    }
    console.log(labels);
    try {
      switch (forward_site) {
        case 'PTer':
          if (labels.gy) { document.getElementById('guoyu').checked = true; }
          if (labels.yy) { document.getElementById('yueyu').checked = true; }
          if (labels.zz) { document.getElementById('zhongzi').checked = true; }
          if (labels.diy) { document.getElementById('diy').checked = true; }
          if (labels.yz) { document.getElementById('ensub').checked = true; }
          break;
        case 'CHDBits':
          if (labels.gy) { document.getElementsByName('cnlang')[0].checked = true; }
          if (labels.zz) { document.getElementsByName('cnsub')[0].checked = true; }
          if (labels.diy) { document.getElementsByName('diy')[0].checked = true; }
          break;
        case 'CMCT':
          if (labels.zz) { document.getElementById('subtitlezh').checked = true; }
          if (!labels.diy && raw_info.descr.match(/mpls/i)) { document.getElementById('untouched').checked = true; }
          if (labels.hdr10) { document.getElementById('hdr10').checked = true; }
          if (labels.hdr10plus) { document.getElementById('hdr10plus').checked = true; }
          if (raw_info.descr.match(/HDR Vivid/)) { document.getElementById('hdrvivid').checked = true; }
          if (raw_info.small_descr.match(/特效字幕/)) { document.getElementById('subtitlesp').checked = true; }
          if (labels.db) { document.getElementById('dovi').checked = true; }
          if (raw_info.name.match(/(\.| )3D(\.| )/)) { document.getElementById('3d').checked = true; }
          if (raw_info.name.match(/HLG/)) { document.getElementById('hlg').checked = true; }
          if (labels.complete) { document.getElementById('pack').checked = true; }
          break;
        case 'OurBits':
          if (labels.gy) { document.getElementById('tag_gy').checked = true; }
          if (labels.zz) { document.getElementById('tag_zz').checked = true; }
          if (labels.diy) { document.getElementById('tag_diy').checked = true; }
          if (labels.hdr10) { document.getElementById('tag_hdr').checked = true; }
          if (labels.hdr10plus) { document.getElementById('tag_hdrp').checked = true; }
          if (labels.db) { document.getElementById('tag_db').checked = true; }
          if (raw_info.name.match(/HLG/)) { document.getElementById('tag_hlg').checked = true; }
          break;
        case 'HaiDan':
          if (labels.diy) {
            $('input[name="tag_list[]"][value=4]').attr('checked', true);
          } else if (labels.yp) {
            $('input[name="tag_list[]"][value=7]').attr('checked', true);
          }
          if (labels.gy) { $('input[name="tag_list[]"][value=5]').attr('checked', true); }
          if (labels.yy) { $('input[name="tag_list[]"][value=10]').attr('checked', true); }
          if (labels.zz) { $('input[name="tag_list[]"][value=3]').attr('checked', true); }
          if (!labels.gy && !labels.yy) {
            $('input[name="tag_list[]"][value=11]').attr('checked', true);
          }
          if (labels.hdr10 || labels.hdr10plus) { $('input[name="tag_list[]"][value=16]').attr('checked', true); }
          if (labels.db) { $('input[name="tag_list[]"][value=15]').attr('checked', true); }
          if (raw_info.name.match(/\.3D\.| 3D /)) {
            $('input[name="tag_list[]"][value=14]').attr('checked', true);
          }
          break;
        case 'HDSky':
          if (labels.diy) {
            $('input[name="option_sel[]"][value="13"]').attr('checked', true);
          } else if (labels.yp) {
            $('input[name="option_sel[]"][value=28]').attr('checked', true);
          }
          if (labels.gy) { $('input[name="option_sel[]"][value="5"]').attr('checked', true); }
          if (labels.yy) { $('input[name="option_sel[]"][value="11"]').attr('checked', true); }
          if (labels.zz) { $('input[name="option_sel[]"][value="6"]').attr('checked', true); }
          if (raw_info.small_descr.match(/特效字幕/)) { $('input[name="option_sel[]"][value="20"]').attr('checked', true); }
          if (labels.db && (labels.hdr10plus || labels.hdr10)) {
            $('input[name="option_sel[]"][value="24"]').attr('checked', true);
          } else if (labels.db) {
            $('input[name="option_sel[]"][value="15"]').attr('checked', true);
          } else if (labels.hdr10plus) {
            $('input[name="option_sel[]"][value="17"]').attr('checked', true);
          } else if (labels.hdr10) {
            $('input[name="option_sel[]"][value="9"]').attr('checked', true);
          }
          if (raw_info.descr.match(/atmos /i)) {
            $('input[name="option_sel[]"][value=21]').attr('checked', true);
          }
          break;
        case 'HDDolby': case 'PThome': case 'HDHome': case 'Audiences':
          if (labels.gy) { check_label(document.getElementsByName('tags[]'), 'gy'); }
          if (labels.yy) { check_label(document.getElementsByName('tags[]'), 'yy'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[]'), 'zz'); }
          if (labels.diy) {
            check_label(document.getElementsByName('tags[]'), 'diy');
          } else {
            if (labels.yp && forward_site == 'HDHome') {
              check_label(document.getElementsByName('tags[]'), 'ybyp');
            }
          }
          if (labels.hdr10) { check_label(document.getElementsByName('tags[]'), 'hdr10'); }
          if (labels.hdr10plus) { check_label(document.getElementsByName('tags[]'), 'hdrm'); }
          if (labels.db) { check_label(document.getElementsByName('tags[]'), 'db'); }
          if (labels.complete) { check_label(document.getElementsByName('tags[]'), 'wj'); }
          break;
        case 'HDVideo':
          if (labels.gy) { check_label(document.getElementsByName('tags[4][]'), '5'); }
          if (labels.yy) { check_label(document.getElementsByName('tags[4][]'), '10'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[4][]'), '6'); }
          if (labels.diy) { check_label(document.getElementsByName('tags[4][]'), '4'); }
          if (labels.hdr10) { check_label(document.getElementsByName('tags[4][]'), '11'); }
          if (labels.hdr10plus) { check_label(document.getElementsByName('tags[4][]'), '20'); }
          if (labels.db) { check_label(document.getElementsByName('tags[4][]'), '12'); }
          if (labels.complete) { check_label(document.getElementsByName('tags[4][]'), '17'); }
          break;
        case 'UBits':
          if (labels.gy) { check_label(document.getElementsByName('tags[4][]'), '5'); }
          if (labels.yy) { check_label(document.getElementsByName('tags[4][]'), '11'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[4][]'), '6'); }
          if (labels.diy) {
            check_label(document.getElementsByName('tags[4][]'), '4');
          } else if (labels.yp) {
            check_label(document.getElementsByName('tags[4][]'), '17');
          }
          if (raw_info.standard_sel == '4K') {
            if (labels.hdr10 || labels.hdr10plus) {
              if (labels.hdr10) {
                check_label(document.getElementsByName('tags[4][]'), '9');
              }
              if (labels.hdr10plus) {
                check_label(document.getElementsByName('tags[4][]'), '10');
              }
            } else {
              if ($('textarea[name="technical_info"]').val().match(/HDR10/)) {
                check_label(document.getElementsByName('tags[4][]'), '9');
              } else {
                check_label(document.getElementsByName('tags[4][]'), '7');
              }
            }
          }
          if (raw_info.small_descr.match(/特效字幕/)) { check_label(document.getElementsByName('tags[4][]'), '12'); }
          if (raw_info.audiocodec_sel == 'DTS-X') {
            check_label(document.getElementsByName('tags[4][]'), '16');
          }
          if ($('textarea[name="technical_info"]').val().match(/Dolby.{0,15}Atmos/)) { check_label(document.getElementsByName('tags[4][]'), '15'); }
          if (labels.db) { check_label(document.getElementsByName('tags[4][]'), '8'); }
          if (labels.complete) { check_label(document.getElementsByName('tags[4][]'), '20'); }
          if (raw_info.name.match(/HLG/)) { check_label(document.getElementsByName('tags[4][]'), '19'); }
          break;
        case 'LemonHD':
          if (labels.gy) { check_label(document.getElementsByName('tag_gy'), '1'); }
          if (labels.yy) { check_label(document.getElementsByName('tag_yy'), '1'); }
          if (labels.zz) { check_label(document.getElementsByName('tag_zz'), '1'); }
          if (labels.diy) {
            check_label(document.getElementsByName('tag_diy'), '1');
          } else if (labels.yp) {
            check_label(document.getElementsByName('tag_untouch'), '1');
          }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tag_hdr'), '1'); }
          if (labels.db) { check_label(document.getElementsByName('tag_dv'), '1'); }
          break;
        case 'WT-Sakura':
          if (labels.gy) { check_label(document.getElementsByName('tags[4][]'), '5'); }
          if (labels.yy) { check_label(document.getElementsByName('tags[4][]'), '12'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[4][]'), '6'); }
          if (labels.diy) {
            check_label(document.getElementsByName('tags[4][]'), '4');
          } else if (labels.yp) {
            check_label(document.getElementsByName('tags[4][]'), '22');
          }
          if (labels.hdr10) { check_label(document.getElementsByName('tags[4][]'), '7'); }
          if (labels.hdr10plus) { check_label(document.getElementsByName('tags[4][]'), '10'); }
          if (labels.db) { check_label(document.getElementsByName('tags[4][]'), '11'); }
          if (raw_info.small_descr.match(/特效字幕/)) {
            check_label(document.getElementsByName('tags[4][]'), '9');
          }
          break;
        case 'HITPT':
          if (labels.gy) { check_label(document.getElementsByName('tags[4][]'), '5'); }
          if (labels.yy) { check_label(document.getElementsByName('tags[4][]'), '8'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[4][]'), '6'); }
          if (labels.diy) { check_label(document.getElementsByName('tags[4][]'), '4'); }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tags[4][]'), '7'); }
          if (labels.db) { check_label(document.getElementsByName('tags[4][]'), '9'); }
        case 'FreeFarm':
          if (labels.gy) { check_label(document.getElementsByName('tags[4][]'), '5'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[4][]'), '6'); }
          if (labels.diy) { check_label(document.getElementsByName('tags[4][]'), '4'); }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tags[4][]'), '7'); }
          if (raw_info.name.match(/(\.| )3D(\.| )/)) { check_label(document.getElementsByName('tags[4][]'), '11'); }
          if (labels.complete) { check_label(document.getElementsByName('tags[4][]'), '10'); }
          if (raw_info.name.match(/S\d{1,3}.?E\d{1,5}/) || raw_info.small_descr.match(/第\d{1,5}(.\d{1,5})?集/)) {
            check_label(document.getElementsByName('tags[4][]'), '12');
          }
          if (raw_info.type == '短剧') { check_label(document.getElementsByName('tags[4][]'), '8'); }
          break;
        case 'PigGo':
          if (labels.gy) { check_label(document.getElementsByName('tags[4][]'), '5'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[4][]'), '6'); }
          if (labels.diy) { check_label(document.getElementsByName('tags[4][]'), '4'); }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tags[4][]'), '7'); }
          if (labels.db) { check_label(document.getElementsByName('tags[4][]'), '9'); }
          if (labels.complete) { check_label(document.getElementsByName('tags[4][]'), '13'); }
          if (raw_info.name.match(/DV/)) { check_label(document.getElementsByName('tags[4][]'), '9'); }
          if (raw_info.name.match(/(\.| )3D(\.| )/)) { check_label(document.getElementsByName('tags[4][]'), '8'); }
          if (raw_info.descr.match(/Dolby.*?Atmos/) || $('textarea[name="technical_info"]').val().match(/Dolby.*?Atmos/)) {
            check_label(document.getElementsByName('tags[4][]'), '12');
          }
          if (raw_info.name.match(/-DGB/i)) { check_label(document.getElementsByName('tags[4][]'), '24'); }
          break;
        case 'UltraHD':
          if (labels.gy) { check_label(document.getElementsByName('tags[]'), '5'); }
          if (labels.yy) { check_label(document.getElementsByName('tags[]'), '5'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[]'), '6'); }
          if (labels.diy) { check_label(document.getElementsByName('tags[]'), '4'); }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tags[]'), '7'); }
          if (labels.db) { check_label(document.getElementsByName('tags[]'), '9'); }
          break;
        case "CarPt":
          if (labels.gy) { check_label(document.getElementsByName('tags[4][]'), '5'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[4][]'), '6'); }
          if (labels.diy) { check_label(document.getElementsByName('tags[4][]'), '4'); }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tags[4][]'), '7'); }
          break;
        case 'Oshen':
          if (labels.gy) { check_label(document.getElementsByName('tags[4][]'), '5'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[4][]'), '6'); }
          if (labels.diy) { check_label(document.getElementsByName('tags[4][]'), '4'); }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tags[4][]'), '7'); }
          break;
        case 'DiscFan':
          if (labels.gy) { check_label(document.getElementsByName('tags[4][]'), '5'); }
          if (labels.yy) { check_label(document.getElementsByName('tags[4][]'), '8'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[4][]'), '6'); }
          if (labels.diy) { check_label(document.getElementsByName('tags[4][]'), '4'); }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tags[4][]'), '7'); }
          break;
        case 'PTsbao':
          if (labels.zz) { check_label(document.getElementsByName('tags[1][]'), '6'); }
          if (labels.gy) { check_label(document.getElementsByName('tags[1][]'), '5'); }
          if (labels.diy) { check_label(document.getElementsByName('tags[1][]'), '4'); }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tags[1][]'), '7'); }
          break;
        case 'BTSchool':
          if (labels.gy) { document.getElementsByName('span[]')[4].checked = true; }
          if (labels.yy) { document.getElementsByName('span[]')[4].checked = true; }
          if (labels.zz) { document.getElementsByName('span[]')[5].checked = true; }
          break;
        case 'HaiDan':
          if (labels.gy) { document.getElementsByName('tag[cn]')[0].checked = true; }
          if (labels.yy) { document.getElementsByName('tag[cn]')[0].checked = true; }
          if (labels.zz) { document.getElementsByName('tag[zz]')[0].checked = true; }
          break;
        case '52PT':
          if (labels.gy) { document.getElementsByName('tags[]')[4].checked = true; }
          if (labels.yy) { document.getElementsByName('tags[]')[4].checked = true; }
          if (labels.zz) { document.getElementsByName('tags[]')[5].checked = true; }
          break;
        case 'HDfans':
          if (labels.gy) { $('input[name="tags[4][]"][value="5"]').attr('checked', true); }
          if (labels.yy) { $('input[name="tags[4][]"][value="10"]').attr('checked', true); }
          if (labels.zz) { $('input[name="tags[4][]"][value="6"]').attr('checked', true); }
          if (labels.diy) {
            $('input[name="tags[4][]"][value="4"]').attr('checked', true);
          } else if (labels.yp) {
            $('input[name="tags[4][]"][value="21"]').attr('checked', true);
          }
          if (labels.db) { $('input[name="tags[4][]"][value="9"]').attr('checked', true); }
          if (labels.hdr10 || labels.hdr10plus) { try { $('input[name="tags[4][]"][value="7"]').attr('checked', true); } catch (err) { } }
          if (raw_info.descr.match(/Dolby.*?Atmos/) || $('textarea[name="technical_info"]').val().match(/Dolby.*?Atmos/)) {
            check_label(document.getElementsByName('tags[4][]'), '12');
          }
          if (labels.complete) { $('input[name="tags[4][]"][value="23"]').attr('checked', true); }
          break;
        case '52MOVIE':
          if (labels.gy) { $('input[name="tags[4][]"][value="5"]').attr('checked', true); }
          if (labels.yy) { $('input[name="tags[4][]"][value="8"]').attr('checked', true); }
          if (labels.zz) { $('input[name="tags[4][]"][value="6"]').attr('checked', true); }
          if (labels.diy) {
            $('input[name="tags[4][]"][value="4"]').attr('checked', true);
          } else if ($('textarea[name="technical_info"]').val().match(/mpls/i)) {
            $('input[name="tags[4][]"][value="0"]').attr('checked', true);
          }
          if (labels.db) { $('input[name="tags[4][]"][value="11"]').attr('checked', true); }
          if (labels.hdr10) { $('input[name="tags[4][]"][value="12"]').attr('checked', true); }
          if (labels.hdr10plus) {
            $('input[name="tags[4][]"][value="13"]').attr('checked', true);
          } else {
            if (labels.hdr) { $('input[name="tags[4][]"][value="7"]').attr('checked', true); }
          }
          if (labels.complete) { $('input[name="tags[4][]"][value="10"]').attr('checked', true); }
          if (raw_info.type == '动漫') {
            check_label(document.getElementsByName('tags[4][]'), '14');
          }
          break;
        case "HDTime":
          if (labels.gy) { $('input[name="tags[4][]"][value="5"]').attr('checked', true); }
          if (labels.yy) { $('input[name="tags[4][]"][value="5"]').attr('checked', true); }
          if (labels.zz) { $('input[name="tags[4][]"][value="6"]').attr('checked', true); }
          if (labels.diy) { $('input[name="tags[4][]"][value="4"]').attr('checked', true); }
          if (labels.hdr10 || labels.hdr10plus) { try { $('input[name="tags[4][]"][value="7"]').attr('checked', true); } catch (err) { } }
          break;
        case 'PTChina':
          if (labels.db) { $('input[name="tags[4][]"][value="8"]').attr('checked', true); }
          if (labels.gy) { $('input[name="tags[4][]"][value="5"]').attr('checked', true); }
          if (labels.yy) { $('input[name="tags[4][]"][value="5"]').attr('checked', true); }
          if (labels.zz) { $('input[name="tags[4][]"][value="6"]').attr('checked', true); }
          if (labels.diy) { $('input[name="tags[4][]"][value="4"]').attr('checked', true); }
          if (labels.hdr10 || labels.hdr10plus) { $('input[name="tags[4][]"][value="7"]').attr('checked', true); }
          break;
        case '1PTBA':
          if (labels.gy) { check_label(document.getElementsByName('tags[4][]'), '5'); }
          if (labels.yy) { check_label(document.getElementsByName('tags[4][]'), '11'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[4][]'), '6'); }
          if (labels.diy) { check_label(document.getElementsByName('tags[4][]'), '4'); }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tags[4][]'), '7'); }
          if (labels.db) { check_label(document.getElementsByName('tags[4][]'), '21'); }
          if (raw_info.type == 'MV') { check_label(document.getElementsByName('tags[4][]'), '26'); }
          if (raw_info.small_descr.match(/特效字幕/)) {
            check_label(document.getElementsByName('tags[4][]'), '24');
          }
          break;
        case 'HDRoute':
          if (labels.gy) { document.getElementsByName('is_mandrain')[0].checked = true; }
          if (labels.yy) { document.getElementsByName('is_cantonese')[0].checked = true; }
          if (labels.diy) { document.getElementsByName('is_diyed')[0].checked = true; }
          break;
        case 'ZMPT':
          if (labels.gy) { $('input[name="tags[4][]"][value="5"]').attr('checked', true); }
          if (labels.yy) { $('input[name="tags[4][]"][value="5"]').attr('checked', true); }
          if (labels.zz) { $('input[name="tags[4][]"][value="6"]').attr('checked', true); }
          if (labels.diy) {
            $('input[name="tags[4][]"][value="4"]').attr('checked', true);
          } else if (labels.yp) {
            $('input[name="tags[4][]"][value="10"]').attr('checked', true);
          }
          if (labels.hdr10 || labels.hdr10plus) { try { $('input[name="tags[4][]"][value="7"]').attr('checked', true); } catch (err) { } }
          if (labels.complete) { $('input[name="tags[4][]"][value="12"]').attr('checked', true); }
          break;
        case 'ICC':
          if (labels.gy) { $('input[name="tags[4][]"][value="5"]').attr('checked', true); }
          if (labels.yy) { $('input[name="tags[4][]"][value="5"]').attr('checked', true); }
          if (labels.zz) { $('input[name="tags[4][]"][value="6"]').attr('checked', true); }
          if (labels.diy) { $('input[name="tags[4][]"][value="4"]').attr('checked', true); }
          if (labels.hdr10 || labels.hdr10plus) { try { $('input[name="tags[4][]"][value="7"]').attr('checked', true); } catch (err) { } }
          break;
        case 'CyanBug':
          if (labels.gy) { check_label(document.getElementsByName('tags[4][]'), '5'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[4][]'), '6'); }
          if (labels.diy) { check_label(document.getElementsByName('tags[4][]'), '4'); }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tags[4][]'), '7'); }
          if (labels.db) { check_label(document.getElementsByName('tags[4][]'), '8'); }
          if (raw_info.name.match(/DV/)) { check_label(document.getElementsByName('tags[4][]'), '8'); }
          break;
        case 'RS':
          if (labels.diy) { check_label(document.getElementsByName('tags[]'), '4'); }
          if (labels.gy) { check_label(document.getElementsByName('tags[]'), '5'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[]'), '6'); }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tags[]'), '7'); }
          break;
        case 'OKPT':
          if (labels.gy) { check_label(document.getElementsByName('tags[4][]'), '5'); }
          if (labels.en) { check_label(document.getElementsByName('tags[4][]'), '57'); }
          if (labels.yy) { check_label(document.getElementsByName('tags[4][]'), '45'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[4][]'), '6'); }
          if (labels.yz) { check_label(document.getElementsByName('tags[4][]'), '58'); }
          if (labels.diy) { check_label(document.getElementsByName('tags[4][]'), '4'); }
          if (labels.complete) {
            check_label(document.getElementsByName('tags[4][]'), '51');
          } else if (raw_info.name.match(/[\d ]E\d+[ \.]/)) {
            check_label(document.getElementsByName('tags[4][]'), '50');
          }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tags[4][]'), '7'); }
          if (labels.db) { check_label(document.getElementsByName('tags[4][]'), '8'); }
          if (raw_info.small_descr.match(/特效字幕/)) { check_label(document.getElementsByName('tags[4][]'), '12'); }
          if (raw_info.descr.match(/Dolby.*?Atmos/) || $('textarea[name="technical_info"]').val().match(/Dolby.*?Atmos/)) {
            check_label(document.getElementsByName('tags[4][]'), '53');
          }
          break;
        case 'CrabPt':
          if (labels.gy) { check_label(document.getElementsByName('tags[4][]'), '5'); }
          if (labels.yy) { check_label(document.getElementsByName('tags[4][]'), '6'); }
          if (labels.zz) { check_label(document.getElementsByName('tags[4][]'), '7'); }
          if (labels.diy) { check_label(document.getElementsByName('tags[4][]'), '4'); }
          if (labels.complete) {
            check_label(document.getElementsByName('tags[4][]'), '8');
          } else if (raw_info.type == '剧集' || raw_info.name.match(/S\d+E\d+/)) {
            check_label(document.getElementsByName('tags[4][]'), '9');
          }
          if (labels.hdr10 || labels.hdr10plus) { check_label(document.getElementsByName('tags[4][]'), '11'); }
          if (labels.db) { check_label(document.getElementsByName('tags[4][]'), '12'); }
          if (raw_info.small_descr.match(/特效字幕/)) { check_label(document.getElementsByName('tags[4][]'), '10'); }
          if (raw_info.descr.match(/Dolby.*?Atmos/) || $('textarea[name="technical_info"]').val().match(/Dolby.*?Atmos/)) {
            check_label(document.getElementsByName('tags[4][]'), '13');
