/**
 * @module 20_forward_site_filling4
 * @description forward_site blocks: BLU, ACM, Tik, image handling...
 * @lines 21001-23000
 * 
 * Extracted from auto_feed.user.js
 * DO NOT EDIT - Auto-generated by split_modules.py
 */

        case 'X265': codec_box.val(11); break;
        case 'VP9': codec_box.val(9); break;
        case 'X264': codec_box.val(2); break;
      }
      if (raw_info.name.match(/H.?266/)) { codec_box.val(10); }

      //分辨率
      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = { '8K': 1, '4K': 2, '1080p': 3, '1080i': 3, '720p': 4 };
      standard_box.val(5);
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }

      //音频编码
      var audiocodec_box = $('select[name="audiocodec_sel[4]"]');
      console.log(raw_info.audiocodec_sel)
      switch (raw_info.audiocodec_sel) {
        case 'DTS-HD': audiocodec_box.val(7); break;
        case 'DTS-HDMA:X 7.1': audiocodec_box.val(22); break;
        case 'DTS-HDMA': case 'DTS-HDHR': audiocodec_box.val(7); break;
        case 'TrueHD': audiocodec_box.val(19); break;
        case 'Atmos':
          var info_plus = raw_info.name + raw_info.descr + $('textarea[name="technical_info"]').val();
          if (info_plus.match(/True.?HD/i)) {
            audiocodec_box.val(19);
          } else {
            audiocodec_box.val(15);
          }
          break;
        case 'DTS': audiocodec_box.val(3); break;
        case 'AC3': audiocodec_box.val(15); break;
        case 'AAC': audiocodec_box.val(6); break;
        case 'Flac': audiocodec_box.val(1); break;
        case 'APE': audiocodec_box.val(5); break;
        case 'LPCM': audiocodec_box.val(16); break;
        case 'WAV': audiocodec_box.val(7);
      }

      $('select[name="team_sel[4]"]').val(14);
      for (var key in reg_team_name) {
        if (raw_info.name.match(reg_team_name[key]) && !raw_info.name.match(/PandaMoon|HDSpace|HDClub|LCHD/i)) {
          if (key == 'MTeam') key = 'M-team';
          if (key == 'Pter') key = 'PterClub';
          if (key == '影') key = 'Ying';
          if (key == '红叶') key = 'Red Leaves';
          $('select[name="team_sel[4]"]>option').map(function (index, e) {
            var reg_team = new RegExp(key, 'i');
            if (e.innerText.match(reg_team)) {
              $(`select[name="team_sel[4]"]>option:eq(${index})`).attr('selected', true);
            }
          });
        }
      }

      var team_box = $('select[name="processing_sel[4]"]');
      var team_dict = { '欧美': 6, '大陆': 8, '香港': 7, '台湾': 7, '日本': 5, '韩国': 4, '澳门': 7, '印度': 17 };
      const southeast_asia = ['菲律宾', '印度尼西亚', '马来西亚', '新加坡', '泰国', '老挝', '缅甸', '越南', '文莱', '柬埔寨', '不丹'];
      team_box.val(3);
      if (team_dict.hasOwnProperty(raw_info.source_sel)) {
        var index = team_dict[raw_info.source_sel];
        team_box.val(index);
      }
      if (southeast_asia.indexOf(raw_info.source_sel) > -1) {
        team_box.val(18);
      }
      if (raw_info.descr.match(/◎语.*?言.*?日语/)) {
        $('input[name="tags[4][]"][value="28"]').attr('checked', true);
      }
      if (raw_info.descr.match(/◎语.*?言.*?韩语/)) {
        $('input[name="tags[4][]"][value="25"]').attr('checked', true);
      }
    }

    else if (forward_site == 'DiscFan') {
      var browsecat = document.getElementsByName('type')[0];
      switch (raw_info.type) {
        case '电影':
          if (raw_info.source_sel == '大陆') {
            browsecat.options[1].selected = true;
          } else if (raw_info.source_sel == '香港') {
            browsecat.options[2].selected = true;
          } else if (raw_info.source_sel == '台湾') {
            browsecat.options[3].selected = true;
          } else if (raw_info.source_sel == '日本') {
            browsecat.options[5].selected = true;
          } else if (raw_info.source_sel == '韩国') {
            browsecat.options[6].selected = true;
          } else {
            var reg_region = raw_info.descr.match(/(地.{0,5}?区|国.{0,5}?家|产.{0,5}?地|◎產.{0,5}?地)([^\r\n]+)/);
            if (reg_region && reg_region[2].match(/泰国/)) {
              browsecat.options[4].selected = true;
            } else {
              browsecat.options[7].selected = true;
            }
          }
          break;
        case '动漫': browsecat.options[13].selected = true; break;
        case '剧集': browsecat.options[8].selected = true; break;
        case '纪录': browsecat.options[10].selected = true; break;
        case '综艺': browsecat.options[11].selected = true; break;
        case '音乐': case 'MV': browsecat.options[9].selected = true; break;
        case '体育': browsecat.options[12].selected = true; break;
      }

      var source_box = $('select[name="source_sel[4]"]');
      if (raw_info.standard_sel == '4K') {
        source_box.val(2);
      }
      switch (raw_info.medium_sel) {
        case 'UHD': source_box.val(2); break;
        case 'Blu-ray': source_box.val(3); break;
        case 'DVD': source_box.val(4); break;
        case 'HDTV': source_box.val(1); break;
        case 'Encode': source_box.val(10); break;
        case 'WEB-DL': source_box.val(9); break;
        case 'Remux': source_box.val(131);
      }
      if (raw_info.name.match(/dvdrip|BDRIP/i)) {
        source_box.val(10);
      } else if (raw_info.name.match(/ tv /i)) {
        source_box.val(5);
      } else if (raw_info.name.match(/ldrip/i)) {
        source_box.val(7);
      } else if (raw_info.name.match(/vcd/i)) {
        source_box.val(6);
      } else if (raw_info.name.match(/vhs/i)) {
        source_box.val(8);
      }
    }

    else if (forward_site == 'PigGo') {
      var browsecat = $('#browsecat')
      var type_dict = {
        '电影': 401, '剧集': 402, '动漫': 405, '综艺': 403, '音乐': 408, '纪录': 404,
        '体育': 407, '软件': 409, '学习': 409, '': 409, '游戏': 409, 'MV': 406
      };
      browsecat.val(409)
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      disableother('browsecat', 'specialcat');
      var source_box = $('select[name="source_sel[4]"]');
      source_box.val(6)
      switch (raw_info.medium_sel) {
        case 'UHD': source_box.val(1); break;
        case 'Blu-ray': case 'Remux': case 'Encode':
          source_box.val(1); break;
        case 'HDTV': source_box.val(5); break;
        case 'WEB-DL': source_box.val(7); break;
        case 'DVD': source_box.val(3);
      }
      var medium_box = $('select[name="medium_sel[4]"]');
      switch (raw_info.medium_sel) {
        case 'UHD': medium_box.val(11); break;
        case 'Blu-ray': medium_box.val(11); break;
        case 'DVD':
          medium_box.val(11);
          if (raw_info.name.match(/DVDr/i)) {
            medium_box.val(7);
          }
          break;
        case 'Remux': medium_box.val(3); break;
        case 'HDTV': medium_box.val(8); break;
        case 'Encode': medium_box.val(7); break;
        case 'WEB-DL':
          medium_box.val(11);
          if (raw_info.name.match(/webrip/i)) {
            medium_box.val(7);
          }
          break;
        case 'CD': medium_box.val(8);
      }
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(5);
      switch (raw_info.codec_sel) {
        case 'H265': case 'X265': codec_box.val(6); break;
        case 'H264': codec_box.val(1); case 'X264': codec_box.val(1); break;
        case 'VC-1': codec_box.val(5); break;
        case 'MPEG-2': case 'MPEG-4': codec_box.val(5);; break;
        case 'XVID': codec_box.val(5);
      }
      var audiocodec_box = $('select[name="audiocodec_sel[4]"]');
      switch (raw_info.audiocodec_sel) {
        case 'DTS-HD': audiocodec_box.val(9); break;
        case 'DTS-HDMA:X 7.1': audiocodec_box.val(9); break;
        case 'DTS-HDMA': case 'DTS-HDHR': audiocodec_box.val(9); break;
        case 'TrueHD': audiocodec_box.val(10); break;
        case 'Atmos': audiocodec_box.val(10); break;
        case 'DTS': audiocodec_box.val(3); break;
        case 'AC3': audiocodec_box.val(8); break;
        case 'AAC': audiocodec_box.val(6); break;
        case 'Flac': audiocodec_box.val(1); break;
        case 'APE': audiocodec_box.val(2); break;
        case 'LPCM': audiocodec_box.val(11); break;
        case 'WAV': audiocodec_box.val(7);
      }
      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = {
        '4K': 5, '1080p': 1, '1080i': 1, '720p': 3
      };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }
      $('select[name="team_sel[4]"]').val(5);
      check_team(raw_info, 'team_sel[4]');
      $('input[name="pt_gen"]').val(raw_info.dburl);

      if (labels.db) {
        $('select[name="processing_sel[4]"]').val(4);
      } else if (labels.hdr10) {
        $('select[name="processing_sel[4]"]').val(2);
      } else if (labels.hdr10plus) {
        $('select[name="processing_sel[4]"]').val(3);
      } else {
        $('select[name="processing_sel[4]"]').val(1);
      }
    }

    else if (forward_site == 'RouSi') {
      var type_dict = { '电影': 'movie', '剧集': 'tv', '动漫': 'animation', '综艺': 'variety', '音乐': 'music', '纪录': 'documentary', '体育': 'sports', '软件': 'software', '学习': 'ebook' };
      var r_type = 'other';
      if (type_dict.hasOwnProperty(raw_info.type)) {
        r_type = type_dict[raw_info.type];
      }
      var standard_dict = { '8K': '其它', '4320p': '其它', '4K': '4K / 2160p', '1080p': '1080p', '1080i': '1080i', '720p': '720p', 'SD': 'SD', '480p': 'SD' };
      var r_standard = '其它';
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        r_standard = standard_dict[raw_info.standard_sel];
      }
      var r_source = '其它';
      switch (raw_info.medium_sel) {
        case 'Blu-ray': case 'Remux': case 'Encode': r_source = 'Blu-ray'; break;
        case 'UHD': r_source = 'UHD Blu-ray'; break;
        case 'WEB-DL': r_source = 'WEB-DL'; break;
        case 'HDTV': r_source = 'HDTV'; break;
        case 'DVD': r_source = 'DVDRip'; break;
      }
      var r_country = '其他';
      const regions = ["大陆", "香港", "台湾", "日本", "韩国", "美国", "英国", "法国", "德国", "意大利", "西班牙", "俄罗斯", "新西兰", "加拿大", "印度", "泰国", "澳大利亚"];
      var reg_region = raw_info.descr.match(/◎(地.{0,10}?区|国.{0,10}?家|产.{0,10}?地|◎產.{0,5}?地)([^\r\n]+)/);
      if (!reg_region) {
        reg_region = raw_info.descr.match(/(地.{0,10}?区|国.{0,10}?家|产.{0,10}?地|◎產.{0,5}?地)([^\r\n]+)/);
      }
      if (reg_region) {
        region = reg_region[2].split('/')[0].trim();
        if (regions.indexOf(region) > -1) {
          r_country = region;
        }
      }
      if (raw_info.source_sel == '大陆') {
        r_country = '大陆';
      }
      function smartFill(input, value, type = 'input') {
        const el = (typeof input === 'string') ? document.querySelector(input) : input;
        if (!el) {
          console.warn(`未找到元素!!`);
          return;
        }
        switch (type) {
          case 'checkbox':
            const targetState = !!value;
            if (el.checked !== targetState) {
              // 直接触发点击，这会带动框架内部的状态更新
              el.click();
            }
            el.dispatchEvent(new Event('change', { bubbles: true }));
            break;
          case 'input': case 'textarea':
            const proto = el.tagName === 'TEXTAREA'
              ? window.HTMLTextAreaElement.prototype
              : window.HTMLInputElement.prototype;
            const setter = Object.getOwnPropertyDescriptor(proto, "value")?.set;
            if (setter) {
              setter.call(el, value);
            } else {
              el.value = value;
            }
            el.dispatchEvent(new Event('input', { bubbles: true }));
            el.dispatchEvent(new Event('change', { bubbles: true }));
            break;
          case 'select':
            el.value = value;
            el.dispatchEvent(new Event('change', { bubbles: true }));
            break;
        }
      }
      function autoClickCategories(introText) {
        const categoryMatch = introText.match(/◎类.*?别\s+([^\n\r]+)/);
        if (!categoryMatch) {
          console.warn("未在简介中找到类别信息");
          return;
        }
        const targetCategories = categoryMatch[1].split(/[ /／]+/).map(s => s.trim());
        console.log("识别到的类型:", targetCategories);
        const buttons = document.querySelectorAll('div.flex.flex-wrap.gap-2 button[type="button"]');

        buttons.forEach(btn => {
          const btnText = btn.textContent.trim();
          if (targetCategories.includes(btnText)) {
            btn.click();
            console.log(`已点击按钮: ${btnText}`);
          }
        });
      }
      const fileWatcher = setInterval(() => {
        const fileInput = document.querySelector('input[type="file"]');
        if (!fileInput) return;
        if (fileInput.files && fileInput.files.length > 0) {
          clearInterval(fileWatcher);
          smartFill('input[placeholder="种子标题"]', raw_info.name, 'input');
          smartFill('input[placeholder="副标题"]', raw_info.small_descr, 'input');
          setTimeout(() => {
            smartFill('input[placeholder="填入 IMDb 链接"]', raw_info.url, 'input');
            smartFill('input[placeholder="填入 豆瓣 链接"]', raw_info.dburl, 'input');
            autoClickCategories(raw_info.descr);
            smartFill('textarea[placeholder="粘贴 MediaInfo 或 BDInfo 信息"]', mediainfo_mteam, 'textarea');
            smartFill('textarea[placeholder*="种子描述"]', raw_info.descr, 'textarea');
            if (if_uplver) {
              const anonCheckbox = Array.from(document.querySelectorAll('label'))
                .find(l => l.innerText.includes('匿名上传'))
                ?.querySelector('input');
              smartFill(anonCheckbox, true, 'checkbox');
            }
          }, 1500);
          smartFill(document.querySelectorAll('select')[0], r_type, 'select');
          smartFill(document.querySelectorAll('select')[1], r_country, 'select');
          smartFill(document.querySelectorAll('select')[2], r_standard, 'select');
          smartFill(document.querySelectorAll('select')[3], r_source, 'select');
        }
      }, 1000);
    }

    else if (forward_site == '财神') {
      //类型
      var browsecat = $('#browsecat')
      var type_dict = {
        '电影': 401, '剧集': 402, '动漫': 405, '综艺': 403, '音乐': 408, '纪录': 404,
        '体育': 407, 'MV': 406
      };
      browsecat.val(410);
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      //媒介
      var medium_box = $('select[name="source_sel[4]"]');
      medium_box.val(16);
      switch (raw_info.medium_sel) {
        case 'Blu-ray': medium_box.val(7); break;
        case 'UHD': medium_box.val(8); break;
        case 'Remux': medium_box.val(9); break;
        case 'Encode': medium_box.val(10); break;
        case 'WEB-DL': medium_box.val(11); break;
        case 'HDTV': medium_box.val(12); break;
        case 'DVD': medium_box.val(13); break;
        case 'CD': medium_box.val(14); break;
      }
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(5);
      switch (raw_info.codec_sel) {
        case 'H264': case 'X264': codec_box.val(1); break;
        case 'H265': case 'X265': codec_box.val(2); break;
        case 'VC-1': codec_box.val(3); break;
        case 'MPEG-2': codec_box.val(4); break;
        case 'AV1': codec_box.val(6); break;
      }
      //音频编码
      var audiocodec_box = $('select[name="audiocodec_sel[4]"]');
      audiocodec_box.val(13);
      switch (raw_info.audiocodec_sel) {
        case 'AAC': audiocodec_box.val(9); break;
        case 'APE': audiocodec_box.val(10); break;
        case 'AC3':
          audiocodec_box.val(13);
          if (raw_info.name.match(/DD[P\+]/)) {
            audiocodec_box.val(12);
          }
          break;
        case 'Atmos': audiocodec_box.val(11); break;
        case 'LPCM': audiocodec_box.val(14); break;
        case 'TrueHD': audiocodec_box.val(15); break;
        case 'DTS:X': audiocodec_box.val(16); break;
        case 'DTS-HDMA': case 'DTS-HDHR': audiocodec_box.val(17); break;
        case 'DTS': audiocodec_box.val(18); break;
        case 'M4A': audiocodec_box.val(19); break;
        case 'WAV': audiocodec_box.val(20); break;
        case 'MP3': audiocodec_box.val(21); break;
        case 'Flac': audiocodec_box.val(22); break;
      }
      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = { '8K': 8, '4320p': 8, '4K': 7, '2160p': 7, '1080p': 6, '1080i': 6, '720p': 5, 'SD': 4, '480p': 4, '': 9 };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }
      //制作组
      $('select[name="team_sel[4]"]').val(5);
      check_team(raw_info, 'team_sel[4]');
    }
    else if (forward_site == '下水道') {
      //类型
      var browsecat = $('#browsecat')
      var type_dict = {
        '电影': 401, '剧集': 402, '动漫': 405, '综艺': 403, '音乐': 408, '纪录': 404,
        '体育': 409, 'MV': 409
      };
      browsecat.val(409);
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      //媒介
      var medium_box = $('select[name="medium_sel[4]"]');
      medium_box.val(16);
      switch (raw_info.medium_sel) {
        case 'Blu-ray': medium_box.val(1); break;
        case 'UHD': medium_box.val(1); break;
        case 'Remux': medium_box.val(3); break;
        case 'Encode': medium_box.val(7); break;
        case 'WEB-DL': medium_box.val(10); break;
        case 'HDTV': medium_box.val(5); break;
        case 'DVD': medium_box.val(6); break;
        case 'CD': medium_box.val(8); break;
      }
      if (raw_info.name.match(/HD DVD/)) {
        medium_box.val(2);
      }
      if (raw_info.name.match(/minihd/i)) {
        medium_box.val(4);
      }
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(5);
      switch (raw_info.codec_sel) {
        case 'H264': case 'X264': codec_box.val(1); break;
        case 'H265': case 'X265': codec_box.val(6); break;
        case 'VC-1': codec_box.val(2); break;
        case 'MPEG-2': codec_box.val(4); break;
        case 'AV1': codec_box.val(5); break;
        case 'XVID': codec_box.val(3);
      }
      //音频编码
      var audiocodec_box = $('select[name="audiocodec_sel[4]"]');
      audiocodec_box.val(7);
      switch (raw_info.audiocodec_sel) {
        case 'AAC': audiocodec_box.val(6); break;
        case 'APE': audiocodec_box.val(2); break;
        case 'AC3':
          audiocodec_box.val(8);
          if (raw_info.name.match(/DD[P\+]/)) {
            audiocodec_box.val(11);
          }
          break;
        case 'Atmos': audiocodec_box.val(11); break;
        case 'LPCM': audiocodec_box.val(16); break;
        case 'TrueHD': audiocodec_box.val(13); break;
        case 'Atmos':
          audiocodec_box.val(13);
          if (raw_info.name.match(/DD[\+P]/i)) {
            audiocodec_box.val(11);
          }
          break;
        case 'DTS:X': audiocodec_box.val(15); break;
        case 'DTS-HDMA': case 'DTS-HDHR': audiocodec_box.val(14); break;
        case 'DTS': audiocodec_box.val(3); break;
        case 'M4A': audiocodec_box.val(7); break;
        case 'WAV': audiocodec_box.val(10); break;
        case 'MP3': audiocodec_box.val(4); break;
        case 'Flac': audiocodec_box.val(1); break;
        case 'OCG': audiocodec_box.val(5); break;
        case 'ALAC': audiocodec_box.val(9); break;
        case 'AV3V': audiocodec_box.val(17); break;
        case 'OPUS': audiocodec_box.val(18); break;
      }
      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = { '8K': 6, '4320p': 6, '4K': 5, '2160p': 5, '2K': 4, '1440p': 4, '1080p': 1, '1080i': 1, '720p': 3, '720i': 3, 'SD': 2, '480p': 2, '480i': 2, '': 0 };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }
      //制作组
      $('select[name="team_sel[4]"]').val(5);
      check_team(raw_info, 'team_sel[4]');
    }

    else if (forward_site == '唐门') {
      var browsecat = $('#browsecat')
      var type_dict = { '': 409, '音乐': 408, 'MV': 406, '体育': 407, '纪录': 404, '动漫': 405, '综艺': 403, '剧集': 402, '电影': 401 };
      browsecat.val(409)
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      try { disableother('browsecat', 'specialcat'); } catch (err) { }
      $('select[name="team_sel[4]"]').val(5);
      check_team(raw_info, 'team_sel[4]');
      var medium_box = $('select[name="medium_sel[4]"]');
      switch (raw_info.medium_sel) {
        case 'UHD': medium_box.val(10); break;
        case 'Blu-ray': medium_box.val(11); break;
        case 'Remux': medium_box.val(12); break
        case 'Encode': medium_box.val(13); break;
        case 'WEB-DL': medium_box.val(14); break;
        case 'HDTV': medium_box.val(15); break;
        case 'DVD':
          if (raw_info.name.match(/dvdr/i)) {
            medium_box.val(16);
          } else {
            medium_box.val(16);
          }
          break;
        case 'CD': medium_box.val(17); break;

      }
      if (raw_info.name.match(/MiniBD/i)) {
        medium_box.val(4);
      }
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(11);
      switch (raw_info.codec_sel) {
        case 'H264': case 'X264': codec_box.val(6); break;
        case 'H265': case 'X265': codec_box.val(7); break;
        case 'VC-1': codec_box.val(8); break;
        case 'MPEG-2': case 'MPEG-4': codec_box.val(9); break;
        case 'AV1': codec_box.val(10);
      }
      var audiocodec_box = $('select[name="audiocodec_sel[4]"]');
      audiocodec_box.val(23);
      switch (raw_info.audiocodec_sel) {
        case 'AAC': audiocodec_box.val(9); break;
        case 'APE': audiocodec_box.val(10); break;
        case 'Atmos': audiocodec_box.val(11); break;
        case 'AC3':
          audiocodec_box.val(13);
          if (raw_info.name.match(/DD[P\+]/)) {
            audiocodec_box.val(12);
          }
          break;
        case 'LPCM': audiocodec_box.val(14); break;
        case 'TrueHD': audiocodec_box.val(15); break;
        case 'DTS-X': audiocodec_box.val(16); break;
        case 'DTS-HDMA': audiocodec_box.val(17); break;
        case 'DTS-HDHR': audiocodec_box.val(17); break;
        case 'DTS': audiocodec_box.val(18); break;
        case 'M4A': audiocodec_box.val(19); break;
        case 'WAV': audiocodec_box.val(20); break;
        case 'MP3': audiocodec_box.val(21); break;
        case 'Flac': audiocodec_box.val(22); break;
      }
      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = { '8K': 9, '4K': 8, '1080p': 7, '1080i': 7, '720p': 6, '720i': 6, 'SD': 5, 'Other': 10 };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }
      try {
        var year = raw_info.name.match(/\d{4}[^pi]/gi).pop().slice(0, 4);
        year = parseInt(year);
        var years = [2011, 2001, 1981, 1961, 1941, 1921, 1901, 1851, 1800];
        var year_selected = false;
        years.forEach((item, index) => {
          if (year > item && !year_selected) {
            $('select[name="processing_sel[5]"]').val(9 - index);
            year_selected = true;
          }
        });
      } catch (err) { }
    }


    else if (forward_site == 'ZMPT') {
      var browsecat = $('#browsecat');
      var type_dict = {
        '电影': 401, '剧集': 402, '动漫': 417, '综艺': 403, '音乐': 423, '纪录': 422,
        '体育': 409, '软件': 425, '游戏': 426, 'MV': 423
      };
      browsecat.val(409)
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }

      if (raw_info.type == '书籍' && raw_info.descr.match(/m4a|mp3/i)) {
        browsecat.val(424);
      }
      var medium_box = $('select[name="medium_sel[4]"]');
      switch (raw_info.medium_sel) {
        case 'UHD': medium_box.val(1); break;
        case 'Blu-ray': medium_box.val(1); break;
        case 'DVD':
          medium_box.val(2);
          if (raw_info.name.match(/DVDr/i)) {
            medium_box.val(6);
          }
          break;
        case 'Remux': medium_box.val(3); break;
        case 'HDTV': medium_box.val(5); break;
        case 'Encode': medium_box.val(7); break;
        case 'WEB-DL': medium_box.val(10); break;
        case 'CD': medium_sel.val(8);
      }
      if (raw_info.name.match(/MiniBD/i)) {
        medium_box.val(4);
      }
      var audiocodec_box = $('select[name="audiocodec_sel[4]"]');
      switch (raw_info.audiocodec_sel) {
        case 'DTS-HD': case 'DTS-HDMA:X 7.1': case 'DTS-HDMA': audiocodec_box.val(3); break;
        case 'TrueHD': audiocodec_box.val(7); break;
        case 'Atmos': audiocodec_box.val(7); break;
        case 'DTS': audiocodec_box.val(3); break;
        case 'AC3': audiocodec_box.val(8); break;
        case 'AAC': audiocodec_box.val(6); break;
        case 'Flac': audiocodec_box.val(1); break;
        case 'APE': audiocodec_box.val(2); break;
        case 'LPCM': audiocodec_box.val(7); break;
        case 'WAV': audiocodec_box.val(7);
      }

      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = {
        '4K': 5, '1080p': 1, '1080i': 1, '720p': 8, 'SD': 7,
      };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }
      $('select[name="team_sel[4]"]').val(5);
      check_team(raw_info, 'team_sel[4]');
    }

    else if (forward_site == 'ICC') {
      var browsecat = $('#browsecat')
      var type_dict = {
        '电影': 401, '剧集': 402, '动漫': 405, '综艺': 403, '音乐': 408, '纪录': 404,
        '体育': 407, '软件': 409, '学习': 409, '': 409, '游戏': 409, 'MV': 406
      };
      browsecat.val(409)
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      try { disableother('browsecat', 'specialcat'); } catch (err) { }
      $('select[name="team_sel[4]"]').val(5);
      check_team(raw_info, 'team_sel[4]');
      var medium_box = $('select[name="medium_sel[4]"]');
      switch (raw_info.medium_sel) {
        case 'UHD': case 'Blu-ray':
          medium_box.val(1); break;
        case 'DVD':
          if (raw_info.name.match(/dvdr/i)) {
            medium_box.val(6);
          } else {
            medium_box.val(2);
          }
          break;
        case 'Remux': medium_box.val(3); break
        case 'HDTV': medium_box.val(5); break;
        case 'Encode': medium_box.val(7); break;
        case 'WEB-DL': medium_box.val(10); break;
        case 'CD': medium_box.val(8);
      }
      if (raw_info.name.match(/MiniBD/i)) {
        medium_box.val(4);
      }
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(5);
      switch (raw_info.codec_sel) {
        case 'H265': case 'X265': codec_box.val(6); break;
        case 'H264': case 'X264': codec_box.val(1); break;
        case 'VC-1': codec_box.val(2); break;
        case 'MPEG-2': case 'MPEG-4': codec_box.val(4); break;
        case 'XVID': codec_box.val(3);
      }
      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = {
        '4K': 6, '1080p': 1, '1080i': 2, '720p': 3, 'SD': 4
      };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }
      try {
        var year = raw_info.name.match(/\d{4}[^pi]/gi).pop().slice(0, 4);
        year = parseInt(year);
        var years = [2011, 2001, 1981, 1961, 1941, 1921, 1901, 1851, 1800];
        var year_selected = false;
        years.forEach((item, index) => {
          if (year > item && !year_selected) {
            $('select[name="processing_sel[5]"]').val(9 - index);
            year_selected = true;
          }
        });
      } catch (err) { }
    }

    else if (forward_site == '海棠') {
      var string = raw_info.name + raw_info.small_descr + raw_info.descr;
      if (string.match(/相声/)) {
        $('#browsecat').val(1);
      } else if (string.match(/小品/)) {
        $('#browsecat').val(4101);
      }
      try { disableother('browsecat', 'specialcat') } catch (err) { }

      var codec_box = document.getElementsByName('codec_sel')[0];
      switch (raw_info.codec_sel) {
        case 'H265': case 'X265': codec_box.options[2].selected = true; break;
        case 'H264': case 'X264': codec_box.options[1].selected = true; break;
      }
      var standard_box = $('select[name=standard_sel]');
      var standard_dict = {
        '4K': 1, '1080p': 2, '1080i': 2, '720p': 3, 'SD': 4
      };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }
    }

    else if (forward_site == '麒麟') {
      var browsecat = $('#browsecat')
      var type_dict = { '电影': 401, '剧集': 402, '动漫': 405, '综艺': 420, '音乐': 408, '纪录': 404, '体育': 407, '软件': 411, '学习': 419, '': 409, '游戏': 412, 'MV': 406, '短剧': 421 };
      browsecat.val(409)
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      try {
        $('select[name="processing_sel[4]"]').val(9);
        var year = raw_info.name.match(/(19|20)\d{2}/g).pop();
        $('select[name="processing_sel[4]"]>option').map(function (index, e) {
          if (e.innerText.match(year)) {
            $(`select[name="processing_sel[4]"]>option:eq(${index})`).attr('selected', true);
          }
        });
      } catch (Err) { }
      //媒介
      var medium_box = $('select[name="medium_sel[4]"]');
      switch (raw_info.medium_sel) {
        case 'UHD': medium_box.val(24); break;
        case 'Blu-ray':
          medium_box.val(25);
          if (labels.diy) {
            medium_box.val(26);
          }
          break;
        case 'DVD': medium_box.val(27); break;
        case 'Remux': medium_box.val(30); break;
        case 'HDTV': medium_box.val(28); break;
        case 'Encode': medium_box.val(29); break;
        case 'WEB-DL': medium_box.val(31); break;
        case 'CD': medium_box.val(33);
      }
      if (raw_info.name.match(/webrip/i)) {
        medium_box.val(29);
      }
      //视频编码
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(5);
      switch (raw_info.codec_sel) {
        case 'H265': case 'X265': codec_box.val(6); break;
        case 'H264': case 'X264': codec_box.val(1); break;
        case 'VC-1': codec_box.val(2); break;
        case 'MPEG-2': case 'MPEG-4': codec_box.val(4); break;
        case 'XVID': codec_box.val(3);
      }
      //音频编码
      var audiocodec_box = $('select[name="audiocodec_sel[4]"]');
      switch (raw_info.audiocodec_sel) {
        case 'DTS-HD': audiocodec_box.val(13); break;
        case 'DTS-HDMA:X 7.1': audiocodec_box.val(8); break;
        case 'DTS-HDMA': audiocodec_box.val(8); break;
        case 'DTS-HDHR': audiocodec_box.val(19); break;
        case 'TrueHD': audiocodec_box.val(9); break;
        case 'Atmos':
          audiocodec_box.val(15);
          if (raw_info.name.match(/DD[\+P]/i)) {
            audiocodec_box.val(17);
          }
          break;
        case 'DTS': audiocodec_box.val(3); break;
        case 'AC3':
          audiocodec_box.val(11);
          if (raw_info.name.match(/DD[\+P]/i)) {
            audiocodec_box.val(17);
          }
          break;
        case 'AAC': audiocodec_box.val(6); break;
        case 'Flac': audiocodec_box.val(1); break;
        case 'APE': audiocodec_box.val(12); break;
        case 'LPCM': audiocodec_box.val(10); break;
        case 'WAV': audiocodec_box.val(13);
      }
      //分辨率
      var standard_box = $('select[name="standard_sel[4]"]');
      standard_box.val(9);
      var standard_dict = { '4K': 6, '1080p': 1, '1080i': 1, '720p': 3, 'SD': 8 };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }
      var source_box = $('select[name="source_sel[4]"]');
      switch (raw_info.source_sel) {
        case '大陆': source_box.val(15); break;
        case '香港': source_box.val(16); break;
        case '台湾': source_box.val(17); break;
        case '日本': source_box.val(19); break;
        case '韩国': source_box.val(20); break;
        default:
          try {
            var reg_region = raw_info.descr.match(/(地.{0,5}?区|国.{0,5}?家|产.{0,5}?地|◎產.{0,5}?地)([^\r\n]+)/);
            if (reg_region) {
              region = reg_region[2].split('/')[0].trim();
              region = region.split(':').pop().trim();
              $('select[name="source_sel[4]"]>option').map(function (index, e) {
                if (region.match(e.innerText.split('/').pop())) {
                  $(`select[name="source_sel[4]"]>option:eq(${index})`).attr('selected', true);
                }
              });
            }
          } catch (err) { }
      }
      if (source_box.val() == 0) {
        source_box.val(14);
      }
      $('select[name="team_sel[4]"]').val(5);
      check_team(raw_info, 'team_sel[4]');
    }

    else if (forward_site == 'CarPt') {
      //类型
      var browsecat = $('#browsecat')
      var type_dict = {
        '电影': 401, '剧集': 402, '动漫': 403, '综艺': 405, '音乐': 406, '纪录': 404,
        '体育': 407, '软件': 407, '学习': 407, '': 407, '游戏': 407, 'MV': 406
      };
      browsecat.val(407);
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      //媒介
      var medium_box = $('select[name="medium_sel[4]"]');
      switch (raw_info.medium_sel) {
        case 'UHD': medium_box.val(8); break;
        case 'Blu-ray': medium_box.val(7); break;
        case 'DVD':
          medium_box.val(4);
          if (raw_info.name.match(/DVDr/i)) {
            medium_box.val(4);
          }
          break;
        case 'Remux': medium_box.val(9); break;
        case 'HDTV': medium_box.val(3); break;
        case 'Encode': medium_box.val(1); break;
        case 'WEB-DL': medium_box.val(2); break;
        case 'CD': medium_box.val(8);
      }
      //视频编码
      var codec_box = document.getElementsByName('codec_sel[4]')[0];
      codec_box.options[6].selected = true;
      switch (raw_info.codec_sel) {
        case 'H265': case 'X265': codec_box.options[2].selected = true; break;
        case 'H264': case 'X264': codec_box.options[1].selected = true; break;
        case 'VC-1': codec_box.options[4].selected = true; break;
        case 'MPEG-2': case 'MPEG-4': codec_box.options[3].selected = true; break;
        case 'XVID': codec_box.options[5].selected = true;
      }
      //音频编码
      var audiocodec_box = document.getElementsByName('audiocodec_sel[4]')[0];
      switch (raw_info.audiocodec_sel) {
        case 'DTS-HD': audiocodec_box.options[2].selected = true; break;
        case 'DTS-HDMA:X 7.1': audiocodec_box.options[2].selected = true; break;
        case 'DTS-HDMA': case 'DTS-HDHR': audiocodec_box.options[2].selected = true; break;
        case 'TrueHD': audiocodec_box.options[1].selected = true; break;
        case 'Atmos': audiocodec_box.options[1].selected = true; break;
        case 'DTS': audiocodec_box.options[2].selected = true; break;
        case 'AC3': audiocodec_box.options[3].selected = true; break;
        case 'LPCM': audiocodec_box.options[4].selected = true; break;
        case 'AAC': audiocodec_box.options[7].selected = true; break;
        case 'Flac': audiocodec_box.options[5].selected = true; break;
        case 'APE': audiocodec_box.options[8].selected = true; break;
        case 'WAV': audiocodec_box.options[9].selected = true;
      }
      //分辨率
      var standard_box = document.getElementsByName('standard_sel[4]')[0];
      var standard_dict = {
        '4K': 1, '1080p': 2, '1080i': 2, '720p': 3, 'SD': 4, '': 5
      };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.options[index].selected = true;
      }
      $('select[name="team_sel[4]"]').val(5);
      check_team(raw_info, 'team_sel[4]');
    }

    else if (forward_site == 'JoyHD') {

      $('input[name="imdburl"]').val(raw_info.url);
      //类型
      var browsecat = document.getElementsByName('type')[0];
      var type_dict = {
        '电影': 1, '剧集': 2, '动漫': 4, '综艺': 3, '音乐': 5, '纪录': 7,
        '体育': 6, '软件': 9, '学习': 11, '': 12, '游戏': 10, 'MV': 8
      };
      //如果当前类型在上述字典中
      browsecat.options[12].selected = true;//默认其他
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.options[index].selected = true;
      }

      document.getElementById('browsecat').dispatchEvent(evt);
      var medium_box = document.getElementsByName('source_sel')[0];
      switch (raw_info.type) {
        case '电影':
          switch (raw_info.medium_sel) {
            case 'UHD': case 'Blu-ray': medium_box.options[5].selected = true; break;
            case 'DVD': medium_box.options[8].selected = true; break;
            case 'Remux': medium_box.options[6].selected = true; break;
            case 'HDTV': medium_box.options[9].selected = true; break;
            case 'WEB-DL': medium_box.options[4].selected = true; break;
            case 'Encode':
              if (raw_info.standard_sel == '1080p') {
                medium_box.options[2].selected = true;
              } else if (raw_info.standard_sel == '720p') {
                medium_box.options[1].selected = true;
              } else if (raw_info.standard_sel == '4K') {
                medium_box.options[11].selected = true;
              }
              if (raw_info.name.match(/pad$|ipad/i)) {
                medium_box.options[12].selected = true;
              }
              break;
            default:
              if (raw_info.standard_sel == '1080p') {
                medium_box.options[2].selected = true;
              } else if (raw_info.standard_sel == '720p') {
                medium_box.options[1].selected = true;
              } else if (raw_info.standard_sel == '4K') {
                medium_box.options[11].selected = true;
              }
          }
          if (raw_info.name.match(/10bit/)) {
            medium_box.options[3].selected = true;
          } else if (raw_info.name.match(/BDRIP/i)) {
            medium_box.options[10].selected = true;
          }

          break;
        case '剧集':
          switch (raw_info.source_sel) {
            case '大陆': medium_box.options[2].selected = true; break;
            case '台湾': case '香港': case '港台': medium_box.options[3].selected = true; break;
            case '日本': medium_box.options[5].selected = true; break;
            case '韩国': medium_box.options[6].selected = true; break;
            case '欧美': medium_box.options[4].selected = true; break;
          }
          if (raw_info.name.match(/S\d+[^E]|complete/i)) {
            medium_box.options[1].selected = true;
          }
          break;
        case '综艺': medium_box.options[2].selected = true; break;
        case '纪录': medium_box.options[7].selected = true; break;
        case '动漫': medium_box.options[2].selected = true; break;
        case '音乐': medium_box.options[1].selected = true; break;
        case '体育': case '学习': case '软件': medium_box.options[4].selected = true; break;
      }
      $('select[name="team_sel"]').val(13);
      check_team(raw_info, 'team_sel');
    }

    else if (forward_site == 'Oshen') {
      //类型
      var browsecat = $('#browsecat');
      var type_dict = {
        '电影': 401, '剧集': 402, '动漫': 405, '综艺': 403, '音乐': 408, '纪录': 404,
        '体育': 407, '软件': 409, '学习': 409, '': 409, '游戏': 410, 'MV': 406
      };
      //如果当前类型在上述字典中
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      //媒介
      var medium_box = $('select[name="medium_sel[4]"]');
      switch (raw_info.medium_sel) {
        case 'UHD': case 'Blu-ray': medium_box.val(1); break;
        case 'DVD':
          if (raw_info.name.match(/HD ?DVD/i)) {
            medium_box.val(2);
          } else {
            medium_box.val(6);
          }
          break;
        case 'Remux': medium_box.val(3); break;
        case 'HDTV': medium_box.val(5); break;
        case 'Encode': medium_box.val(7); break;
        case 'CD': medium_box.val(8);
      }
      if (raw_info.name.match(/MiniBD/i)) {
        medium_box.val(4);
      }

      //视频编码
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(5);
      switch (raw_info.codec_sel) {
        case 'H264': case 'X264': codec_box.val(1); break;
        case 'H265': case 'X265': codec_box.val(10); break;
        case 'VC-1': codec_box.val(2); break;
        case 'MPEG-2': codec_box.val(4); break;
        case 'XVID': codec_box.val(3);
      }

      //分辨率
      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = { '4K': 5, '1080p': 1, '1080i': 2, '720p': 3, 'SD': 4 };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }

      $('select[name="team_sel[4]"]').val(5);
      check_team(raw_info, 'team_sel[4]');
    }

    else if (forward_site == 'CrabPt') {
      //类型
      var browsecat = $('#browsecat')
      var type_dict = {
        '电影': 401, '剧集': 402, '动漫': 405, '综艺': 403, '音乐': 408, '纪录': 404,
        '体育': 407, '软件': 409, '学习': 409, '': 409, '游戏': 409, 'MV': 406
      };
      //如果当前类型在上述字典中
      browsecat.val(409);
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      try { disableother('browsecat', 'specialcat'); } catch (err) { }
      //媒介
      var medium_box = $('select[name="source_sel[4]"]');
      medium_box.val(1);
      if (raw_info.medium_sel == 'UHD') {
        medium_box.val(3);
      } else if (raw_info.medium_sel == 'Blu-ray') {
        medium_box.val(2);
      } else if (raw_info.medium_sel == 'Remux') {
        medium_box.val(4);
      } else if (raw_info.medium_sel == 'Encode') {
        medium_box.val(5);
      } else if (raw_info.medium_sel == 'WEB-DL') {
        medium_box.val(6);
      } else if (raw_info.medium_sel == 'HDTV') {
        medium_box.val(7);
      } else if (raw_info.medium_sel == 'CD') {
        medium_box.val(8);
      }

      //编码
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(1);
      switch (raw_info.codec_sel) {
        case 'H265': case 'X265': codec_box.val(3); break;
        case 'H264': case 'X264': codec_box.val(2); break;
        case 'VP9': codec_box.val(5); break;
        case 'AV1': codec_box.val(6); break;
      }
      if (raw_info.name.match(/H.?266/)) { codec_box.val(4); }

      //分辨率
      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = { '8K': 5, '4K': 4, '1080p': 3, '1080i': 3, '720p': 2, 'SD': 1, '': 1 };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }

      //音频编码
      var audiocodec_box = $('select[name="audiocodec_sel[4]"]');
      switch (raw_info.audiocodec_sel) {
        case 'DTS-HD': audiocodec_box.val(15); break;
        case 'DTS-HDMA:X 7.1': audiocodec_box.val(8); break;
        case 'DTS-HDMA': case 'DTS-HDHR': audiocodec_box.val(17); break;
        case 'TrueHD': audiocodec_box.val(6); break;
        case 'DTS': audiocodec_box.val(5); break;
        case 'AC3':
          audiocodec_box.val(3);
          if (raw_info.name.match(/DD[P\+]/)) {
            audiocodec_box.val(4);
          }
          break;
        case 'AAC': audiocodec_box.val(2); break;
        case 'Flac': audiocodec_box.val(10); break;
        case 'APE': audiocodec_box.val(12); break;
        case 'LPCM': audiocodec_box.val(7); break;
        case 'WAV': audiocodec_box.val(11); break;
        case 'Atmos': audiocodec_box.val(26); break;
      }

      //制作组
      $('select[name="team_sel[4]"]').val(1);
      check_team(raw_info, 'team_sel[4]');

      var processing_box = $('select[name="processing_sel[4]"]');
      processing_box.val(1);
      var processing_dict = {
        '欧美': 4, '大陆': 2, '香港': 3, '台湾': 3, '日本': 5, '韩国': 6,
        '印度': 7, '': 1, '港台': 3
      };
      if (processing_dict.hasOwnProperty(raw_info.source_sel)) {
        var index = processing_dict[raw_info.source_sel];
        processing_box.val(index);
      }
    }

    else if (forward_site == 'QingWa') {
      //类型
      var browsecat = $('#browsecat')
      var type_dict = {
        '电影': 401, '剧集': 402, '动漫': 405, '综艺': 403, '音乐': 408, '纪录': 404,
        '体育': 407, '软件': 409, '学习': 409, '': 409, '游戏': 409, 'MV': 406
      };
      //如果当前类型在上述字典中
      browsecat.val(409);
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      try { disableother('browsecat', 'specialcat'); } catch (err) { }
      //媒介
      var medium_box = $('select[name="source_sel[4]"]');
      medium_box.val(6);
      switch (raw_info.medium_sel) {
        case 'UHD': medium_box.val(1); break;
        case 'Blu-ray': medium_box.val(8); break;
        case 'Remux': medium_box.val(9); break;
        case 'Encode': medium_box.val(10); break;
        case 'WEB-DL': medium_box.val(7); break;
        case 'HDTV': medium_box.val(4); break;
        case 'DVD': medium_box.val(2); break;
        case 'CD': medium_box.val(3); break;
      }

      //编码
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(5);
      switch (raw_info.codec_sel) {
        case 'H265': case 'X265': codec_box.val(6); break;
        case 'H264': case 'X264': codec_box.val(1); break;
        case 'VC-1': codec_box.val(2); break;
        case 'MPEG-2': codec_box.val(4); break;
        case 'MPEG-4': codec_box.val(3); break;
        case 'VP9': codec_box.val(8); break;
        case 'AV1': codec_box.val(7); break;
      }

      //分辨率
      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = { '8K': 6, '4K': 7, '1080p': 1, '1080i': 2, '720p': 3, 'SD': 4, '': 5 };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }

      //音频编码
      var audiocodec_box = $('select[name="audiocodec_sel[4]"]');
      audiocodec_box.val(7);
      switch (raw_info.audiocodec_sel) {
        case 'DTS-HD': audiocodec_box.val(5); break;
        case 'DTS-HDMA:X 7.1': audiocodec_box.val(9); break;
        case 'DTS-HDMA': case 'DTS-HDHR': audiocodec_box.val(10); break;
        case 'TrueHD': audiocodec_box.val(12); break;
        case 'DTS': audiocodec_box.val(14); break;
        case 'AC3':
          audiocodec_box.val(15);
          if (raw_info.name.match(/DD[P\+]/)) {
            audiocodec_box.val(16);
          }
          break;
        case 'AAC': audiocodec_box.val(17); break;
        case 'Flac': audiocodec_box.val(1); break;
        case 'APE': audiocodec_box.val(18); break;
        case 'LPCM': audiocodec_box.val(13); break;
        case 'OPUS': audiocodec_box.val(20); break;
        case 'WAV': audiocodec_box.val(19); break;
        case 'Atmos':
          var info_plus = raw_info.name + raw_info.descr + $('textarea[name="technical_info"]').val();
          if (info_plus.match(/True.?HD/i)) {
            audiocodec_box.val(11);
          }
          break;
        case 'MP3': audiocodec_box.val(4); break;
      }

      //制作组
      $('select[name="team_sel[4]"]').val(5);
      check_team(raw_info, 'team_sel[4]');
    }

    else if (forward_site == '52MOVIE') {
      //类型
      var browsecat = $('#browsecat')
      var type_dict = {
        '电影': 401, '剧集': 402, '动漫': 405, '综艺': 403, '音乐': 408, '纪录': 404,
        '体育': 410, '短剧': 402, '软件': 411, '学习': 411, '': 411, '游戏': 411, 'MV': 406
      };
      browsecat.val(411);
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      try { disableother('browsecat', 'specialcat'); } catch (err) { }
      //媒介
      var medium_box = $('select[name="medium_sel[4]"]');
      medium_box.val(11);
      switch (raw_info.medium_sel) {
        case 'UHD': medium_box.val(1); break;
        case 'Blu-ray': medium_box.val(1); break;
        case 'Remux': medium_box.val(3); break;
        case 'Encode': medium_box.val(7); break;
        case 'WEB-DL': medium_box.val(10); break;
        case 'HDTV': medium_box.val(5); break;
        case 'DVD': medium_box.val(6); break;
        case 'CD': medium_box.val(8); break;
      }

      //编码
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(9);
      switch (raw_info.codec_sel) {
        case 'H265': case 'X265': codec_box.val(1); break;
        case 'H264': case 'X264': codec_box.val(2); break;
        case 'VC-1': codec_box.val(3); break;
        case 'XVID': codec_box.val(5); break;
        case 'MPEG-2': codec_box.val(4); break;
        case 'MPEG-4': codec_box.val(9); break;
        case 'VP9': codec_box.val(7); break;
        case 'VP8': codec_box.val(7); break;
        case 'AVS': codec_box.val(8); break;
        case 'AV1': codec_box.val(6); break;
      }

      //分辨率
      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = { '8K': 6, '4K': 5, '1080p': 1, '1080i': 2, '720p': 3, 'SD': 4, '': 0 };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }

      //音频编码
      var audiocodec_box = $('select[name="audiocodec_sel[4]"]');
      audiocodec_box.val(15);
      switch (raw_info.audiocodec_sel) {
        case 'DTS-HD': audiocodec_box.val(4); break;
        case 'DTS-HDMA:X 7.1': audiocodec_box.val(4); break;
        case 'DTS-HDMA': case 'DTS-HDHR': audiocodec_box.val(4); break;
        case 'TrueHD': audiocodec_box.val(7); break;
        case 'DTS': audiocodec_box.val(3); break;
        case 'Atmos':
          audiocodec_box.val(6);
          if (raw_info.name.match(/TrueHD/)) {
            audiocodec_box.val(8);
          }
          break;
        case 'AC3':
          audiocodec_box.val(2);
          if (raw_info.name.match(/DD[P\+]/)) {
            audiocodec_box.val(5);
            if (raw_info.name.match(/atmos/i) || raw_info.descr.match(/atmos/i)) {
              audiocodec_box.val(6);
            }
          }
          break;
        case 'AAC': audiocodec_box.val(1); break;
        case 'Flac': audiocodec_box.val(11); break;
        case 'APE': audiocodec_box.val(12); break;
        case 'LPCM': audiocodec_box.val(9); break;
        case 'MP2': audiocodec_box.val(13); break;
        case 'OGG': audiocodec_box.val(14); break;
        case 'WAV': audiocodec_box.val(10); break;
        case 'MP3': audiocodec_box.val(13); break;
      }
    }

    else if (forward_site == 'PTFans') {
      var browsecat = $('#browsecat')
      var type_dict = {
        '电影': 401, '剧集': 404, '动漫': 415, '综艺': 405, '音乐': 407, '纪录': 406,
        '体育': 403, 'MV': 407
      };
      browsecat.val(419);
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      disableother('browsecat', 'specialcat');
      var medium_box = $('select[name="medium_sel[4]"]');
      medium_box.val(8);
      switch (raw_info.medium_sel) {
        case 'UHD': case 'Blu-ray': medium_box.val(6); break;
        case 'Remux': medium_box.val(3); break;
        case 'Encode': medium_box.val(7); break;
        case 'WEB-DL': medium_box.val(5); break;
        case 'HDTV': medium_box.val(8); break;
        case 'DVD': medium_box.val(2); break;
        case 'CD': medium_box.val(1); break;
      }
      if (raw_info.name.match(/MiniBD/)) {
        medium_box.val(4);
      }
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(9);
      switch (raw_info.codec_sel) {
        case 'H265': case 'X265':
          codec_box.val(2);
          if (raw_info.medium_sel == 'Blu-ray' || raw_info.medium_sel == 'UHD') {
            codec_box.val(5);
          }
          break;
        case 'H264': case 'X264':
          codec_box.val(1);
          if (raw_info.medium_sel == 'Blu-ray' || raw_info.medium_sel == 'UHD') {
            codec_box.val(4);
          }
          break;
        case 'VC-1': codec_box.val(3); break;
        case 'MPEG-2': case 'MPEG-4': codec_box.val(6); break;
        case 'AV1': codec_box.val(8); break;
      }

      //制作组
      $('select[name="team_sel[4]"]').val(5);
      check_team(raw_info, 'team_sel[4]');

      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = { '8K': 6, '4K': 5, '1080p': 1, '1080i': 2, '720p': 3, 'SD': 4, '': 4 };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }
    }

    else if (forward_site == 'PTzone') {
      //类型
      var browsecat = $('#browsecat')
      var type_dict = {
        '电影': 401, '剧集': 402, '动漫': 405, '综艺': 403, '音乐': 406, '纪录': 404,
        '体育': 407, 'MV': 406
      };
      browsecat.val(408);
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      //媒介
      var medium_box = $('select[name="medium_sel[4]"]');
      medium_box.val(8);
      switch (raw_info.medium_sel) {
        case 'UHD': medium_box.val(10); break;
        case 'Blu-ray': medium_box.val(1); break;
        case 'Remux': medium_box.val(3); break;
        case 'Encode': medium_box.val(7); break;
        case 'WEB-DL': medium_box.val(4); break;
        case 'HDTV': medium_box.val(5); break;
        case 'DVD': medium_box.val(2); break;
        case 'CD': medium_box.val(8); break;
      }
      if (raw_info.name.match(/dvdrip/i)) {
        medium_box.val(6);
      }
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(5);
      switch (raw_info.codec_sel) {
        case 'H265': case 'X265': codec_box.val(6); break;
        case 'H264': case 'X264': codec_box.val(1); break;
        case 'VC-1': codec_box.val(2); break;
        case 'MPEG-2': codec_box.val(3); break;
        case 'MPEG-4': codec_box.val(4); break;
      }
      //音频编码
      var audiocodec_box = $('select[name="audiocodec_sel[4]"]');
      audiocodec_box.val(7);
      switch (raw_info.audiocodec_sel) {
        case 'DTS-HD': audiocodec_box.val(4); break;
        case 'DTS-HDMA:X 7.1': audiocodec_box.val(10); break;
        case 'DTS-HDMA': case 'DTS-HDHR': audiocodec_box.val(10); break;
        case 'TrueHD': case 'Atmos': audiocodec_box.val(14); break;
        case 'AC3':
          audiocodec_box.val(11);
          if (raw_info.name.match(/DD[P\+]/)) {
            audiocodec_box.val(12);
          }
          break;
        case 'AAC': audiocodec_box.val(6); break;
        case 'Flac': audiocodec_box.val(1); break;
        case 'APE': audiocodec_box.val(2); break;
        case 'DTS': audiocodec_box.val(3); break;
        case 'MP3': audiocodec_box.val(4); break;
        case 'WAV': audiocodec_box.val(15); break;
      }
      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = { '8K': 5, '4K': 6, '1080p': 1, '1080i': 2, '720p': 3, 'SD': 4, '': 4 };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }
      //制作组
      $('select[name="team_sel[4]"]').val(5);
      check_team(raw_info, 'team_sel[4]');
    }

    else if (forward_site == '雨') {
      //类型
      var browsecat = $('#browsecat')
      var type_dict = {
        '电影': 401, '剧集': 402, '动漫': 405, '综艺': 403, '音乐': 406, '纪录': 404,
        '体育': 407, 'MV': 406
      };
      browsecat.val(410);
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      //媒介
      var medium_box = $('select[name="medium_sel[4]"]');
      medium_box.val(11);
      switch (raw_info.medium_sel) {
        case 'UHD': case 'Blu-ray': medium_box.val(1); break;
        case 'Remux': medium_box.val(3); break;
        case 'Encode': medium_box.val(7); break;
        case 'WEB-DL': medium_box.val(10); break;
        case 'HDTV': medium_box.val(5); break;
        case 'DVD': medium_box.val(2); break;
        case 'CD': medium_box.val(8); break;
      }
      if (raw_info.name.match(/dvdrip/i)) {
        medium_box.val(6);
      }
      if (raw_info.name.match(/MiniBD/i)) {
        medium_box.val(4);
      }
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(9);
      switch (raw_info.codec_sel) {
        case 'H265': case 'X265': codec_box.val(2); break;
        case 'H264': case 'X264': codec_box.val(1); break;
        case 'VC-1': codec_box.val(7); break;
        case 'MPEG-2': codec_box.val(3); break;
        case 'MPEG-4': codec_box.val(4); break;
        case 'XVID': codec_box.val(5); break;
        case 'VP9': codec_box.val(6); break;
        case 'AV1': codec_box.val(8); break;
      }
      //音频编码
      var audiocodec_box = $('select[name="audiocodec_sel[4]"]');
      audiocodec_box.val(13);
      switch (raw_info.audiocodec_sel) {
        case 'DTS-HD': audiocodec_box.val(7); break;
        case 'DTS-HDMA:X 7.1': audiocodec_box.val(7); break;
        case 'DTS-HDMA': case 'DTS-HDHR': audiocodec_box.val(7); break;
        case 'TrueHD': case 'Atmos': audiocodec_box.val(8); break;
        case 'AC3': audiocodec_box.val(6); break;
        case 'AAC': audiocodec_box.val(4); break;
        case 'Flac': audiocodec_box.val(1); break;
        case 'APE': audiocodec_box.val(2); break;
        case 'WAV': audiocodec_box.val(3); break;
        case 'DTS': audiocodec_box.val(5); break;
        case 'MP3': audiocodec_box.val(4); break;
        case 'LPCM': audiocodec_box.val(9); break;
        case 'M4A': audiocodec_box.val(10); break;
        case 'MP3': audiocodec_box.val(11); break;
      }
      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = { '8K': 8, '4K': 7, '1080p': 1, '1080i': 2, '720p': 3, 'SD': 4, '': 9 };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }
      //制作组
      $('select[name="team_sel[4]"]').val(21);
      check_team(raw_info, 'team_sel[4]');
    }

    else if (forward_site == 'PTLGS') {
      var browsecat = $('#browsecat');
      var type_dict = { '音乐': 409, '体育': 407, 'MV': 406, '综艺': 403, '剧集': 402, '动漫': 405, '纪录': 404, '电影': 401, };
      browsecat.val(0);
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      var medium_box = $('select[name^="medium_sel"]');
      medium_box.val(12);
      switch (raw_info.medium_sel) {
        case 'Blu-ray': case 'UHD': medium_box.val(14); break;
        case 'Encode': medium_box.val(5); break;
        case 'Remux': medium_box.val(8); break;
        case 'WEB-DL': medium_box.val(4); break;
        case 'HDTV': medium_box.val(3); break;
        case 'DVD': medium_box.val(2); break;
        case 'DVDRiP': medium_box.val(11); break;
        case 'CD': medium_box.val(15); break;
      }
      if (raw_info.name.match(/webrip/i)) {
        medium_box.val(7);
      } else if (raw_info.name.match(/tvrip/i)) {
        medium_box.val(2);
      }

      //视频编码
      var codec_box = $('select[name^="codec_sel"]');
      codec_box.val(5);
      switch (raw_info.codec_sel) {
        case 'H.265': case 'H265': case 'HEVC': case 'X265': codec_box.val(6); break;
        case 'AVC': case 'H.264': case 'X264': case 'H264': codec_box.val(7); break;
        case 'VC-1': codec_box.val(2); break;
        case 'MPEG-2': case 'MPEG-4': codec_box.val(4);
      }

      //音频编码
      var audiocodec_box = $('select[name^="audiocodec_sel"]');
      audiocodec_box.val(7);
      switch (raw_info.audiocodec_sel) {
        case 'DTS-HD': case 'DTS-HDMA': case 'DTS-HDHR': audiocodec_box.val(10); break;
        case 'TrueHD': case 'Atmos': audiocodec_box.val(12); break;
        case 'LPCM': audiocodec_box.val(8); break;
        case 'DTS': audiocodec_box.val(19); break;
        case 'AC3': audiocodec_box.val(9); break;
        case 'AAC': audiocodec_box.val(11); break;
        case 'Flac': audiocodec_box.val(13); break;
        case 'APE': audiocodec_box.val(14); break;
        case 'WAV': audiocodec_box.val(1); break;
        case 'MP3': audiocodec_box.val(6); break;
      }

      $('select[name^="team_sel"]').val("13");
      check_team(raw_info, 'team_sel');

      //分辨率
      var standard_box = $('select[name^="standard_sel[4]"]');
      var standard_dict = {
        '2160p': 6, '4K': 6, '1080p': 1, '1080i': 2, '720p': 3, 'SD': 4, '': 7
      };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        standard_box.val(standard_dict[raw_info.standard_sel]);
      }
    }

    else if (forward_site == 'NJTUPT') {
      var browsecat = $('#browsecat');
      var type_dict = { '音乐': 422, '体育': 407, 'MV': 406, '综艺': 403, '剧集': 402, '动漫': 405, '纪录': 404, '电影': 401, '游戏': 425, '学习': 415 };
      browsecat.val(409);
      if (type_dict.hasOwnProperty(raw_info.type)) {
        var index = type_dict[raw_info.type];
        browsecat.val(index);
      }
      //媒介
      var medium_box = $('select[name="medium_sel[4]"]');
      medium_box.val(10);
      switch (raw_info.medium_sel) {
        case 'UHD': case 'Blu-ray': medium_box.val(9); break;
        case 'Remux': medium_box.val(8); break;
        case 'Encode': medium_box.val(7); break;
        case 'WEB-DL': medium_box.val(5); break;
        case 'HDTV': medium_box.val(6); break;
        case 'DVD': medium_box.val(2); break;
      }
      //编码
      var codec_box = $('select[name="codec_sel[4]"]');
      codec_box.val(5);
      switch (raw_info.codec_sel) {
        case 'H264': case 'X264': codec_box.val(1); break;
        case 'VC-1': codec_box.val(2); break;
        case 'H265': case 'X265': codec_box.val(3); break;
        case 'MPEG-2': case 'MPEG-4': codec_box.val(4); break;
        case 'AV1': codec_box.val(6); break;
      }
      var standard_box = $('select[name="standard_sel[4]"]');
      var standard_dict = { '4K': 5, '1080p': 1, '1080i': 2, '720p': 3, 'SD': 4, '': 4 };
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
      }
    }

    else if (forward_site == 'HDT') {
      var announce = 'https://hdts-announce.ru/announce.php';
      addTorrent(raw_info.torrent_url, raw_info.torrent_name, forward_site, announce);
      var category_box = $('select[name="category"]');
      if (raw_info.type == '纪录' && !raw_info.name.match(/[^T]S\d+|E\d+/)) {
        raw_info.type = '电影';
      }
      if (raw_info.type == '纪录' || raw_info.type == '综艺' || raw_info.type == '动漫') {
        if (!raw_info.name.match(/[^T]S\d+|E\d+|Complete/i)) {
          raw_info.type = '电影';
        }
      }
      switch (raw_info.type) {
        case '电影':
          switch (raw_info.medium_sel) {
            case 'UHD': category_box.val('70'); break;
            case 'Blu-ray': category_box.val('1'); break;
            case 'Remux':
              if (raw_info.name.match(/uhd/i)) {
                category_box.val('71');
              } else {
                category_box.val('2');
              }
              break;
            case 'HDTV': case 'Encode': case 'WEB-DL': case 'DVD':
              if (raw_info.standard_sel == '4K') {
                category_box.val('64');
              } else if (raw_info.standard_sel == '1080p' || raw_info.standard_sel == '1080i') {
                category_box.val('5');
              } else if (raw_info.standard_sel == '720p') {
                category_box.val('3');
              }
              break;
          }
          break;
        case '剧集': case '纪录': case '综艺': case '动漫':
          if (raw_info.name.match(/[^T]S\d+[^E]|complete/i)) {
            $('select[name="season"]').val('true');
          }
          switch (raw_info.medium_sel) {
            case 'UHD': category_box.val('72'); break;
            case 'Blu-ray': category_box.val('59'); break;
            case 'Remux':
              if (raw_info.name.match(/uhd/i)) {
                category_box.val('73');
              } else {
                category_box.val('60');
              }
              break;
            case 'HDTV': case 'Encode': case 'WEB-DL': case 'DVD':
              if (raw_info.standard_sel == '4K') {
                category_box.val('65');
              } else if (raw_info.standard_sel == '1080p' || raw_info.standard_sel == '1080i') {
                category_box.val('30');
              } else if (raw_info.standard_sel == '720p') {
                category_box.val('38');
              }
              break;
          }
          break;
      }

      if (raw_info.name.toLowerCase().indexOf(' 3d ') !== -1) {
        document.getElementsByName('3d')[0].options[1].selected = true;
      }

      var mediainfo = get_mediainfo_picture_from_descr(raw_info.descr).mediainfo;
      if (mediainfo.match(/HDR10\+/i)) {
        document.getElementsByName('HDR10Plus')[0].checked = true;
      } else if (mediainfo.match(/HDR10/i)) {
        document.getElementsByName('HDR10')[0].checked = true;
      }
      if (mediainfo.match(/Dolby Vision/i)) {
        document.getElementsByName('DolbyVision')[0].checked = true;
      }
      if (mediainfo.match(/Dolby Atmos/i)) {
        document.getElementsByName('DolbyAtmos')[0].checked = true;
      }
      var mediainfo_hdt = $('textarea[name="info"]').val();

      mediainfo_hdt = mediainfo_hdt.replace(/\[quote\]/g, '[font=consolas]');
      mediainfo_hdt = mediainfo_hdt.replace(/\[\/quote\]/g, '[/font]');
      $('textarea[name="info"]').val(mediainfo_hdt);
    }

    else if (['BLU', 'ACM', 'Monika', 'Tik', 'Aither', 'FNP', 'OnlyEncodes', 'ReelFliX'].indexOf(forward_site) > -1) {
      if (forward_site == 'BLU') {
        var announce = $('a[href*="https://blutopia.cc/announce/"]').attr('href');
      } else if (forward_site == 'Tik') {
        var announce = $('a[href*="https://cinematik.net/"]').attr('href');
      } else {
        var announce = $('h2:contains(announce)').text().replace('Announce URL:', '').trim();
      }
      addTorrent(raw_info.torrent_url, raw_info.torrent_name, forward_site, announce);

      if (raw_info.type == '剧集' || raw_info.type == '综艺' || raw_info.type == '纪录') {
        $('#autocat').val("2");
        try { $('#season_number').val(parseInt(raw_info.name.match(/S(\d+)/i)[1])) } catch (err) { $('#season_number').val("1") }
        try { $('#episode_number').val(parseInt(raw_info.name.match(/E(\d+)/i)[1])) } catch (err) { }
      }
      $('#autocat').on('change', function () {
        if (this.value == '1') {
          var tid = $('#autoimdb').val();
          setTimeout(function () {
            $('#autoimdb').val(tid);
          }, 1000);
        } else if (this.value == '2') {
          var tid = $('#autoimdb').val();
          setTimeout(function () {
            $('#autoimdb').val(tid);
            try { $('#season_number').val(parseInt(raw_info.name.match(/S(\d+)/i)[1])) } catch (err) { $('#season_number').val("1") }
            try { $('#episode_number').val(parseInt(raw_info.name.match(/E(\d+)/i)[1])) } catch (err) { }
          }, 1000);
        }
      });

      var size = 0;
      if (raw_info.medium_sel == 'Blu-ray' || raw_info.medium_sel == 'UHD') {
        size = get_size_from_descr(raw_info.descr);
      }
      var source_box = document.getElementsByName('type_id')[0];
      if (forward_site == 'ACM') {
        switch (raw_info.medium_sel) {
          case 'UHD':
            if (raw_info.name.match(/remux/i)) {
              $('#autotype').val('12');
            } else {
              if (0 <= size && size < 46.57) {
                $('#autotype').val('3');
              } else if (size < 61.47) {
                $('#autotype').val('2');
              } else {
                $('#autotype').val('1');
              }
            }
            break;
          case 'Blu-ray':
            if (0 <= size && size < 23.28) {
              $('#autotype').val('5');
            } else if (size < 46.57) {
              $('#autotype').val('4');
            }
            break;
          case 'Remux': $('#autotype').val('7'); break;
          case 'HDTV': $('#autotype').val('17'); break;
          case 'Encode':
            if (raw_info.standard_sel == '4K') {
              $('#autotype').val('8');
            } else if (raw_info.standard_sel == '1080p' || raw_info.standard_sel == '1080i') {
              $('#autotype').val('10');
            } else if (raw_info.standard_sel == '720p') {
              $('#autotype').val('11');
            } else if (raw_info.standard_sel == 'SD') {
              $('#autotype').val('13');
            }
            break;
          case 'DVD':
            if (raw_info.name.match(/dvd5/i)) {
              $('#autotype').val('14');
            } else {
              $('#autotype').val('16');
            }
            break;
          case 'WEB-DL': $('#autotype').val('9');
        }
        if (raw_info.name.match(/webrip/i)) {
          $('#autotype').val('9');
        }
      } else if (forward_site == 'Tik') {
        if (raw_info.name.match(/dvd5/i)) {
          if (raw_info.descr.match(/Standard.*?PAL/)) {
            $('#autotype').val('10');
          } else {
            $('#autotype').val('8');
          }
        } else if (raw_info.name.match(/dvd9/i)) {
          if (raw_info.descr.match(/Standard.*?PAL/)) {
            $('#autotype').val('9');
          } else {
            $('#autotype').val('7');
          }
        } else if (raw_info.descr.match(/mpls/i) && (raw_info.medium_sel == 'Blu-ray' || raw_info.medium_sel == 'UHD')) {
          try {
            var size = get_size_from_descr(raw_info.descr);
            if (0 <= size && size < 23.28) {
              $('#autotype').val('6');
            } else if (size < 46.57) {
              $('#autotype').val('5');
            } else if (size < 61.47) {
              $('#autotype').val('4');
            } else {
              $('#autotype').val('3');
            }
          } catch (Err) { }
        }
      } else if (forward_site == 'OnlyEncodes') {
        switch (raw_info.medium_sel) {
          case 'UHD': source_box.options[4].selected = true; break;
          case 'Blu-ray': source_box.options[4].selected = true; break;
          case 'Remux': source_box.options[5].selected = true; break;
          case 'HDTV': source_box.options[6].selected = true; break;
          case 'Encode':
            if (raw_info.codec_sel == 'X264' || raw_info.codec_sel == 'H264') {
              source_box.options[2].selected = true;
            } else {
              source_box.options[1].selected = true;
            }
            break;
          case 'WEB-DL': source_box.options[6].selected = true;
        }
      } else {
        switch (raw_info.medium_sel) {
          case 'UHD': source_box.options[1].selected = true; break;
          case 'Blu-ray': source_box.options[1].selected = true; break;
          case 'Remux': source_box.options[2].selected = true; break;
          case 'HDTV': source_box.options[6].selected = true; break;
          case 'Encode': source_box.options[3].selected = true; break;
          case 'WEB-DL': source_box.options[4].selected = true;
        }
        if (raw_info.name.match(/webrip/i)) {
          source_box.options[5].selected = true;
        }
      }

      //分辨率
      var standard_box = $('#autores');
      var standard_dict = { '4K': 2, '1080p': 3, '1080i': 4, '720p': 5, 'SD': 10, '': 10, '8K': 1 };
      if (forward_site == 'ACM') {
        standard_dict = { '4K': 1, '1080p': 2, '1080i': 2, '720p': 3, 'SD': 4, '': 0, '8K': 0 };
      } else if (forward_site == 'BLU') {
        standard_dict = { '4K': 1, '1080p': 2, '1080i': 3, '720p': 5, 'SD': 0, '': 0, '8K': 11 };
      } else if (forward_site == 'Monika') {
        standard_dict = { '4K': 2, '1080p': 3, '1080i': 4, '720p': 5, 'SD': 10, '': 10, '8K': 1 };
      }
      if (standard_dict.hasOwnProperty(raw_info.standard_sel)) {
        var index = standard_dict[raw_info.standard_sel];
        standard_box.val(index);
        $('#resolution_id').val(index);
      }

      if (raw_info.standard_sel == 'SD' || raw_info.medium_sel == 'DVD') {
        $('#sd').prop("checked", true);
      }

      if (raw_info.name.match(/576p/i)) {
        standard_box.val(6);
      } else if (raw_info.name.match(/576i/i)) {
        standard_box.val(7);
      } else if (raw_info.name.match(/480p/i) || (!raw_info.descr.match(/Scan type.*Interlaced/) && raw_info.descr.match(/Height.*?480 pixels/))) {
        standard_box.val(8);
      } else if (raw_info.name.match(/480i/i) || (raw_info.descr.match(/Scan type.*Interlaced/) && raw_info.descr.match(/Height.*?480 pixels/))) {
        standard_box.val(9);
      }

      const ver = ['AUS', 'CAN', 'CEE', 'CZE', 'ESP', 'EUR', 'FRA', 'GBR', 'GER', 'HKG', 'ITA', 'JPN', 'KOR', 'NOR', 'NLD', 'RUS', 'TWN', 'USA'];
      for (i = 0; i < ver.length; i++) {
        var reg = new RegExp('(\\.| )' + ver[i] + '(\\.| )', 'i');
        if (raw_info.name.match(reg)) {
          console.log(ver[i]);
          $('#autoreg option').filter(function () {
            if ($(this).text().trim() == ver[i]) {
              var val = $(this).val();
              $('#autoreg').val(val);
            }
            var i_evt = new Event("change", { bubbles: true, cancelable: false });
            $('#autoreg')[0].dispatchEvent(i_evt);
          });
          break;
        }
      }

      function search_by_name(search_name) {
        var $div = $(`<p class="form__group"></p>`);
        var $table = $(`<table style="width: 100%" class="table table-condensed table-bordered table-striped table-hover"></table>`);
        $div.append($table);
        var search_url;
        if (raw_info.type == '剧集') {
          search_url = 'http://api.tmdb.org/3/search/tv?api_key={key}&language=zh-CN&query={name}&page=1&include_adult=true';
        } else if (raw_info.type == '电影') {
          search_url = 'http://api.tmdb.org/3/search/movie?api_key={key}&language=zh-CN&query={name}&page=1&include_adult=true';
        } else {
          search_url = 'http://api.tmdb.org/3/search/multi?api_key={key}&language=zh-CN&query={name}&page=1&include_adult=true';
        }
        search_url = search_url.format({ 'key': used_tmdb_key, 'name': search_name });

        function compare(date) {
          return function (obj1, obj2) {
            try { var value1 = obj1[date].split('-')[0] + obj1[date].split('-')[1] + obj1[date].split('-')[2]; } catch (err) { value1 = '00000000' }
            try { var value2 = obj2[date].split('-')[0] + obj2[date].split('-')[1] + obj2[date].split('-')[2]; } catch (err) { value2 = '00000000' }
            return value2 - value1;
          }
        }
        getJson(search_url, null, function (data) {
          if (data.results.length > 2) {
            if (raw_info.type == '剧集') {
              data.results = data.results.sort(compare('first_air_date'));
            } else {
              data.results = data.results.sort(compare('release_date'));
            }
          }
          if (data.results.length > 0) {
            data = data.results;
            data.map((e) => {
              var $tr = $("<tr></tr>");
              var media_type = e.media_type;
              if (!media_type) {
                if (raw_info.type == '剧集' || raw_info.name.match(/S\d+|E\d+/)) {
                  media_type = 'tv';
                } else {
                  media_type = 'movie';
                }
              }
              if (media_type == 'tv') {
                $td0 = $(`<td><img src="https://image.tmdb.org/t/p/w300_and_h450_bestv2${e.poster_path}"; style="width:80px; height: 120px;"></td>`);
                $td1 = $(`<td>${e.first_air_date}</td>`);
                $td2 = $(`<td>${e.original_name}</td>`);
                $td3 = $(`<td><a href="https://www.themoviedb.org/TV/${e.id}" target="_blank">${e.name}</a></td>`);
                $td5 = $(`<td><input type="button" class="fill_number" name=${e.id} value="USE"></td>`);
                $tr.append($td0); $tr.append($td1); $tr.append($td2); $tr.append($td3); $tr.append($td5);
              } else {
                $td0 = $(`<td><img src="https://image.tmdb.org/t/p/w300_and_h450_bestv2${e.poster_path}"; style="width: 80px; height: 120px;"></td>`);
                $td1 = $(`<td>${e.release_date}</td>`);
                $td2 = $(`<td>${e.original_title}</td>`);
                $td3 = $(`<td><a href="https://www.themoviedb.org/movie/${e.id}" target="_blank">${e.title}</a></td>`);
                $td5 = $(`<td><input type="button" class="fill_number" name=${e.id} value="USE"></td>`);
                $tr.append($td0); $tr.append($td1); $tr.append($td2); $tr.append($td3); $tr.append($td5);
              }
              $table.append($tr);
            });
            $('.fill_number').css({ 'backgroundColor': 'rgb(70, 77, 96)' });
            $('.fill_number').click(function () {
              $('#autotmdb').val($(this).attr('name'));
              $table.slideUp(500);
              window.scrollTo(0, 500);
            });

            $('#autotmdb').change(function () {
              if (!$(this).val()) {
                $table.slideDown(1000);
              }
            });
            $table.find('td').css({ 'backgroundColor': 'rgb(62, 59, 100)' });
            if (forward_site == 'Tik') {
              $table.find('td').css({ 'backgroundColor': 'rgb(255, 254, 240)' });
            }
            if (forward_site == 'Aither') {
              $table.find('td').css({ 'width': '200px' });
            }
          }
        });
        if (!$('#anime_exists_on_mal').length) {
          $('#apimatch').parent().parent().parent().after($div);
          var color = 'white';
          if (forward_site == 'Tik') {
            color = 'red';
          }
          $('#apimatch').parent().parent().parent().after(`<output name="apimatch" id="apimatch" for="torrent" style="color: ${color};">${raw_info.name}</output>`);
        } else {
          $('#apimatch').parent().parent().after($div);
          $('#apimatch').parent().parent().after(`<output name="apimatch" id="apimatch" for="torrent" style="color: ${color};">${raw_info.name}</output>`);
        }
      }

      if (raw_info.url && used_tmdb_key) {
        var imdb_id = raw_info.url.match(/tt\d+/)[0];
        var search_url = `https://api.themoviedb.org/3/find/${imdb_id}?api_key=${used_tmdb_key}&external_source=imdb_id&include_adult=false&language=zh-CN`;
        getJson(search_url, null, function (data) {
          console.log(data)
          if (data.movie_results.length) {
            $('#auto_tmdb_movie').val(data.movie_results[0].id);
            $('#autotmdb').val(data.movie_results[0].id);
          } else if (data.tv_results.length) {
            $('#auto_tmdb_movie').val(data.tv_results[0].id);
            $('#autotmdb').val(data.movie_results[0].id);
          } else if (data.tv_episode_results.length) {
            $('#auto_tmdb_movie').val(data.tv_episode_results[0].show_id);
            $('#autotmdb').val(data.movie_results[0].id);
          }
          if (!$('#auto_tmdb_movie').val() && !$('#autotmdb').val()) {
            search_by_name(search_name);
          }
        });
      } else if (search_name && used_tmdb_key) {
        search_by_name(search_name);
      }

      try { $('#autoimdb').val(raw_info.url.match(/tt(\d+)/i)[1]); } catch (err) { }
      if (!$('#anime_exists_on_mal').length) {
        $('#automal').val(0);
      }
      $('#anime_exists_on_mal').prop("checked", false);
      var event = new Event('input', { bubbles: true });
      try {
        var infos = get_mediainfo_picture_from_descr(raw_info.descr);
        if (raw_info.multi_mediainfo) {
          var mediainfos = raw_info.multi_mediainfo.match(/\[quote\][\s\S]*?\[\/quote\]/g);
          if (mediainfos.length) {
            for (i = 1; i < mediainfos.length; i++) {
              if (mediainfos[i].match(/\.VOB/)) {
                raw_info.descr = raw_info.descr.replace(infos.mediainfo, mediainfos[i].replace(/\[.*?\]/g, ''));
                infos.mediainfo = mediainfos[i].replace(/\[.*?\]/g, '');
              }
            }
          }
        }
        var container = $('textarea[name="mediainfo"]');
        if (raw_info.descr.match(/MPLS/) && (raw_info.medium_sel == 'Blu-ray' || raw_info.medium_sel == 'UHD')) {
          container = $('textarea[name="bdinfo"]');
